import type { WhatsAppPerformanceView } from "../../../../../api/whatsappAnalyticsApi";

const DAYS = [
  ["2026-09-26", 12, 11, 4, 1],
  ["2026-09-27", 18, 16, 7, 0],
  ["2026-09-28", 9, 9, 3, 1],
  ["2026-09-29", 21, 19, 8, 0],
  ["2026-09-30", 15, 14, 6, 2],
  ["2026-10-01", 11, 10, 4, 0],
  ["2026-10-02", 8, 7, 2, 0],
] as const;

export function buildPerformanceFixture(): WhatsAppPerformanceView {
  const series = DAYS.map(([date, sent, delivered, read, failed]) => ({
    date,
    metaSent: sent,
    metaDelivered: delivered,
    localSent: Math.max(0, sent - 3),
    localDelivered: Math.max(0, delivered - 3),
    localRead: read,
    localFailed: failed,
  }));
  const sent = series.reduce((sum, row) => sum + (row.metaSent || 0), 0);
  const delivered = series.reduce((sum, row) => sum + (row.metaDelivered || 0), 0);
  return {
    samplePreview: true,
    sourcesMixed: false,
    timezone: "UTC",
    demoData: false,
    range: {
      preset: "7",
      since: "2026-09-26",
      until: "2026-10-02",
      days: 7,
      timezone: "UTC",
      clamped: false,
      clampReasons: [],
      templateSince: "2026-09-26",
      templateUntil: "2026-10-02",
      previous: { since: "2026-09-19", until: "2026-09-25" },
    },
    phones: [
      {
        phoneNumberId: "123456789012345",
        displayPhoneNumber: "+972 51-595-3390",
        verifiedName: "Invistimo RSVP",
        digits: "972515953390",
      },
    ],
    selectedPhone: { phoneNumberId: "", scope: "all" },
    sync: {
      lastAttemptAt: "2026-10-02T08:00:00.000Z",
      lastSuccessAt: "2026-10-02T08:00:00.000Z",
      lastError: "",
      lastErrorCode: "",
      rateLimitedUntil: null,
      templateInsightsEnabled: true,
      templateInsightsReason: "",
      messagingAvailable: true,
      messagingReason: "",
      wabaTimezone: "Asia/Jerusalem",
    },
    meta: {
      messaging: {
        available: true,
        reason: null,
        sent,
        delivered,
        read: null,
        readAvailable: false,
        readReason: "NOT_IN_MESSAGING_ANALYTICS",
        deliveryRate: Math.round((delivered / sent) * 1000) / 10,
        partial: false,
        coverage: { requested: 7, covered: 7, missing: [], partial: false },
        series: series.map((row) => ({
          date: row.date,
          sent: row.metaSent,
          delivered: row.metaDelivered,
        })),
        comparison: {
          available: true,
          sent: 70,
          delivered: 64,
          deltas: {
            sent: { value: 34.3, reason: null },
            delivered: { value: 34.4, reason: null },
          },
        },
      },
      templates: {
        available: true,
        reason: null,
        phoneScoped: false,
        readRetention: "READ_RETAINED_7_DAYS",
        rows: [
          {
            templateId: "1",
            name: "appointment_reminder",
            language: "he",
            category: "UTILITY",
            sent: 40,
            delivered: 38,
            read: 21,
            deliveryRate: 95,
            readRate: 55.3,
            clicks: {
              available: true,
              total: 6,
              unique: 5,
              items: [{ type: "quick_reply_button", buttonContent: "אישור", count: 6 }],
            },
            source: "meta_template",
          },
          {
            templateId: "2",
            name: "promo_october",
            language: "he",
            category: "MARKETING",
            sent: 22,
            delivered: 20,
            read: 9,
            deliveryRate: 90.9,
            readRate: 45,
            clicks: {
              available: true,
              total: 4,
              unique: 3,
              items: [{ type: "url_button", buttonContent: "לצפייה", count: 4 }],
            },
            source: "meta_template",
          },
          {
            templateId: "3",
            name: "login_code",
            language: "en",
            category: "AUTHENTICATION",
            sent: 8,
            delivered: 8,
            read: 4,
            deliveryRate: 100,
            readRate: 50,
            clicks: { available: false, total: null, unique: null, items: null },
            source: "meta_template",
          },
        ],
      },
    },
    local: {
      available: true,
      source: "webhook",
      sent: 73,
      delivered: 68,
      read: 34,
      failed: 4,
      apiRejected: 1,
      deliveryRate: 93.2,
      readRate: 50,
      series: series.map((row) => ({
        date: row.date,
        sent: row.localSent || 0,
        delivered: row.localDelivered || 0,
        read: row.localRead || 0,
        failed: row.localFailed || 0,
      })),
      templates: [
        {
          name: "appointment_reminder",
          language: "he",
          category: "",
          sent: 36,
          delivered: 34,
          read: 18,
          failed: 2,
          deliveryRate: 94.4,
          readRate: 52.9,
          clicks: { available: false, total: null, unique: null, items: null },
          source: "webhook",
        },
      ],
      comparison: {
        available: true,
        deltas: {
          read: { value: 12.5, reason: null },
          failed: { value: -20, reason: null },
        },
      },
    },
    series,
  };
}
