const dashboardDemoClients = [
  {
    _id: "c1",
    fullName: "John Miller",
    phone: "+14155552671",
    email: "john.miller@email.com",
    address: "New York, NY",
    status: "Lead",
    lastActivity: "Waiting for reply",
  },
  {
    _id: "c2",
    fullName: "Emily Carter",
    phone: "+14155559832",
    email: "emily.carter@email.com",
    address: "Los Angeles, CA",
    status: "Active",
    lastActivity: "Appointment booked",
  },
  {
    _id: "c3",
    fullName: "Daniel Brooks",
    phone: "+447911123456",
    email: "daniel.brooks@email.com",
    address: "London, UK",
    status: "VIP",
    lastActivity: "Follow-up suggested",
  },
  {
    _id: "c4",
    fullName: "Sarah Johnson",
    phone: "+14155558744",
    email: "sarah.johnson@email.com",
    address: "Austin, TX",
    status: "Active",
    lastActivity: "Reminder sent",
  },
  {
    _id: "c5",
    fullName: "Michael Thompson",
    phone: "+14155553421",
    email: "michael.thompson@email.com",
    address: "Chicago, IL",
    status: "Inactive",
    lastActivity: "No response",
  },
  {
    _id: "c6",
    fullName: "Olivia White",
    phone: "+972545551234",
    email: "olivia.white@email.com",
    address: "Tel Aviv, Israel",
    status: "Lead",
    lastActivity: "New inquiry",
  },
  {
    _id: "c7",
    fullName: "David Anderson",
    phone: "+14155550987",
    email: "david.anderson@email.com",
    address: "Seattle, WA",
    status: "Active",
    lastActivity: "Meeting completed",
  },
  {
    _id: "c8",
    fullName: "Emma Wilson",
    phone: "+447700900321",
    email: "emma.wilson@email.com",
    address: "Manchester, UK",
    status: "Active",
    lastActivity: "Invoice sent",
  },
  {
    _id: "c9",
    fullName: "Robert Lee",
    phone: "+14155557890",
    email: "robert.lee@email.com",
    address: "San Jose, CA",
    status: "VIP",
    lastActivity: "Repeat booking",
  },
  {
    _id: "c10",
    fullName: "Jessica Brown",
    phone: "+14155554321",
    email: "jessica.brown@email.com",
    address: "Boston, MA",
    status: "Lead",
    lastActivity: "Proposal viewed",
  },
  {
    _id: "c11",
    fullName: "Chris Evans",
    phone: "+33612345678",
    email: "chris.evans@email.com",
    address: "Paris, France",
    status: "Active",
    lastActivity: "Call scheduled",
  },
  {
    _id: "c12",
    fullName: "Laura Martinez",
    phone: "+4915123456789",
    email: "laura.martinez@email.com",
    address: "Berlin, Germany",
    status: "Active",
    lastActivity: "Onboarding completed",
  },
];

export default dashboardDemoClients;
