META_BLOCKS = {
    "flameStack": [
        ("header", "charcoal-ember-nav", "Charcoal ember sticky nav"),
        ("hero", "rising-ember-sparks", "Rising ember sparks hero"),
        ("menu", "vertical-meat-timeline", "Vertical meat timeline"),
        ("process", "ember-process-strip", "Ember process strip"),
        ("gallery", "ember-gallery-mosaic", "Ember gallery mosaic"),
        ("reviews", "ember-reviews-rail", "Ember reviews rail"),
        ("hours", "glowing-hour-chips", "Glowing hour chips + stats"),
        ("cta", "ember-home-cta", "Home CTA teaser"),
        ("menuPage", "full-meat-menu", "Full meat menu page"),
        ("grillPage", "coal-process-story", "Grill process story page"),
        ("about", "ash-timeline-portrait", "Ash timeline + pitmaster"),
        ("contact", "ember-reserve-faq", "Ember reserve + FAQ"),
        ("footer", "ember-line", "Ember line footer"),
    ],
    "steamBowl": [
        ("header", "floating-pill-nav", "Floating pill nav"),
        ("hero", "centered-bowl-steam", "Centered bowl steam hero"),
        ("dishes", "radial-circular-dishes", "Radial circular dishes"),
        ("process", "steam-process-steps", "Steam process steps"),
        ("gallery", "steam-round-gallery", "Steam round gallery"),
        ("reviews", "steam-reviews", "Steam reviews"),
        ("stats", "steam-stats-hours", "Steam stats + hours"),
        ("cta", "steam-home-cta", "Home CTA teaser"),
        ("bowlsPage", "full-bowl-menu", "Full bowls menu page"),
        ("brothPage", "broth-lab-story", "Broth lab story page"),
        ("about", "steam-timeline-chef", "Steam timeline + chef"),
        ("contact", "circular-steam-reserve", "Circular reserve + FAQ"),
        ("footer", "noodle-wave-svg", "Noodle wave footer"),
    ],
    "doughStretch": [
        ("header", "stretch-underline-logo", "Stretch underline logo nav"),
        ("hero", "diagonal-rotating-pizza", "Diagonal rotating pizza hero"),
        ("menu", "triangular-masonry", "Triangular masonry menu"),
        ("process", "crust-process-steps", "Crust process steps"),
        ("gallery", "crust-gallery", "Crust gallery"),
        ("reviews", "crust-reviews", "Crust reviews"),
        ("stats", "oven-stats-hours", "Oven stats + hours"),
        ("cta", "crust-home-cta", "Home CTA teaser"),
        ("pizzasPage", "full-pizza-menu", "Full pizza menu page"),
        ("ovenPage", "oven-story", "Oven story page"),
        ("about", "flour-timeline-chef", "Flour timeline + chef"),
        ("contact", "ticket-reserve-faq", "Ticket reserve + FAQ"),
        ("footer", "crust-edge", "Crust edge footer"),
    ],
    "mezzeMosaic": [
        ("header", "olive-branch-nav", "Olive branch underline nav"),
        ("hero", "four-tile-olive-orbs", "4-tile mosaic olive orbs hero"),
        ("platter", "horizontal-platter-scroll", "Horizontal platter scroll"),
        ("process", "mezze-process", "Mezze process"),
        ("gallery", "mezze-gallery", "Mezze gallery"),
        ("reviews", "mezze-reviews", "Mezze reviews"),
        ("stats", "mezze-stats", "Mezze stats + hours"),
        ("cta", "mezze-home-cta", "Home CTA teaser"),
        ("mezzePage", "full-mezze-menu", "Full mezze menu page"),
        ("tablePage", "shared-table-story", "Shared table story page"),
        ("about", "botanical-timeline", "Botanical timeline + chef"),
        ("contact", "garden-reserve-faq", "Garden reserve + FAQ"),
        ("footer", "mezze-shared", "Mezze footer"),
    ],
    "conveyorRail": [
        ("header", "minimal-thin-bar", "Minimal thin bar nav"),
        ("hero", "conveyor-belt-scroll", "Conveyor belt hero"),
        ("nigiri", "nigiri-snap-rail", "Nigiri snap rail"),
        ("process", "zen-process", "Zen process"),
        ("gallery", "zen-gallery", "Zen gallery"),
        ("reviews", "zen-reviews", "Zen reviews"),
        ("stats", "wasabi-pulse-stats", "Wasabi pulse stats"),
        ("cta", "zen-home-cta", "Home CTA teaser"),
        ("omakasePage", "omakase-full-menu", "Omakase full menu page"),
        ("nigiriPage", "nigiri-story", "Nigiri story page"),
        ("about", "zen-timeline-portrait", "Zen timeline + portrait"),
        ("contact", "lacquer-reserve-faq", "Lacquer reserve + FAQ"),
        ("footer", "thin-gold-line", "Thin gold footer"),
    ],
    "sunnyBrunch": [
        ("header", "airy-sunny-circle", "Airy sunny circle logo nav"),
        ("hero", "rotating-sun-rays", "Soft cream sun rays hero"),
        ("gallery", "polaroid-scatter", "Polaroid featured brunch"),
        ("process", "sunny-process", "Sunny process"),
        ("photos", "sunny-gallery", "Sunny gallery"),
        ("reviews", "sunny-reviews", "Sunny reviews"),
        ("hours", "weekend-stats-hours", "Weekend stats + hours"),
        ("cta", "sunny-home-cta", "Home CTA teaser"),
        ("brunchPage", "full-brunch-menu", "Full brunch menu page"),
        ("coffeePage", "coffee-story", "Coffee story page"),
        ("about", "note-timeline-chef", "Note timeline + chef"),
        ("contact", "postcard-reserve-faq", "Postcard reserve + FAQ"),
        ("footer", "dotted-napkin", "Dotted napkin footer"),
    ],
    "nightTapas": [
        ("header", "neon-glow-logo", "Neon glow logo nav"),
        ("hero", "cascade-small-plates", "Cascade rising plates hero"),
        ("menu", "bento-grid-tapas", "Bento grid menu"),
        ("process", "neon-process", "Neon process"),
        ("gallery", "neon-gallery", "Neon gallery"),
        ("reviews", "neon-reviews", "Neon reviews"),
        ("stats", "neon-stats", "Neon stats + hours"),
        ("cta", "neon-home-cta", "Home CTA teaser"),
        ("tapasPage", "full-tapas-menu", "Full tapas menu page"),
        ("barPage", "bar-story", "Bar story page"),
        ("about", "chalk-timeline", "Chalk timeline + chef"),
        ("contact", "bar-tab-reserve-faq", "Bar-tab reserve + FAQ"),
        ("footer", "neon-flicker", "Neon flicker footer"),
    ],
    "spiceWheel": [
        ("header", "ornate-bordered-nav", "Ornate bordered nav"),
        ("hero", "spice-particle-fall", "Spice particle fall hero"),
        ("menu", "conic-spice-wheel", "Conic-gradient spice wheel"),
        ("process", "spice-process", "Spice process"),
        ("gallery", "spice-gallery", "Spice gallery"),
        ("reviews", "spice-reviews", "Spice reviews"),
        ("stats", "spice-stats", "Spice stats + hours"),
        ("cta", "spice-home-cta", "Home CTA teaser"),
        ("thaliPage", "full-thali-menu", "Full thali menu page"),
        ("spicesPage", "spice-room-story", "Spice room story page"),
        ("about", "terra-timeline", "Terracotta timeline + chef"),
        ("contact", "thali-reserve-faq", "Thali reserve + FAQ"),
        ("footer", "spice-dots", "Spice dots footer"),
    ],
    "cellarDepth": [
        ("header", "centered-elegant-serif", "Centered elegant serif nav"),
        ("hero", "parallax-cellar-layers", "Parallax cellar depth hero"),
        ("tasting", "vertical-notes-timeline", "Vertical tasting notes"),
        ("process", "cellar-process", "Cellar process"),
        ("gallery", "cellar-gallery", "Cellar gallery"),
        ("reviews", "cellar-reviews", "Cellar reviews"),
        ("stats", "cellar-stats", "Cellar stats + hours"),
        ("cta", "cellar-home-cta", "Home CTA teaser"),
        ("winesPage", "full-wine-list", "Full wine list page"),
        ("tastingPage", "tasting-story", "Tasting story page"),
        ("about", "letterpress-timeline", "Letterpress timeline + chef"),
        ("contact", "elegant-reserve-faq", "Elegant reserve + FAQ"),
        ("footer", "vintage-stamp", "Vintage stamp footer"),
    ],
    "neonStreet": [
        ("header", "sticker-badge-nav", "Sticker badge nav"),
        ("hero", "truck-slide-neon-title", "Food truck + neon title hero"),
        ("stack", "night-market-card-stack", "Night market vertical stack"),
        ("process", "street-process", "Street process"),
        ("gallery", "street-gallery", "Street gallery"),
        ("reviews", "street-reviews", "Street reviews"),
        ("stats", "street-stats-pins", "Street stats + hours"),
        ("cta", "street-home-cta", "Home CTA teaser"),
        ("trucksPage", "full-truck-menu", "Full truck menu page"),
        ("spotsPage", "city-spots-story", "City spots story page"),
        ("about", "comic-timeline", "Comic timeline + chef"),
        ("contact", "sms-reserve-faq", "SMS reserve + FAQ"),
        ("footer", "ticket-tear", "Ticket tear footer"),
    ],
}
