"""Exact translations for high-value built-in template / library Hebrew strings."""


def r(en, es, pt, ar):
    return {"en": en, "es": es, "pt-BR": pt, "ar": ar}


EXACT = {
    # Categories and chrome
    "חנויות ומסחר": r("Stores and commerce", "Tiendas y comercio", "Lojas e comércio", "متاجر وتجارة"),
    "דפי נחיתה": r("Landing pages", "Landing pages", "Landing pages", "صفحات هبوط"),
    "יופי וטיפוח": r("Beauty and care", "Belleza y cuidado", "Beleza e cuidado", "جمال وعناية"),
    "פורטפוליו וסוכנות": r("Portfolio and agency", "Portafolio y agencia", "Portfólio e agência", "معرض أعمال ووكالة"),
    "אוכל ומסעדות": r("Food and restaurants", "Comida y restaurantes", "Comida e restaurantes", "طعام ومطاعم"),
    "נדל״ן": r("Real estate", "Inmobiliaria", "Imobiliário", "عقارات"),
    "תיירות וחוף": r("Travel and beach", "Turismo y playa", "Turismo e praia", "سياحة وشاطئ"),
    "חינוך וקורסים": r("Education and courses", "Educación y cursos", "Educação e cursos", "تعليم ودورات"),
    "עסקים ושירותים": r("Business and services", "Negocios y servicios", "Negócios e serviços", "أعمال وخدمات"),
    "עסקים": r("Business", "Negocios", "Negócios", "أعمال"),
    "קפה ואוכל": r("Coffee and food", "Café y comida", "Café e comida", "قهوة وطعام"),
    "אירוח ומלונאות": r("Hospitality and hotels", "Hospitalidad y hoteles", "Hospitalidade e hotéis", "ضيافة وفنادق"),
    "סייבר ואבטחה": r("Cyber and security", "Ciberseguridad", "Cibersegurança", "أمن سيبراني"),
    "נוף וגינון": r("Landscape and gardening", "Paisaje y jardinería", "Paisagismo e jardinagem", "حدائق ومناظر"),
    "קריאייטיב ועיצוב": r("Creative and design", "Creatividad y diseño", "Criativo e design", "إبداع وتصميم"),
    "תעשייה וייצור": r("Industry and manufacturing", "Industria y fabricación", "Indústria e fabricação", "صناعة وتصنيع"),
    "אירועים וחתונות": r("Events and weddings", "Eventos y bodas", "Eventos e casamentos", "فعاليات وأعراس"),
    "עסקים וייעוץ": r("Business and consulting", "Negocios y consultoría", "Negócios e consultoria", "أعمال واستشارات"),
    "רפואה ובריאות": r("Medicine and health", "Medicina y salud", "Medicina e saúde", "طب وصحة"),
    "כושר וספורט": r("Fitness and sport", "Fitness y deporte", "Fitness e esporte", "لياقة ورياضة"),
    "אדריכלות ובנייה": r("Architecture and construction", "Arquitectura y construcción", "Arquitetura e construção", "عمارة وبناء"),
    "עורכי דין": r("Law firms", "Despachos de abogados", "Escritórios de advocacia", "مكاتب محاماة"),
    "חנויות / אופנה": r("Stores / fashion", "Tiendas / moda", "Lojas / moda", "متاجر / أزياء"),
    "טכנולוגיה": r("Technology", "Tecnología", "Tecnologia", "تكنولوجيا"),
    "פיננסים וחשבונאות": r("Finance and accounting", "Finanzas y contabilidad", "Finanças e contabilidade", "مالية ومحاسبة"),
    "תרבות ואמנות": r("Culture and art", "Cultura y arte", "Cultura e arte", "ثقافة وفن"),
    "שירותים מקצועיים": r("Professional services", "Servicios profesionales", "Serviços profissionais", "خدمات مهنية"),
    "חנות ואיקומרס": r("Store and ecommerce", "Tienda y comercio", "Loja e e-commerce", "متجر وتجارة إلكترونية"),
    "תיק עבודות": r("Portfolio", "Portafolio", "Portfólio", "معرض أعمال"),
    "נדל״ן יוקרה": r("Luxury real estate", "Inmobiliaria de lujo", "Imobiliário de luxo", "عقارات فاخرة"),
    "פורטפolio וצילום": r("Portfolio and photography", "Portafolio y fotografía", "Portfólio e fotografia", "معرض وتصوير"),

    # Beauty / studio ritual copy
    "מנהלת מקצועית": r("Professional manager", "Directora profesional", "Gerente profissional", "مديرة مهنية"),
    "הטקס שלנו": r("Our ritual", "Nuestro ritual", "Nosso ritual", "طقوسنا"),
    "רגעים מהסטודיו": r("Moments from the studio", "Momentos del estudio", "Momentos do estúdio", "لحظات من الاستوديو"),
    "מה הלקוחות מספרות": r("What clients say", "Lo que cuentan las clientas", "O que as clientes contam", "ماذا تقول العميلات"),
    "מוכנות לתור הבא?": r("Ready for the next appointment?", "¿Listas para la próxima cita?", "Prontas para o próximo horário?", "جاهزات للموعد التالي؟"),
    "מאיפה הכל התחיל": r("Where it all started", "Dónde empezó todo", "Onde tudo começou", "من أين بدأ كل شيء"),
    "סיור בחלל": r("A tour of the space", "Recorrido por el espacio", "Tour pelo espaço", "جولة في المكان"),
    "החלל בנוי כשביל חוויה: קבלת פנים שקטה, אזורי טיפול מוארים נכון, עמדות עבודה סטריליות ופינת סיום עם מראה, מוצרים והסבר אישי.": r(
        "The space is built as a journey: a quiet welcome, well-lit treatment areas, sterile work stations, and a finishing corner with a mirror, products, and a personal recap.",
        "El espacio es un recorrido: bienvenida silenciosa, zonas de tratamiento bien iluminadas, puestos estériles y un rincón final con espejo, productos y explicación personal.",
        "O espaço é um percurso: recepção silenciosa, áreas de tratamento bem iluminadas, estações estéreis e um canto final com espelho, produtos e explicação pessoal.",
        "المكان مبني كمسار تجربة: ترحيب هادئ، مناطق علاج بإضاءة صحيحة، محطات عمل معقمة وركن ختام بمرآة ومنتجات وشرح شخصي.",
    ),
    "הערכים שמנחים אותנו": r("The values that guide us", "Los valores que nos guían", "Os valores que nos guiam", "القيم التي توجهنا"),
    "דיוק, היגיינה, שקיפות ורוגע הם לא סיסמאות אצלנו — הם מופיעים בלוח התורים, בבחירת החומרים, בקצב העבודה ובשיחה שאחרי הטיפול.": r(
        "Precision, hygiene, transparency, and calm are not slogans here — they show up in the booking board, the materials we choose, the pace of the work, and the conversation after treatment.",
        "La precisión, la higiene, la transparencia y la calma no son eslóganes: aparecen en la agenda, en los materiales, en el ritmo y en la conversación después del tratamiento.",
        "Precisão, higiene, transparência e calma não são slogans: aparecem na agenda, nos materiais, no ritmo e na conversa depois do tratamento.",
        "الدقة والنظافة والشفافية والهدوء ليست شعارات لدينا — تظهر في لوحة المواعيد واختيار المواد وإيقاع العمل والحديث بعد العلاج.",
    ),
    "המומחיות שלנו": r("Our expertise", "Nuestra especialidad", "Nossa especialidade", "خبرتنا"),
    "מאחורי כל טיפול עומדת מומחית עם הכשרה, תיק עבודות ותהליך עבודה ברור. אנחנו מחלקות תפקידים לפי ניסיון, רגישות וסוג התוצאה המבוקשת.": r(
        "Behind every treatment is a specialist with training, a portfolio, and a clear process. We assign roles by experience, sensitivity, and the result you want.",
        "Detrás de cada tratamiento hay una especialista con formación, portafolio y un proceso claro. Repartimos roles según experiencia, sensibilidad y el resultado deseado.",
        "Por trás de cada tratamento há uma especialista com formação, portfólio e um processo claro. Dividimos papéis por experiência, sensibilidade e o resultado desejado.",
        "خلف كل علاج تقف مختصة بتدريب ومعرض أعمال وعملية واضحة. نوزّع الأدوار حسب الخبرة والحساسية ونوع النتيجة المطلوبة.",
    ),
    "הסמכות והכשרות": r("Certifications and training", "Certificaciones y formación", "Certificações e formação", "اعتمادات وتدريب"),
    "הצוות עובר רענון חיטוי, הכשרות מוצר והדרכות בטיחות לאורך השנה, כדי לשמור על תוצאה עקבית ועל סביבת טיפול בטוחה.": r(
        "The team refreshes sanitation, product training, and safety briefings throughout the year so results stay consistent and the treatment space stays safe.",
        "El equipo actualiza higiene, formación de producto y seguridad a lo largo del año para mantener un resultado constante y un espacio seguro.",
        "A equipe atualiza higiene, treino de produto e segurança ao longo do ano para manter resultado consistente e um espaço seguro.",
        "يمرّ الفريق بتحديث تعقيم وتدريب منتجات وإرشادات سلامة على مدار السنة للحفاظ على نتيجة ثابتة وبيئة علاج آمنة.",
    ),
    "ציר הזמן": r("Timeline", "Línea de tiempo", "Linha do tempo", "الجدول الزمني"),
    "מה כותבים עלינו": r("What people write about us", "Qué escriben sobre nosotras", "O que escrevem sobre nós", "ماذا يُكتب عنا"),
    "לקוחות ועורכות יופי מתארות בעיקר את השילוב בין שקט, סדר, דיוק ותוצאה שנראית טבעית גם אחרי כמה ימים.": r(
        "Clients and beauty editors mostly describe the mix of quiet, order, precision, and a result that still looks natural days later.",
        "Clientas y editoras de belleza destacan la mezcla de calma, orden, precisión y un resultado que sigue viéndose natural días después.",
        "Clientes e editoras de beleza descrevem a mistura de silêncio, ordem, precisão e um resultado que continua natural dias depois.",
        "تصف العميلات ومحررات الجمال أساساً المزج بين الهدوء والترتيب والدقة ونتيجة تبدو طبيعية حتى بعد عدة أيام.",
    ),
    "בואו להכיר מקרוב": r("Come meet us up close", "Ven a conocernos de cerca", "Venha nos conhecer de perto", "تعالوا للتعرّف عن قرب"),
    "קטלוג טיפולים": r("Treatment catalog", "Catálogo de tratamientos", "Catálogo de tratamentos", "كتالوج علاجات"),
    "כל השירותים": r("All services", "Todos los servicios", "Todos os serviços", "كل الخدمات"),
    "כל שירות מוצג עם משך, הכנה, תוצאה צפויה ותוספות אפשריות כדי לעזור לכן לבחור נכון עוד לפני התור.": r(
        "Every service shows duration, prep, the expected result, and optional add-ons so you can choose well before the appointment.",
        "Cada servicio muestra duración, preparación, resultado esperado y extras para elegir bien antes de la cita.",
        "Cada serviço mostra duração, preparo, resultado esperado e extras para escolher bem antes do horário.",
        "يُعرض كل خدمة مع المدة والتحضير والنتيجة المتوقعة والإضافات الممكنة لمساعدتكم على الاختيار قبل الموعد.",
    ),
    "טיפול הדגל": r("Signature treatment", "Tratamiento estrella", "Tratamento destaque", "العلاج المميز"),
    "טיפול הדגל משלב אבחון אישי, הכנת אזור מדויקת, עבודה בשכבות וסיום שמותאם לשגרת הבית. הוא מתאים למי שרוצה תוצאה מורגשת בלי לוותר על תחושה טבעית.": r(
        "The signature treatment combines a personal assessment, precise area prep, layered work, and a finish fitted to your home routine. It is for anyone who wants a visible result without losing a natural feel.",
        "El tratamiento estrella combina diagnóstico personal, preparación precisa, trabajo por capas y un cierre adaptado a tu rutina. Para quien quiere un resultado visible sin perder naturalidad.",
        "O tratamento destaque combina diagnóstico pessoal, preparo preciso, trabalho em camadas e um acabamento adaptado à rotina. Para quem quer resultado visível sem perder a naturalidade.",
        "يجمع العلاج المميز بين تشخيص شخصي وتحضير دقيق للمنطقة وعمل بطبقات وختام يناسب روتين المنزل. يناسب من يريد نتيجة ملموسة دون التخلي عن الإحساس الطبيعي.",
    ),
    "מדריך משך טיפול": r("Treatment duration guide", "Guía de duración", "Guia de duração", "دليل مدة العلاج"),
    "משך הטיפול כולל זמן התאמה, הכנה וסיכום. אנחנו משאירות מרווחים בין תורים כדי לאפשר עבודה רגועה ולא לדחוס לקוחות.": r(
        "Treatment time includes fitting, prep, and a wrap-up. We leave gaps between appointments so the work stays calm and we never rush clients.",
        "La duración incluye ajuste, preparación y cierre. Dejamos huecos entre citas para trabajar con calma y no apretar a las clientas.",
        "A duração inclui ajuste, preparo e encerramento. Deixamos intervalos entre horários para trabalhar com calma e não apressar clientes.",
        "تشمل مدة العلاج وقت الملاءمة والتحضير والخلاصة. نترك فجوات بين المواعيد لعمل هادئ دون حشر العميلات.",
    ),
    "תוספות מומלצות": r("Recommended add-ons", "Extras recomendados", "Extras recomendados", "إضافات موصى بها"),
    "תוספות קטנות יכולות לשנות את החוויה: מסכה מרגיעה, עיסוי קצר, אמפולה ממוקדת או צילום תוצאה לתיעוד אישי.": r(
        "Small add-ons can change the experience: a calming mask, a short massage, a targeted ampoule, or a result photo for your own record.",
        "Los extras pequeños cambian la experiencia: mascarilla calmante, masaje breve, ampolla puntual o foto del resultado.",
        "Extras pequenos mudam a experiência: máscara calmante, massagem curta, ampola pontual ou foto do resultado.",
        "إضافات صغيرة قد تغيّر التجربة: قناع مهدئ، تدليك قصير، أمبولة مركّزة أو تصوير النتيجة للتوثيق الشخصي.",
    ),
    "ההשוואה מציגה שינוי אמיתי ועדין: ניקיון, סימטריה, ברק או מרקם טוב יותר — בלי הבטחות מוגזמות ועם הסבר איך לשמור על התוצאה.": r(
        "The comparison shows a real, subtle change: cleanliness, symmetry, glow, or a better texture — no exaggerated promises, with a note on how to keep the result.",
        "La comparación muestra un cambio real y sutil: limpieza, simetría, brillo o mejor textura, sin promesas exageradas y con cómo cuidar el resultado.",
        "A comparação mostra uma mudança real e sutil: limpeza, simetria, brilho ou melhor textura, sem promessas exageradas e com como manter o resultado.",
        "تعرض المقارنة تغييراً حقيقياً ولطيفاً: نظافة وتناسق ولمعان أو ملمساً أفضل — بلا وعود مبالغ فيها ومع شرح لكيفية الحفاظ على النتيجة.",
    ),
    "מחירון שקוף": r("Transparent pricing", "Precios transparentes", "Preços transparentes", "أسعار شفافة"),
    "המחירים כוללים את זמן הייעוץ, חומרי העבודה והנחיות ההמשך. לפני כל תוספת תקבלו הסבר ואישור.": r(
        "Prices include consultation time, working materials, and aftercare notes. Before any add-on you get an explanation and approval.",
        "Los precios incluyen la consulta, los materiales y las indicaciones. Antes de cada extra recibirás explicación y confirmación.",
        "Os preços incluem a consulta, os materiais e as orientações. Antes de cada extra você recebe explicação e confirmação.",
        "تشمل الأسعار وقت الاستشارة ومواد العمل وإرشادات المتابعة. قبل أي إضافة ستحصلون على شرح وموافقة.",
    ),
    "שאלות על טיפולים": r("Questions about treatments", "Preguntas sobre tratamientos", "Perguntas sobre tratamentos", "أسئلة عن العلاجات"),
    "רוצות לקבוע?": r("Want to book?", "¿Quieren reservar?", "Querem agendar?", "تريدون الحجز؟"),
    "בחרו יום ושעה": r("Choose a day and time", "Elige día y hora", "Escolha dia e horário", "اختاروا يوماً ووقتاً"),
    "בחירת טיפול": r("Choose a treatment", "Elegir tratamiento", "Escolher tratamento", "اختيار علاج"),
    "בחירת מומחית": r("Choose a specialist", "Elegir especialista", "Escolher especialista", "اختيار مختصة"),
    "מדיניות ביטולים": r("Cancellation policy", "Política de cancelación", "Política de cancelamento", "سياسة الإلغاء"),
    "פרטי יצירת קשר": r("Contact details", "Datos de contacto", "Dados de contato", "بيانات التواصل"),
    "איך מגיעים": r("How to get here", "Cómo llegar", "Como chegar", "كيف تصلون"),
    "שאלות על תורים": r("Questions about appointments", "Preguntas sobre citas", "Perguntas sobre horários", "أسئلة عن المواعيد"),
    "מומחית טיפולים": r("Treatment specialist", "Especialista en tratamientos", "Especialista em tratamentos", "مختصة علاجات"),
    "אחראית חוויית לקוחה": r("Client experience lead", "Responsable de experiencia", "Responsável pela experiência", "مسؤولة تجربة العميلة"),
    "יצאתי עם תחושה שנדיר למצוא — מקצועיות אמיתית ואווירה שנשארת איתך.": r(
        "I left with a feeling that is rare to find — real professionalism and an atmosphere that stays with you.",
        "Salí con una sensación difícil de encontrar: profesionalidad real y un ambiente que se queda contigo.",
        "Saí com uma sensação rara: profissionalismo de verdade e uma atmosfera que fica com você.",
        "خرجت بشعور نادر — احتراف حقيقي وأجواء تبقى معك.",
    ),
    "התיאום היה פשוט, הטיפול מדויק, והתוצאה בדיוק כמו שרציתי.": r(
        "Booking was simple, the treatment was precise, and the result was exactly what I wanted.",
        "La reserva fue sencilla, el tratamiento preciso y el resultado exactamente como quería.",
        "O agendamento foi simples, o tratamento preciso e o resultado exatamente o que eu queria.",
        "كان التنسيق بسيطاً والعلاج دقيقاً والنتيجة تماماً كما أردت.",
    ),
    "מקום שנעים לחזור אליו. מרגישות שמקשיבים באמת.": r(
        "A place you are glad to come back to. You feel truly listened to.",
        "Un lugar al que apetece volver. Se siente que de verdad escuchan.",
        "Um lugar a que dá gosto voltar. Dá para sentir que escutam de verdade.",
        "مكان يسرّ الرجوع إليه. تشعران أن الإصغاء حقيقي.",
    ),
    "לקוחה": r("Client", "Clienta", "Cliente", "عميلة"),
    "כמה זמן מראש כדאי לקבוע?": r("How far ahead should I book?", "¿Con cuánta antelación conviene reservar?", "Com quanta antecedência devo agendar?", "كم مسبقاً يُفضّل الحجز؟"),
    "מומלץ שבוע–שבועיים מראש, ובסופי שבוע אפילו קצת יותר.": r(
        "A week or two ahead is best, and a bit more for weekends.",
        "Conviene una o dos semanas, y un poco más los fines de semana.",
        "O ideal é uma ou duas semanas, e um pouco mais nos fins de semana.",
        "يُفضّل أسبوع إلى أسبوعين مسبقاً، وفي عطلة نهاية الأسبوع أكثر قليلاً.",
    ),
    "מה מדיניות הביטול?": r("What is the cancellation policy?", "¿Cuál es la política de cancelación?", "Qual é a política de cancelamento?", "ما سياسة الإلغاء؟"),
    "ניתן לבטל או לשנות עד 24 שעות לפני התור ללא חיוב.": r(
        "You can cancel or change up to 24 hours before the appointment at no charge.",
        "Puedes cancelar o cambiar hasta 24 horas antes sin cargo.",
        "Pode cancelar ou alterar até 24 horas antes sem cobrança.",
        "يمكن الإلغاء أو التغيير حتى 24 ساعة قبل الموعد دون رسوم.",
    ),
    "כן — חניון קרוב או חניה ברחוב לפי המיקום. נפרט בהודעת האישור.": r(
        "Yes — nearby parking or street parking depending on the location. We will include details in the confirmation.",
        "Sí: parking cercano o en la calle según la ubicación. Lo detallamos en la confirmación.",
        "Sim — estacionamento perto ou na rua, conforme o local. Detalhamos na confirmação.",
        "نعم — موقف قريب أو وقوف في الشارع حسب الموقع. سنفصّل ذلك في رسالة التأكيد.",
    ),
    "השאירו פרטים": r("Leave your details", "Deja tus datos", "Deixe seus dados", "اتركوا بياناتكم"),
    "נחזור אליכן לאישור התור בהקדם.": r(
        "We will get back to you soon to confirm the appointment.",
        "Volveremos pronto para confirmar la cita.",
        "Voltaremos em breve para confirmar o horário.",
        "سنعود إليكن قريباً لتأكيد الموعد.",
    ),
    "א׳–ה׳ 09:00–20:00 · ו׳ 09:00–14:00": r(
        "Sun–Thu 09:00–20:00 · Fri 09:00–14:00",
        "Dom–jue 09:00–20:00 · vie 09:00–14:00",
        "Dom–qui 09:00–20:00 · sex 09:00–14:00",
        "الأحد–الخميس 09:00–20:00 · الجمعة 09:00–14:00",
    ),
    "הרגע שלכן מתחיל כאן.": r("Your moment starts here.", "Vuestro momento empieza aquí.", "O momento de vocês começa aqui.", "لحظتكن تبدأ هنا."),
    "בחרו טיפול, יום ושעה — ואנחנו נדאג לשאר.": r(
        "Choose a treatment, day, and time — we will take care of the rest.",
        "Elige tratamiento, día y hora; nosotras nos ocupamos del resto.",
        "Escolha tratamento, dia e horário — nós cuidamos do resto.",
        "اخترن علاجاً ويوماً ووقتاً — وسنتولى الباقي.",
    ),
    "חבילת Soft": r("Soft package", "Paquete Soft", "Pacote Soft", "باقة Soft"),
    "טיפול יחיד עם ייעוץ פתיחה, התאמת חומרי עבודה וסיכום כתוב להמשך בבית.": r(
        "A single treatment with an opening consult, product matching, and written notes for home care.",
        "Un tratamiento con consulta inicial, ajuste de materiales y un resumen escrito para casa.",
        "Um tratamento com consulta inicial, ajuste de materiais e um resumo escrito para casa.",
        "علاج واحد مع استشارة افتتاح وملاءمة مواد وملخص مكتوب للمتابعة في المنزل.",
    ),
    "חבילת Glow": r("Glow package", "Paquete Glow", "Pacote Glow", "باقة Glow"),
    "שלושה טיפולים מתוכננים מראש, מעקב תוצאה בין ביקורים ותזכורות לשמירה על רצף.": r(
        "Three planned treatments, result follow-up between visits, and reminders to keep the rhythm.",
        "Tres tratamientos planificados, seguimiento entre visitas y recordatorios para no romper el ritmo.",
        "Três tratamentos planejados, acompanhamento entre visitas e lembretes para manter o ritmo.",
        "ثلاثة علاجات مخططة مسبقاً ومتابعة النتيجة بين الزيارات وتذكيرات للحفاظ على التسلسل.",
    ),
    "חבילת Ritual": r("Ritual package", "Paquete Ritual", "Pacote Ritual", "باقة Ritual"),
    "יום טיפוח מלא עם תוספות, הפסקת שתייה, צילום תוצאה ותיאום תור המשך לפי הצורך.": r(
        "A full care day with add-ons, a drink break, a result photo, and a follow-up booking if you need one.",
        "Un día de cuidado completo con extras, pausa para beber, foto del resultado y cita de seguimiento si hace falta.",
        "Um dia completo de cuidado com extras, pausa para bebida, foto do resultado e horário de continuidade se precisar.",
        "يوم عناية كامل مع إضافات واستراحة مشروب وتصوير النتيجة وتنسيق موعد متابعة عند الحاجة.",
    ),
    "ביטול עד 24 שעות · איחור מעל 15 דק׳ עלול לקצר את הטיפול · בריאות מעל הכל.": r(
        "Cancel up to 24 hours · arriving more than 15 minutes late may shorten the treatment · health comes first.",
        "Cancelación hasta 24 h · un retraso de más de 15 min puede acortar el tratamiento · la salud es lo primero.",
        "Cancelamento até 24 h · atraso acima de 15 min pode encurtar o tratamento · saúde em primeiro lugar.",
        "إلغاء حتى 24 ساعة · التأخير أكثر من 15 د قد يقصّر العلاج · الصحة أولاً.",
    ),

    # Store / commerce
    "הזמינו עכשיו": r("Order now", "Pedir ahora", "Pedir agora", "اطلبوا الآن"),
    "לכל המוצרים": r("All products", "Todos los productos", "Todos os produtos", "كل المنتجات"),
    "בחרו קטגוריה ועברו ישירות לסינון חי בחנות.": r(
        "Pick a category and jump straight into live filtering in the store.",
        "Elige una categoría y pasa al filtro en vivo de la tienda.",
        "Escolha uma categoria e vá direto ao filtro ao vivo da loja.",
        "اختاروا فئة وانتقلوا مباشرة إلى التصفية الحية في المتجر.",
    ),
    "אוספים שנבנו סביב חוויית קנייה אמיתית.": r(
        "Collections built around a real shopping experience.",
        "Colecciones pensadas para una compra real.",
        "Coleções feitas para uma experiência de compra real.",
        "مجموعات بُنيت حول تجربة تسوق حقيقية.",
    ),
    "כל קולקציה מובילה למוצרים שמגיעים מתוסף החנות.": r(
        "Every collection leads to products that come from the store plugin.",
        "Cada colección lleva a productos del plugin de la tienda.",
        "Cada coleção leva a produtos do plugin da loja.",
        "كل مجموعة تؤدي إلى منتجات تأتي من إضافة المتجر.",
    ),
    "אביזרים": r("Accessories", "Accesorios", "Acessórios", "إكسسوارات"),
    "אקססוריז": r("Accessories", "Accesorios", "Acessórios", "إكسسوارات"),
    "מוצרים שנבחרו לתצוגה עשירה.": r(
        "Products chosen for a rich display.",
        "Productos elegidos para una vitrina rica.",
        "Produtos escolhidos para uma vitrine rica.",
        "منتجات اختيرت لعرض غني.",
    ),
    "הקטלוג נטען מתוסף החנות — עם דמו עד שתמלאו מוצרים אמיתיים.": r(
        "The catalog loads from the store plugin — with demo items until you add real products.",
        "El catálogo se carga del plugin de la tienda, con demo hasta que añadas productos reales.",
        "O catálogo vem do plugin da loja — com demo até você cadastrar produtos reais.",
        "يُحمَّل الكتالوج من إضافة المتجر — مع محتوى تجريبي حتى تملأوا منتجات حقيقية.",
    ),
    "בחירה מדויקת": r("A precise choice", "Una elección precisa", "Uma escolha precisa", "اختيار دقيق"),
    "כל מוצר מוצג עם קטגוריה, מחיר ותיאור ברור.": r(
        "Every product shows a category, price, and a clear description.",
        "Cada producto muestra categoría, precio y una descripción clara.",
        "Cada produto mostra categoria, preço e uma descrição clara.",
        "يُعرض كل منتج مع فئة وسعر ووصف واضح.",
    ),
    "חוויית קנייה מלאה": r("A full shopping experience", "Una experiencia de compra completa", "Uma experiência de compra completa", "تجربة تسوق كاملة"),
    "11 עמודים עם סינון, סל, גלריה, אודות ומשלוחים.": r(
        "11 pages with filtering, cart, gallery, about, and shipping.",
        "11 páginas con filtro, carrito, galería, acerca de y envíos.",
        "11 páginas com filtro, carrinho, galeria, sobre e entregas.",
        "11 صفحة مع تصفية وسلة ومعرض وحول وشحن.",
    ),
    "עיצוב ייחודי": r("Distinctive design", "Diseño único", "Design exclusivo", "تصميم مميز"),
    "תמונות שמספרות את האווירה של המותג.": r(
        "Photos that tell the brand’s atmosphere.",
        "Fotos que cuentan el ambiente de la marca.",
        "Fotos que contam a atmosfera da marca.",
        "صور تروي أجواء العلامة.",
    ),
    "גלריה עשירה עם סצנות מוצר ואטמוספירה.": r(
        "A rich gallery with product scenes and atmosphere.",
        "Una galería rica con escenas de producto y ambiente.",
        "Uma galeria rica com cenas de produto e atmosfera.",
        "معرض غني بمشاهد المنتج والأجواء.",
    ),
    "מה אומרים מי שכבר קנו.": r("What people who already bought say.", "Lo que dicen quienes ya compraron.", "O que dizem quem já comprou.", "ماذا يقول من اشترى بالفعل."),
    "האתר מרגיש כמו חנות אמיתית — עשיר, יפה ומדויק.": r(
        "The site feels like a real store — rich, beautiful, and precise.",
        "El sitio se siente como una tienda real: rico, bello y preciso.",
        "O site parece uma loja de verdade — rico, bonito e preciso.",
        "الموقع يشعر كمتجر حقيقي — غني وجميل ودقيق.",
    ),
    "הסינון והעמודים הפנימיים חוסכים זמן ומעלים אמון.": r(
        "Filtering and inner pages save time and build trust.",
        "El filtro y las páginas internas ahorran tiempo y generan confianza.",
        "O filtro e as páginas internas poupam tempo e geram confiança.",
        "التصفية والصفحات الداخلية تختصر الوقت وتعزّز الثقة.",
    ),
    "כל עמוד מרגיש מלא — לא רק דף בית יפה.": r(
        "Every page feels complete — not just a pretty home page.",
        "Cada página se siente completa, no solo una home bonita.",
        "Cada página parece completa — não só uma home bonita.",
        "كل صفحة تبدو مكتملة — وليست مجرد صفحة رئيسية جميلة.",
    ),
    "השראה, מדריכים ובחירות מערכת.": r(
        "Inspiration, guides, and editorial picks.",
        "Inspiración, guías y selecciones de la redacción.",
        "Inspiração, guias e escolhas da equipe.",
        "إلهام وأدلة واختيارات تحريرية.",
    ),
    "תוכן שמלווה את הקנייה ומחזק את המותג.": r(
        "Content that walks with the purchase and strengthens the brand.",
        "Contenido que acompaña la compra y refuerza la marca.",
        "Conteúdo que acompanha a compra e fortalece a marca.",
        "محتوى يرافق الشراء ويعزّز العلامة.",
    ),
    "איך לבחור נכון בפעם הראשונה": r("How to choose well the first time", "Cómo elegir bien a la primera", "Como escolher bem na primeira vez", "كيف تختارون صح من أول مرة"),
    "טיפים קצרים להתאמה מהירה לצרכים שלכם.": r(
        "Short tips for a fast match to your needs.",
        "Consejos cortos para adaptarlo rápido a lo que necesitas.",
        "Dicas curtas para adaptar rápido às suas necessidades.",
        "نصائح قصيرة لملاءمة سريعة لاحتياجاتكم.",
    ),
    "מאחורי הקלעים של הקולקציה": r("Behind the scenes of the collection", "Entre bastidores de la colección", "Bastidores da coleção", "خلف كواليس المجموعة"),
    "סיפור קצר על בחירת מוצרים וחומרים.": r(
        "A short story about choosing products and materials.",
        "Una historia breve sobre la elección de productos y materiales.",
        "Uma história curta sobre a escolha de produtos e materiais.",
        "قصة قصيرة عن اختيار المنتجات والمواد.",
    ),
    "שילובים שעובדים תמיד": r("Combinations that always work", "Combinaciones que siempre funcionan", "Combinações que sempre funcionam", "تركيبات تنجح دائماً"),
    "המלצות שמעלות את חוויית השימוש.": r(
        "Recommendations that raise the experience of using it.",
        "Recomendaciones que mejoran el uso.",
        "Recomendações que elevam a experiência de uso.",
        "توصيات ترفع تجربة الاستخدام.",
    ),
    "היו הראשונים לדעת על הגעות חדשות.": r(
        "Be the first to know about new arrivals.",
        "Sé el primero en saber de las novedades.",
        "Seja o primeiro a saber das novidades.",
        "كونوا أول من يعرف الوصولات الجديدة.",
    ),
    "היו ראשונים לדעת על הגעות חדשות.": r(
        "Be first to know about new arrivals.",
        "Sé el primero en enterarte de las novedades.",
        "Seja o primeiro a saber das novidades.",
        "كونوا أول من يعلم بالوصولات الجديدة.",
    ),
    "חיפוש, סינון לפי קטגוריה ומיון — המוצרים מתוסף החנות.": r(
        "Search, filter by category, and sort — products come from the store plugin.",
        "Busca, filtro por categoría y orden: los productos vienen del plugin de la tienda.",
        "Busca, filtro por categoria e ordenação — os produtos vêm do plugin da loja.",
        "بحث وتصفية حسب الفئة وفرز — المنتجات من إضافة المتجر.",
    ),
    "המוצרים בתצוגה הם דמו עד שתגדירו את הקטלוג האמיתי בניהול החנות.": r(
        "Products on display are demo until you set the real catalog in store management.",
        "Los productos en vitrina son demo hasta que definas el catálogo real.",
        "Os produtos em exibição são demo até você definir o catálogo real.",
        "المنتجات المعروضة تجريبية حتى تحدّدوا الكتالوج الحقيقي في إدارة المتجر.",
    ),
    "תיאור המוצר יופיע כאן מתוך תוסף החנות.": r(
        "The product description will appear here from the store plugin.",
        "La descripción del producto aparecerá aquí desde el plugin de la tienda.",
        "A descrição do produto aparecerá aqui a partir do plugin da loja.",
        "سيظهر وصف المنتج هنا من إضافة المتجر.",
    ),
    "פרטי מוצר ברורים: שימוש, התאמה ותועלת.": r(
        "Clear product details: use, fit, and benefit.",
        "Detalles claros: uso, encaje y beneficio.",
        "Detalhes claros: uso, adequação e benefício.",
        "تفاصيل منتج واضحة: الاستخدام والملاءمة والفائدة.",
    ),
    "מידע על משלוח, החזרה ושירות מופיע בכל עמוד רלוונטי.": r(
        "Shipping, returns, and service info appear on every relevant page.",
        "La info de envío, devolución y servicio aparece en cada página relevante.",
        "Informações de entrega, devolução e serviço aparecem em cada página relevante.",
        "معلومات الشحن والإرجاع والخدمة تظهر في كل صفحة ذات صلة.",
    ),
    "אפשר להתייעץ לפני רכישה דרך עמוד יצירת הקשר.": r(
        "You can ask before buying through the contact page.",
        "Puedes consultar antes de comprar en la página de contacto.",
        "Dá para consultar antes de comprar pela página de contato.",
        "يمكن الاستشارة قبل الشراء عبر صفحة التواصل.",
    ),
    "מאיפה מגיעים המוצרים?": r("Where do the products come from?", "¿De dónde vienen los productos?", "De onde vêm os produtos?", "من أين تأتي المنتجات؟"),
    "המוצרים נטענים מתוסף החנות ברגע שתגדירו אותם בניהול.": r(
        "Products load from the store plugin as soon as you set them in management.",
        "Los productos se cargan del plugin en cuanto los definas en la gestión.",
        "Os produtos carregam do plugin assim que você os definir na gestão.",
        "تُحمَّل المنتجات من إضافة المتجر فور تعريفها في الإدارة.",
    ),
    "כן — בעמוד החנות יש חיפוש, קטגוריות ומיון.": r(
        "Yes — the store page has search, categories, and sorting.",
        "Sí: la tienda tiene búsqueda, categorías y orden.",
        "Sim — a página da loja tem busca, categorias e ordenação.",
        "نعم — في صفحة المتجر بحث وفئات وفرز.",
    ),
    "כמה זמן לוקח משלוח?": r("How long does shipping take?", "¿Cuánto tarda el envío?", "Quanto tempo leva a entrega?", "كم يستغرق الشحن؟"),
    "בדרך כלל 1–3 ימי עסקים, לפי אזור ושירות שנבחר.": r(
        "Usually 1–3 business days, depending on area and the service you choose.",
        "Normalmente 1–3 días laborables, según zona y servicio.",
        "Geralmente 1–3 dias úteis, conforme a região e o serviço.",
        "عادة 1–3 أيام عمل حسب المنطقة والخدمة المختارة.",
    ),
    "איך יוצרים קשר?": r("How do I get in touch?", "¿Cómo contacto?", "Como falo com vocês?", "كيف أتواصل؟"),
    "דרך עמוד צור קשר, טלפון או אימייל שמופיעים באתר.": r(
        "Through the contact page, phone, or email shown on the site.",
        "Por la página de contacto, teléfono o email del sitio.",
        "Pela página de contato, telefone ou e-mail do site.",
        "عبر صفحة التواصل أو الهاتف أو البريد الظاهر في الموقع.",
    ),
    "אפשר להחזיר מוצר?": r("Can I return a product?", "¿Se puede devolver un producto?", "Posso devolver um produto?", "هل يمكن إرجاع منتج؟"),
    "כן, לפי מדיניות ההחזרות בעמוד המשלוחים.": r(
        "Yes, according to the returns policy on the shipping page.",
        "Sí, según la política de devoluciones de la página de envíos.",
        "Sim, conforme a política de devoluções na página de entregas.",
        "نعم، وفق سياسة الإرجاع في صفحة الشحن.",
    ),
    "שקיפות מלאה על זמנים, עלויות ומדיניות.": r(
        "Full transparency on timing, costs, and policy.",
        "Transparencia total en plazos, costes y política.",
        "Transparência total sobre prazos, custos e política.",
        "شفافية كاملة حول الأوقات والتكاليف والسياسة.",
    ),
    "שילוח לכל הארץ עם מעקב.": r("Nationwide shipping with tracking.", "Envío a todo el país con seguimiento.", "Envio para todo o país com rastreio.", "شحن لكل أنحاء البلاد مع تتبع."),
    "אריזה בטוחה": r("Secure packaging", "Embalaje seguro", "Embalagem segura", "تغليف آمن"),
    "אריזה שמותאמת לסוג המוצר.": r("Packaging matched to the product type.", "Embalaje adaptado al tipo de producto.", "Embalagem adequada ao tipo de produto.", "تغليف يناسب نوع المنتج."),
    "החזרות פשוטות": r("Simple returns", "Devoluciones sencillas", "Devoluções simples", "إرجاع بسيط"),
    "תהליך החזרה ברור תוך 14 יום.": r("A clear return process within 14 days.", "Un proceso de devolución claro en 14 días.", "Um processo de devolução claro em 14 dias.", "عملية إرجاع واضحة خلال 14 يوماً."),
    "אפשר לתאם איסוף לפי זמינות.": r("Pickup can be arranged by availability.", "Se puede coordinar recogida según disponibilidad.", "Dá para combinar retirada conforme a disponibilidade.", "يمكن تنسيق الاستلام حسب التوفر."),
    "עברו לחנות או כתבו לנו להכוונה אישית.": r(
        "Go to the store or write to us for personal guidance.",
        "Pasa a la tienda o escríbenos para una orientación personal.",
        "Vá à loja ou escreva para uma orientação pessoal.",
        "انتقلوا إلى المتجر أو اكتبوا لنا لتوجيه شخصي.",
    ),
    "המוצרים מתעדכנים אוטומטית מתוסף החנות.": r(
        "Products update automatically from the store plugin.",
        "Los productos se actualizan solos desde el plugin de la tienda.",
        "Os produtos atualizam automaticamente pelo plugin da loja.",
        "تتحدّث المنتجات تلقائياً من إضافة المتجر.",
    ),
    "ישראל": r("Israel", "Israel", "Israel", "إسرائيل"),
    "הכנה": r("Prep", "Preparación", "Preparo", "تحضير"),
    "ספרו כמה אתם ומתי — נשמור לכם מקום.": r(
        "Tell us how many you are and when — we will hold a table.",
        "Dinos cuántos sois y cuándo: os guardamos sitio.",
        "Digam quantos são e quando — reservamos um lugar.",
        "أخبرونا بعددكم والوقت — وسنحجز لكم مكاناً.",
    ),
    "תכנון": r("Planning", "Planificación", "Planejamento", "تخطيط"),
    "מדידה": r("Measurement", "Medición", "Medição", "قياس"),
    "מנות חתימה": r("Signature dishes", "Platos firma", "Pratos assinatura", "أطباق مميزة"),
    "קורסים": r("Courses", "Cursos", "Cursos", "دورات"),
    "ביצוע": r("Delivery", "Ejecución", "Execução", "تنفيذ"),
    "בואו נבנה את השלב הבא.": r("Let’s build the next step.", "Construyamos el siguiente paso.", "Vamos construir o próximo passo.", "لنبنِ الخطوة التالية."),
    "שיחת היכרות": r("Intro call", "Llamada de presentación", "Chamada de apresentação", "مكالمة تعارف"),
    "הפקה": r("Production", "Producción", "Produção", "إنتاج"),
    "תפריט": r("Menu", "Menú", "Cardápio", "قائمة"),
    "שביעות רצון": r("Satisfaction", "Satisfacción", "Satisfação", "رضا"),
    "אסטרטגיה": r("Strategy", "Estrategia", "Estratégia", "استراتيجية"),
    "נכסים": r("Properties", "Propiedades", "Imóveis", "عقارات"),
    "צפו בעבודות": r("View the work", "Ver trabajos", "Ver trabalhos", "شاهدوا الأعمال"),
    "אנחנו בונים מערכות עבודה שמחברות אסטרטגיה, קריאייטיב וביצוע. כל פרויקט מתחיל באבחון חד ומסתיים בנכסים שאפשר להפעיל מיד.": r(
        "We build working systems that connect strategy, creative, and delivery. Every project starts with a sharp assessment and ends with assets you can run immediately.",
        "Construimos sistemas que unen estrategia, creativo y ejecución. Cada proyecto empieza con un diagnóstico nítido y termina en activos listos para usar.",
        "Construímos sistemas que ligam estratégia, criativo e execução. Cada projeto começa com um diagnóstico nítido e termina em ativos prontos para usar.",
        "نبني أنظمة عمل تربط الاستراتيجية والإبداع والتنفيذ. كل مشروع يبدأ بتشخيص حاد وينتهي بأصول يمكن تشغيلها فوراً.",
    ),
    "מה אנחנו מפעילים עבורכם.": r("What we run for you.", "Lo que activamos para vosotros.", "O que operamos para vocês.", "ما نشغّله لكم."),
    "קייסים": r("Case studies", "Casos", "Cases", "حالات"),
    "עבודות שמראות את השיטה.": r("Work that shows the method.", "Trabajos que muestran el método.", "Trabalhos que mostram o método.", "أعمال تُظهر المنهج."),
    "אנשים שמחזיקים מקצוע וקצב.": r("People who hold both craft and pace.", "Personas que sostienen oficio y ritmo.", "Pessoas que sustentam ofício e ritmo.", "أشخاص يجمعون المهنة والإيقاع."),
    "פריימים מתוך תהליך העבודה.": r("Frames from the working process.", "Fotogramas del proceso.", "Frames do processo de trabalho.", "لقطات من عملية العمل."),
    "היתרונות שמורגשים בשטח.": r("Advantages you feel in the field.", "Ventajas que se notan en el terreno.", "Vantagens sentidas no campo.", "مزايا تُلمس في الميدان."),
    "מה משתנה אחרי העבודה.": r("What changes after the work.", "Qué cambia después del trabajo.", "O que muda depois do trabalho.", "ما الذي يتغيّر بعد العمل."),
    "מחשבות מהסטודיו.": r("Thoughts from the studio.", "Pensamientos del estudio.", "Pensamentos do estúdio.", "أفكار من الاستوديو."),
    "איך מתקדמים בלי לאבד חדות.": r("How to move forward without losing sharpness.", "Cómo avanzar sin perder nitidez.", "Como avançar sem perder nitidez.", "كيف تتقدمون دون فقدان الحدة."),
    "מגדירים קהל, יעד ומגבלות פעולה.": r("We define audience, goal, and operating constraints.", "Definimos audiencia, objetivo y límites de acción.", "Definimos público, meta e limites de ação.", "نحدّد الجمهور والهدف وحدود العمل."),
    "ארכיטקטורה": r("Architecture", "Arquitectura", "Arquitetura", "عمارة"),
    "בונים שיטה, נכסים ולוחות זמנים.": r("We build a method, assets, and timelines.", "Construimos método, activos y calendarios.", "Construímos método, ativos e cronogramas.", "نبني منهجاً وأصولاً وجداول زمنية."),
    "מוציאים לפועל בקצב מדוד ושקוף.": r("We execute at a measured, transparent pace.", "Ejecutamos a un ritmo medido y transparente.", "Executamos num ritmo medido e transparente.", "ننفّذ بإيقاع موزون وشفاف."),
    "כיול": r("Calibration", "Calibrado", "Calibragem", "معايرة"),
    "מודדים, משפרים ומרחיבים את מה שעובד.": r("We measure, improve, and expand what works.", "Medimos, mejoramos y ampliamos lo que funciona.", "Medimos, melhoramos e ampliamos o que funciona.", "نقيس ونحسّن ونوسّع ما ينجح."),
    "אפשר להתחיל ממוקד או לבנות מערכת.": r("You can start focused or build a full system.", "Puedes empezar puntual o construir un sistema.", "Dá para começar pontual ou construir um sistema.", "يمكن البدء بتركيز أو بناء نظام."),
    "לפני שמתחילים.": r("Before you start.", "Antes de empezar.", "Antes de começar.", "قبل أن تبدأوا."),
    "כמה מהר אפשר לצאת לדרך?": r("How quickly can we get started?", "¿Qué tan rápido se puede empezar?", "Quão rápido dá para começar?", "كم بسرعة يمكن الانطلاق؟"),
    "ברוב המקרים מתחילים באבחון תוך שבוע ומציגים תוכנית פעולה ראשונה עד שבועיים.": r(
        "In most cases we start with an assessment within a week and present a first action plan within two.",
        "En la mayoría de casos empezamos el diagnóstico en una semana y presentamos un primer plan en dos.",
        "Na maioria dos casos começamos o diagnóstico em uma semana e apresentamos um primeiro plano em duas.",
        "في معظم الحالات نبدأ بالتشخيص خلال أسبوع ونعرض خطة عمل أولى خلال أسبوعين.",
    ),
    "האם אפשר לערוך את כל התוכן באתר?": r("Can all the site content be edited?", "¿Se puede editar todo el contenido del sitio?", "Dá para editar todo o conteúdo do site?", "هل يمكن تحرير كل محتوى الموقع؟"),
    "כן. כל הכותרות, התמונות, השירותים, הצוות והפרטים בנויים כשדות עריכה.": r(
        "Yes. Headlines, images, services, team, and details are all built as editable fields.",
        "Sí. Títulos, fotos, servicios, equipo y datos son campos editables.",
        "Sim. Títulos, fotos, serviços, equipe e dados são campos editáveis.",
        "نعم. كل العناوين والصور والخدمات والفريق والتفاصيل مبنية كحقول قابلة للتحرير.",
    ),
    "האם אתם עובדים עם צוות פנימי?": r("Do you work with an in-house team?", "¿Trabajáis con un equipo interno?", "Vocês trabalham com equipe interna?", "هل تعملون مع فريق داخلي؟"),
    "כן. אנחנו משתלבים עם שיווק, מוצר, מכירות או הנהלה לפי אופי הפרויקט.": r(
        "Yes. We plug into marketing, product, sales, or leadership depending on the project.",
        "Sí. Nos integramos con marketing, producto, ventas o dirección según el proyecto.",
        "Sim. Entramos com marketing, produto, vendas ou direção conforme o projeto.",
        "نعم. نندمج مع التسويق أو المنتج أو المبيعات أو الإدارة حسب طبيعة المشروع.",
    ),
    "בואו נבנה את המהלך הבא.": r("Let’s build the next move.", "Construyamos el siguiente movimiento.", "Vamos construir o próximo movimento.", "لنبنِ الخطوة التالية."),
    "רוצים לראות איך זה יכול לעבוד אצלכם?": r("Want to see how this could work for you?", "¿Quieres ver cómo puede funcionar en tu caso?", "Quer ver como isso pode funcionar com vocês?", "تريدون رؤية كيف يمكن أن يعمل لديكم؟"),
    "שיחה קצרה תספיק כדי להבין אם יש התאמה ומה הצעד הראשון.": r(
        "A short call is enough to see if there is a fit and what the first step is.",
        "Una llamada breve basta para ver si hay encaje y cuál es el primer paso.",
        "Uma chamada curta basta para ver se há encaixe e qual é o primeiro passo.",
        "مكالمة قصيرة تكفي لفهم إن كان هناك توافق وما هي الخطوة الأولى.",
    ),
    "אתר מלא לסוכנות עם 8 עמודים, תנועה ותוכן עריך.": r(
        "A full agency site with 8 pages, motion, and editable content.",
        "Un sitio de agencia completo con 8 páginas, movimiento y contenido editable.",
        "Um site de agência completo com 8 páginas, movimento e conteúdo editável.",
        "موقع وكالة كامل بـ 8 صفحات وحركة ومحتوى قابل للتحرير.",
    ),
    "שליחה": r("Send", "Enviar", "Enviar", "إرسال"),
    "קלאסיקה": r("Classics", "Clásicos", "Clássicos", "كلاسيكيات"),
    "שוק": r("Market", "Mercado", "Mercado", "سوق"),
    "מדריך": r("Guide", "Guía", "Guia", "دليل"),
    "מה אומרים האורחים": r("What guests say", "Lo que dicen los huéspedes", "O que os hóspedes dizem", "ماذا يقول الضيوف"),
    "הסיפור המלא": r("The full story", "La historia completa", "A história completa", "القصة الكاملة"),
    "איך הגענו לכאן": r("How we got here", "Cómo llegamos aquí", "Como chegamos aqui", "كيف وصلنا إلى هنا"),
    "אורח קבוע": r("Regular guest", "Huésped habitual", "Hóspede frequente", "ضيف دائم"),
    "דיוק": r("Precision", "Precisión", "Precisão", "دقة"),
    "הליווי היה מדויק, שקוף ומהיר — מצאנו נכס מעולה תוך שבועיים.": r(
        "The guidance was precise, transparent, and fast — we found an excellent property in two weeks.",
        "El acompañamiento fue preciso, transparente y rápido: encontramos un gran inmueble en dos semanas.",
        "O acompanhamento foi preciso, transparente e rápido — achamos um ótimo imóvel em duas semanas.",
        "كان المرافقة دقيقة وشفافة وسريعة — وجدنا عقاراً ممتازاً خلال أسبوعين.",
    ),
    "צוות מקצועי שמבין גם את השוק וגם את האנשים מאחורי העסקה.": r(
        "A professional team that understands both the market and the people behind the deal.",
        "Un equipo profesional que entiende el mercado y a las personas detrás de la operación.",
        "Uma equipe profissional que entende o mercado e as pessoas por trás do negócio.",
        "فريق محترف يفهم السوق والناس خلف الصفقة.",
    ),
    "מוכנים לצעד הבא?": r("Ready for the next step?", "¿Listos para el siguiente paso?", "Prontos para o próximo passo?", "مستعدون للخطوة التالية؟"),
    "השאירו פרטים ונחזור עם התאמות מדויקות לדרישות שלכם — בלי רעש, בלי לחץ.": r(
        "Leave your details and we will come back with precise matches for your brief — no noise, no pressure.",
        "Deja tus datos y volveremos con encajes precisos, sin ruido ni presión.",
        "Deixe seus dados e voltaremos com encaixes precisos — sem ruído, sem pressão.",
        "اتركوا بياناتكم وسنعود بملاءمات دقيقة لمتطلباتكم — بلا ضجيج وبلا ضغط.",
    ),
    "בואו לפגוש אותנו": r("Come meet us", "Ven a conocernos", "Venha nos encontrar", "تعالوا للقائنا"),
    "המשרד שלנו פתוח לפגישות, סיורים וייעוץ — בתיאום מראש ובאווירה נעימה.": r(
        "Our office is open for meetings, tours, and advice — by appointment, in a calm atmosphere.",
        "Nuestra oficina está abierta para reuniones, visitas y consejo, con cita y en un ambiente agradable.",
        "Nosso escritório está aberto para reuniões, tours e consultoria — com horário e em clima agradável.",
        "مكتبنا مفتوح للاجتماعات والجولات والاستشارة — بتنسيق مسبق وأجواء لطيفة.",
    ),
    "מיפוי דרישות": r("Requirements mapping", "Mapeo de requisitos", "Mapeamento de requisitos", "رسم المتطلبات"),
    "מבינים תקציב, אזור, סגנון חיים ומטרות השקעה.": r(
        "We understand budget, area, lifestyle, and investment goals.",
        "Entendemos presupuesto, zona, estilo de vida y objetivos de inversión.",
        "Entendemos orçamento, região, estilo de vida e metas de investimento.",
        "نفهم الميزانية والمنطقة ونمط الحياة وأهداف الاستثمار.",
    ),
    "סינון חכם": r("Smart filtering", "Filtro inteligente", "Filtro inteligente", "تصفية ذكية"),
    "מציגים רק נכסים שעוברים את הסינון שלנו — איכות לפני כמות.": r(
        "We only show properties that pass our filter — quality before quantity.",
        "Mostramos solo inmuebles que pasan nuestro filtro: calidad antes que cantidad.",
        "Mostramos só imóveis que passam no nosso filtro — qualidade antes de quantidade.",
        "نعرض فقط العقارات التي تتجاوز تصفيتنا — الجودة قبل الكمية.",
    ),
    "סיורים ממוקדים": r("Focused tours", "Visitas enfocadas", "Tours focados", "جولات مركّزة"),
    "יוצאים לשטח עם ליווי מלא, תמונות ונתונים בזמן אמת.": r(
        "We go on site with full guidance, photos, and live data.",
        "Salimos al terreno con acompañamiento, fotos y datos en tiempo real.",
        "Vamos a campo com acompanhamento, fotos e dados em tempo real.",
        "نخرج إلى الميدان بمرافقة كاملة وصور وبيانات لحظية.",
    ),
    "סגירה מקצועית": r("Professional closing", "Cierre profesional", "Fechamento profissional", "إغلاق احترافي"),
    "מלווים במו״מ, בדיקות, משכנתא וחתימה — עד המפתח.": r(
        "We stay with you through negotiation, checks, mortgage, and signing — until the keys.",
        "Acompañamos negociación, revisiones, hipoteca y firma, hasta las llaves.",
        "Acompanhamos negociação, vistorias, financiamento e assinatura — até a chave.",
        "نرافق التفاوض والفحوصات والرهن والتوقيع — حتى المفتاح.",
    ),
    "איך מתחילים לעבוד יחד?": r("How do we start working together?", "¿Cómo empezamos a trabajar juntos?", "Como começamos a trabalhar juntos?", "كيف نبدأ العمل معاً؟"),
    "משאירים פרטים בטופס — נחזור תוך 24 שעות עם 3 התאמות ראשוניות.": r(
        "Leave details in the form — we reply within 24 hours with 3 first matches.",
        "Deja datos en el formulario: respondemos en 24 horas con 3 primeras opciones.",
        "Deixe dados no formulário — respondemos em 24 horas com 3 primeiras opções.",
        "اتركوا البيانات في النموذج — نعود خلال 24 ساعة بـ 3 ملاءمات أولى.",
    ),
    "מה העמלה?": r("What is the commission?", "¿Cuál es la comisión?", "Qual é a comissão?", "ما العمولة؟"),
    "שקופה ומוסכמת מראש — בלי הפתעות ובלי אותיות קטנות.": r(
        "Transparent and agreed in advance — no surprises and no fine print.",
        "Transparente y acordada de antemano, sin sorpresas ni letra pequeña.",
        "Transparente e combinada antes — sem surpresas e sem letras miúdas.",
        "شفافة ومتفق عليها مسبقاً — بلا مفاجآت وبلا حروف صغيرة.",
    ),
    "כמה זמן לוקחת עסקה?": r("How long does a deal take?", "¿Cuánto tarda una operación?", "Quanto tempo leva um negócio?", "كم تستغرق الصفقة؟"),
    "בממוצע 30–45 יום מרגע מציאת הנכס, תלוי במורכבות.": r(
        "On average 30–45 days from finding the property, depending on complexity.",
        "De media 30–45 días desde encontrar el inmueble, según la complejidad.",
        "Em média 30–45 dias a partir de achar o imóvel, conforme a complexidade.",
        "في المتوسط 30–45 يوماً من إيجاد العقار، حسب التعقيد.",
    ),
    "האם אתם עובדים עם משקיעים?": r("Do you work with investors?", "¿Trabajáis con inversores?", "Vocês trabalham com investidores?", "هل تعملون مع مستثمرين؟"),
    "כן — יש ליווי מלא לתשואה, שיפוץ, השכרה וניהול נכס.": r(
        "Yes — full guidance for yield, renovation, rental, and property management.",
        "Sí: acompañamiento completo para rentabilidad, reforma, alquiler y gestión.",
        "Sim — acompanhamento completo para rendimento, reforma, aluguel e gestão.",
        "نعم — مرافقة كاملة للعائد والتجديد والتأجير وإدارة العقار.",
    ),
    "מגמות מחירים ברבעון": r("Quarterly price trends", "Tendencias de precios del trimestre", "Tendências de preço do trimestre", "اتجاهات الأسعار في الربع"),
    "ניתוח עדכני של עליות, ירידות ונקודות כניסה מומלצות לשוק.": r(
        "An up-to-date read of rises, dips, and recommended entry points.",
        "Un análisis actual de subidas, bajadas y puntos de entrada.",
        "Uma leitura atual de altas, quedas e pontos de entrada.",
        "تحليل محدّث للصعود والهبوط ونقاط الدخول الموصى بها.",
    ),
    "שכונות עולות": r("Rising neighborhoods", "Barrios al alza", "Bairros em alta", "أحياء صاعدة"),
    "אילו אזורים מציגים ביקוש גבוה, תשתיות חדשות ופוטנציאל עליית ערך.": r(
        "Which areas show strong demand, new infrastructure, and room for value to rise.",
        "Qué zonas muestran alta demanda, nueva infraestructura y potencial de revalorización.",
        "Quais áreas mostram alta demanda, nova infraestrutura e potencial de valorização.",
        "أي مناطق تظهر طلباً عالياً وبنية تحتية جديدة وإمكانية ارتفاع القيمة.",
    ),
    "טיפים לקונים ראשונים": r("Tips for first-time buyers", "Consejos para compradores primerizos", "Dicas para primeiros compradores", "نصائح للمشترين لأول مرة"),
    "מה לבדוק לפני חתימה — משכנתא, בדק, חלוקה ותכנון עתידי.": r(
        "What to check before signing — mortgage, inspection, layout, and future plans.",
        "Qué revisar antes de firmar: hipoteca, inspección, distribución y plan futuro.",
        "O que checar antes de assinar — financiamento, vistoria, divisão e plano futuro.",
        "ما الذي تفحصونه قبل التوقيع — الرهن والفحص والتقسيم والتخطيط المستقبلي.",
    ),
    "סוכנות מובילה 2025": r("Leading agency 2025", "Agencia líder 2025", "Agência líder 2025", "وكالة رائدة 2025"),
    "שקיפות מלאה": r("Full transparency", "Transparencia total", "Transparência total", "شفافية كاملة"),
    "ליווי VIP": r("VIP guidance", "Acompañamiento VIP", "Acompanhamento VIP", "مرافقة VIP"),
    "98% שביעות רצון": r("98% satisfaction", "98% de satisfacción", "98% de satisfação", "رضا 98%"),
    "מכירות פרימיום": r("Premium sales", "Ventas premium", "Vendas premium", "مبيعات فاخرة"),
    "127 עסקאות": r("127 deals", "127 operaciones", "127 negócios", "127 صفقة"),
    "השקעות וייעוץ": r("Investments and advice", "Inversiones y asesoría", "Investimentos e consultoria", "استثمارات واستشارة"),
    "89 עסקאות": r("89 deals", "89 operaciones", "89 negócios", "89 صفقة"),
    "64 עסקאות": r("64 deals", "64 operaciones", "64 negócios", "64 صفقة"),
    "השכרה וניהול": r("Rentals and management", "Alquiler y gestión", "Aluguel e gestão", "تأجير وإدارة"),
    "112 עסקאות": r("112 deals", "112 operaciones", "112 negócios", "112 صفقة"),
    "זיווגים מומלצים": r("Recommended pairings", "Maridajes recomendados", "Harmonizações recomendadas", "توافيق موصى بها"),
    "חומרי הגלם": r("Ingredients", "Materias primas", "Matérias-primas", "المواد الخام"),
    "טעם עמוק": r("Deep flavor", "Sabor profundo", "Sabor profundo", "طعم عميق"),
    "אפשר להזמין מראש?": r("Can I book ahead?", "¿Se puede reservar con antelación?", "Posso reservar com antecedência?", "هل يمكن الحجز مسبقاً؟"),
    "צדדים": r("Sides", "Acompañamientos", "Acompanhamentos", "أطباق جانبية"),
    "בחירת השף": r("Chef's choice", "Elección del chef", "Escolha do chef", "اختيار الشيف"),
    "תהליך העבודה": r("The working process", "El proceso de trabajo", "O processo de trabalho", "عملية العمل"),
    "מקומות מוגבלים": r("Limited seats", "Plazas limitadas", "Lugares limitados", "أماكن محدودة"),
    "השף / המארח": r("The chef / host", "El chef / anfitrión", "O chef / anfitrião", "الشيف / المضيف"),
    "אירוח": r("Hospitality", "Hospitalidad", "Hospitalidade", "ضيافة"),
    "ליווי": r("Guidance", "Acompañamiento", "Acompanhamento", "مرافقة"),
    "לתיק עבודות": r("To the portfolio", "Al portafolio", "Para o portfólio", "إلى معرض الأعمال"),
    "יישום": r("Implementation", "Implementación", "Implementação", "تطبيق"),
    "ביקור": r("Visit", "Visita", "Visita", "زيارة"),
    "שישי": r("Friday", "Viernes", "Sexta", "الجمعة"),
    "לקולקציה": r("To the collection", "A la colección", "Para a coleção", "إلى المجموعة"),
    "החתימות שלנו": r("Our signatures", "Nuestras firmas", "Nossas assinaturas", "توقيعاتنا"),
    "מהמטבח עד אליכם": r("From the kitchen to you", "De la cocina a vuestra mesa", "Da cozinha até vocês", "من المطبخ إليكم"),
    "בחירה": r("Choice", "Elección", "Escolha", "اختيار"),
    "חומרי גלם טריים בלבד.": r("Fresh ingredients only.", "Solo materia prima fresca.", "Só matéria-prima fresca.", "مواد خام طازجة فقط."),
    "טכניקה מדויקת בלי קיצורי דרך.": r("Precise technique with no shortcuts.", "Técnica precisa, sin atajos.", "Técnica precisa, sem atalhos.", "تقنية دقيقة بلا اختصارات."),
    "חמים, יפים, בזמן.": r("Hot, beautiful, on time.", "Calientes, hermosos, a tiempo.", "Quentes, bonitos, no tempo.", "ساخنة وجميلة وفي الوقت."),
    "רגעים מהמטבח": r("Moments from the kitchen", "Momentos de la cocina", "Momentos da cozinha", "لحظات من المطبخ"),
    "בלוגרית": r("Blogger", "Blogger", "Blogueira", "مدوّنة"),
    "שירות חם, מנות מדויקות, אווירה מדויקת.": r("Warm service, precise dishes, the right atmosphere.", "Servicio cálido, platos precisos, ambiente justo.", "Serviço caloroso, pratos precisos, atmosfera certa.", "خدمة دافئة وأطباق دقيقة وأجواء مناسبة."),
    "חוגג": r("Celebrating", "De celebración", "Comemorando", "محتفل"),
    "א׳–ה׳ 11:00–22:00 · ו׳ 10:00–15:00 · שבת 18:00–22:00": r(
        "Sun–Thu 11:00–22:00 · Fri 10:00–15:00 · Sat 18:00–22:00",
        "Dom–jue 11:00–22:00 · vie 10:00–15:00 · sáb 18:00–22:00",
        "Dom–qui 11:00–22:00 · sex 10:00–15:00 · sáb 18:00–22:00",
        "الأحد–الخميس 11:00–22:00 · الجمعة 10:00–15:00 · السبت 18:00–22:00",
    ),
    "מוכנים להזמין?": r("Ready to order?", "¿Listos para pedir?", "Prontos para pedir?", "مستعدون للطلب؟"),
    "כל המנות": r("All dishes", "Todos los platos", "Todos os pratos", "كل الأطباق"),
    "חתימה": r("Signature", "Firma", "Assinatura", "توقيع"),
    "המנות המובילות": r("Leading dishes", "Platos destacados", "Pratos em destaque", "الأطباق الرائدة"),
    "טעמים שחוזרים": r("Flavors that return", "Sabores que vuelven", "Sabores que voltam", "نكهات تعود"),
    "עונתי": r("Seasonal", "De temporada", "Sazonal", "موسمي"),
    "לפי השוק": r("According to the market", "Según el mercado", "Conforme o mercado", "حسب السوق"),
    "השלמות מושלמות": r("Perfect pairings", "Complementos perfectos", "Complementos perfeitos", "تكميلات مثالية"),
    "מנה + שתייה": r("Dish + drink", "Plato + bebida", "Prato + bebida", "طبق + مشروب"),
    "איזון מושלם": r("Perfect balance", "Equilibrio perfecto", "Equilíbrio perfeito", "توازن مثالي"),
    "חריף + רענון": r("Spicy + fresh", "Picante + fresco", "Picante + fresco", "حار + منعش"),
    "חום מול קרירות": r("Heat versus cool", "Calor frente a frescor", "Calor versus frescor", "حرارة مقابل برودة"),
    "מתוק + מלוח": r("Sweet + salty", "Dulce + salado", "Doce + salgado", "حلو + مالح"),
    "ניגוד שעובד": r("A contrast that works", "Un contraste que funciona", "Um contraste que funciona", "تباين ينجح"),
    "מיז-אן-פלאס מסודר.": r("A tidy mise en place.", "Mise en place ordenada.", "Mise en place organizada.", "تحضير منظّم قبل الخدمة."),
    "בישול": r("Cooking", "Cocción", "Cocção", "طبخ"),
    "חום נכון בזמן הנכון.": r("The right heat at the right time.", "El calor justo en el momento justo.", "O calor certo na hora certa.", "الحرارة الصحيحة في الوقت الصحيح."),
    "טעימה": r("Tasting", "Cata", "Degustação", "تذوّق"),
    "כוונון אחרון.": r("A last adjustment.", "El último ajuste.", "O último ajuste.", "ضبط أخير."),
    "צלחת נקייה ומדויקת.": r("A clean, precise plate.", "Un plato limpio y preciso.", "Um prato limpo e preciso.", "طبق نظيف ودقيق."),
    "חומר ראשי": r("Main ingredient", "Ingrediente principal", "Ingrediente principal", "المادة الرئيسية"),
    "מקור איכותי": r("A quality source", "Un origen de calidad", "Uma origem de qualidade", "مصدر جودة"),
    "תבלין בית": r("House spice", "Especia de la casa", "Tempero da casa", "بهار البيت"),
    "תערובת שלנו": r("Our blend", "Nuestra mezcla", "Nossa mistura", "خليطنا"),
    "שמן/חמאה": r("Oil/butter", "Aceite/mantequilla", "Óleo/manteiga", "زيت/زبدة"),
    "אירועים מיוחדים": r("Special events", "Eventos especiales", "Eventos especiais", "مناسبات خاصة"),
    "ערבי שיתוף ותפריטים עונתיים.": r("Shared evenings and seasonal menus.", "Noches compartidas y menús de temporada.", "Noites compartilhadas e cardápios sazonais.", "أمسيات مشتركة وقوائم موسمية."),
    "הניסויים הראשונים.": r("The first experiments.", "Los primeros ensayos.", "Os primeiros ensaios.", "التجارب الأولى."),
    "תפריט חתימה מחודש.": r("A renewed signature menu.", "Un menú firma renovado.", "Um cardápio assinatura renovado.", "قائمة توقيع متجددة."),
    "טריות": r("Freshness", "Frescura", "Frescor", "طزاجة"),
    "כל יום מחדש.": r("Every day, anew.", "Cada día de nuevo.", "Todo dia de novo.", "كل يوم من جديد."),
    "בלי פשרות.": r("No compromises.", "Sin compromisos.", "Sem concessões.", "بلا تنازلات."),
    "אורחים במרכז.": r("Guests at the center.", "Los huéspedes en el centro.", "Os hóspedes no centro.", "الضيوف في المركز."),
    "מתי נתראה?": r("When shall we meet?", "¿Cuándo nos vemos?", "Quando nos vemos?", "متى نلتقي؟"),
    "יש אפשרויות טבעוניות?": r("Are there vegan options?", "¿Hay opciones veganas?", "Há opções veganas?", "هل هناك خيارات نباتية؟"),
    "כן — בדקו בתפריט המסומן.": r("Yes — check the marked menu.", "Sí: consulta el menú marcado.", "Sim — veja o cardápio marcado.", "نعم — راجعوا القائمة المعلّمة."),
    "בהחלט דרך טופס ההזמנה.": r("Absolutely, through the reservation form.", "Por supuesto, con el formulario de reserva.", "Com certeza, pelo formulário de reserva.", "بالتأكيد عبر نموذج الحجز."),
    "חניון קרוב במרחק הליכה קצרה.": r("Nearby parking a short walk away.", "Parking cercano a pocos minutos a pie.", "Estacionamento perto, a uma caminhada curta.", "موقف قريب على مسافة مشي قصيرة."),
    "₪28 · קלאסי": r("₪28 · Classic", "₪28 · Clásico", "₪28 · Clássico", "₪28 · كلاسيكي"),
    "₪32 · מומלץ": r("₪32 · Recommended", "₪32 · Recomendado", "₪32 · Recomendado", "₪32 · موصى به"),
    "₪36 · שף": r("₪36 · Chef", "₪36 · Chef", "₪36 · Chef", "₪36 · شيف"),
    "₪40 · עונתי": r("₪40 · Seasonal", "₪40 · De temporada", "₪40 · Sazonal", "₪40 · موسمي"),
    "₪24 · ביתי": r("₪24 · Homestyle", "₪24 · Casero", "₪24 · Caseiro", "₪24 · بيتي"),
    "₪30 · מיוחד": r("₪30 · Special", "₪30 · Especial", "₪30 · Especial", "₪30 · خاص"),
    "דירוג ממוצע": r("Average rating", "Valoración media", "Avaliação média", "تقييم متوسط"),
    "השיטה": r("The method", "El método", "O método", "المنهج"),
    "זמינות": r("Availability", "Disponibilidad", "Disponibilidade", "التوفر"),
    "לתיאום שיחה": r("To book a call", "Para coordinar una llamada", "Para agendar uma chamada", "لتنسيق مكالمة"),
    "מחירון": r("Price list", "Lista de precios", "Lista de preços", "قائمة أسعار"),
    "הזמינו שולחן": r("Reserve a table", "Reservar mesa", "Reservar mesa", "احجزوا طاولة"),
    "אירועים": r("Events", "Eventos", "Eventos", "فعاليات"),
    "ידע, ניתוח ותובנות": r("Knowledge, analysis, and insight", "Conocimiento, análisis e ideas", "Conhecimento, análise e insights", "معرفة وتحليل ورؤى"),
    "מגמות 2026": r("2026 trends", "Tendencias 2026", "Tendências 2026", "اتجاهات 2026"),
    "מה משתנה בשוק ואיך להתכונן מראש.": r("What is changing in the market and how to prepare.", "Qué cambia en el mercado y cómo prepararse.", "O que muda no mercado e como se preparar.", "ما الذي يتغيّر في السوق وكيف تستعدون."),
    "מסגרת עבודה": r("Working framework", "Marco de trabajo", "Quadro de trabalho", "إطار عمل"),
    "תהליך בן 4 שלבים שמייצר תוצאות עקביות.": r("A 4-step process that produces consistent results.", "Un proceso de 4 pasos que genera resultados constantes.", "Um processo de 4 etapas que gera resultados consistentes.", "عملية من 4 خطوات تنتج نتائج ثابتة."),
    "טיפוח": r("Care", "Cuidado", "Cuidado", "عناية"),
    "דקור": r("Decor", "Decoración", "Decoração", "ديكور"),
    "מאמרים": r("Articles", "Artículos", "Artigos", "مقالات"),
    "גלו נכסים": r("Discover properties", "Descubrir inmuebles", "Descobrir imóveis", "اكتشفوا العقارات"),
    "ביגוד": r("Apparel", "Ropa", "Roupas", "ملابس"),
    "צעצועים": r("Toys", "Juguetes", "Brinquedos", "ألعاب"),
    "טיולים": r("Trips", "Viajes", "Passeios", "رحلات"),
    "שכבות": r("Layers", "Capas", "Camadas", "طبقات"),
    "/לחודש": r("/month", "/mes", "/mês", "/شهر"),
    "טבעות": r("Rings", "Anillos", "Anéis", "خواتم"),
    "שרשראות": r("Necklaces", "Collares", "Colares", "قلائد"),
    "עגילים": r("Earrings", "Pendientes", "Brincos", "أقراط"),
    "מארזים": r("Sets", "Estuches", "Kits", "علب"),
    "ספורט": r("Sport", "Deporte", "Esporte", "رياضة"),
    "איך זה עובד": r("How it works", "Cómo funciona", "Como funciona", "كيف يعمل"),
    "מחירים": r("Prices", "Precios", "Preços", "أسعار"),
    "לפני": r("Before", "Antes", "Antes", "قبل"),
    "אחרי": r("After", "Después", "Depois", "بعد"),
    "לתפריט": r("To the menu", "Al menú", "Para o cardápio", "إلى القائمة"),
    "לטיפולים": r("To treatments", "A los tratamientos", "Para os tratamentos", "إلى العلاجات"),
    "שיער": r("Hair", "Cabello", "Cabelo", "شعر"),
    "תאורה": r("Lighting", "Iluminación", "Iluminação", "إضاءة"),
    "שעונים": r("Watches", "Relojes", "Relógios", "ساعات"),
    "תחומי התמחות": r("Practice areas", "Áreas de especialidad", "Áreas de atuação", "مجالات التخصص"),
    "סניקרס": r("Sneakers", "Zapatillas", "Tênis", "سنيكرز"),
    "לקוחות מספרים": r("Clients tell", "Los clientes cuentan", "Clientes contam", "العملاء يروون"),
    "מגדלים": r("Towers", "Torres", "Torres", "أبراج"),
    "שליחת פרטים": r("Send details", "Enviar datos", "Enviar dados", "إرسال البيانات"),
    "בלוג": r("Blog", "Blog", "Blog", "مدونة"),
    "מיתוג": r("Branding", "Branding", "Branding", "هوية"),
    "עיצוב אתר": r("Website design", "Diseño web", "Design de site", "تصميم موقع"),
    "פיתוח צד לקוח": r("Front-end development", "Desarrollo front-end", "Desenvolvimento front-end", "تطوير الواجهة"),
    "פיתוח אפליקציה": r("App development", "Desarrollo de apps", "Desenvolvimento de app", "تطوير تطبيق"),
    "שליחת הודעה": r("Send a message", "Enviar mensaje", "Enviar mensagem", "إرسال رسالة"),
    "הזמנת שולחן": r("Table reservation", "Reserva de mesa", "Reserva de mesa", "حجز طاولة"),
    "אפייה": r("Baking", "Repostería", "Confeitaria", "خبز"),
    "תיאום סיור": r("Book a tour", "Coordinar visita", "Agendar tour", "تنسيق جولة"),
    "הגשת מועמדות": r("Apply", "Enviar candidatura", "Enviar candidatura", "تقديم طلب"),
    "תמחור": r("Pricing", "Precios", "Preços", "تسعير"),
    "חשמל": r("Electrical", "Electricidad", "Elétrica", "كهرباء"),
    "לגלריה": r("To the gallery", "A la galería", "Para a galeria", "إلى المعرض"),
    "יצירה": r("Craft", "Creación", "Criação", "إبداع"),
    "סטים": r("Sets", "Sets", "Sets", "أطقم"),
    "שירות": r("Service", "Servicio", "Serviço", "خدمة"),
    "מנות": r("Dishes", "Platos", "Pratos", "أطباق"),
    "נעליים": r("Shoes", "Zapatos", "Sapatos", "أحذية"),
    "ליווי אישי": r("Personal guidance", "Acompañamiento personal", "Acompanhamento pessoal", "مرافقة شخصية"),
    "האווירה": r("The atmosphere", "El ambiente", "A atmosfera", "الأجواء"),
    "להתחיל עכשיו": r("Start now", "Empezar ahora", "Começar agora", "ابدأوا الآن"),
    "פיתוח": r("Development", "Desarrollo", "Desenvolvimento", "تطوير"),
    "מנכ״ל": r("CEO", "CEO", "CEO", "الرئيس التنفيذي"),
    "זרימה": r("Flow", "Flujo", "Fluxo", "تدفق"),
    "סטודיו": r("Studio", "Estudio", "Estúdio", "استوديو"),
    "מותגים": r("Brands", "Marcas", "Marcas", "علامات"),
    "ביצועים": r("Performance", "Rendimiento", "Desempenho", "أداء"),
    "להתחיל פרויקט": r("Start a project", "Empezar un proyecto", "Começar um projeto", "بدء مشروع"),
    "ארגונים": r("Organizations", "Organizaciones", "Organizações", "مؤسسات"),
    "תיאום פגישה": r("Book a meeting", "Coordinar reunión", "Agendar reunião", "تنسيق اجتماع"),
    "אוזניות": r("Headphones", "Auriculares", "Fones", "سماعات"),
    "רמקולים": r("Speakers", "Altavoces", "Caixas de som", "مكبرات"),
    "סאונדבר": r("Soundbar", "Barra de sonido", "Soundbar", "شريط صوت"),
    "החוויה": r("The experience", "La experiencia", "A experiência", "التجربة"),
    "נכסים פעילים": r("Active listings", "Inmuebles activos", "Imóveis ativos", "عقارات نشطة"),
    "חדר": r("Room", "Habitación", "Quarto", "غرفة"),
    "תיקי צד": r("Shoulder bags", "Bolsos de hombro", "Bolsas de ombro", "حقائب كتف"),
    "תיקי גב": r("Backpacks", "Mochilas", "Mochilas", "حقائب ظهر"),
    "נסיעות": r("Travel", "Viajes", "Viagens", "سفر"),
    "ארנקים": r("Wallets", "Carteras", "Carteiras", "محافظ"),
    "פרקים": r("Episodes", "Episodios", "Episódios", "حلقات"),
    "ספרות": r("Literature", "Literatura", "Literatura", "أدب"),
    "ילדים": r("Kids", "Niños", "Crianças", "أطفال"),
    "מחברות": r("Notebooks", "Cuadernos", "Cadernos", "دفاتر"),
    "כתיבה": r("Writing", "Escritura", "Escrita", "كتابة"),
    "פולי קפה": r("Coffee beans", "Granos de café", "Grãos de café", "حبوب قهوة"),
    "ציוד בריסטה": r("Barista gear", "Equipo de barista", "Equipamento de barista", "معدات باريستا"),
    "כוסות": r("Cups", "Tazas", "Xícaras", "أكواب"),
    "מארזי מתנה": r("Gift sets", "Estuches de regalo", "Kits de presente", "علب هدايا"),
    "לנכסים": r("To listings", "A los inmuebles", "Para os imóveis", "إلى العقارات"),
    "עיצוב גבות": r("Brow design", "Diseño de cejas", "Design de sobrancelhas", "تصميم حواجب"),
    "לחמנייה, בשר, גבינה — בלי פילוסופיה.": r("Bun, meat, cheese — no philosophy.", "Pan, carne, queso: sin filosofía.", "Pão, carne, queijo — sem filosofia.", "خبزة ولحم وجبن — بلا فلسفة."),
    "פרימיום": r("Premium", "Premium", "Premium", "فاخر"),
    "אבחון אקנה": r("Acne assessment", "Diagnóstico de acné", "Diagnóstico de acne", "تشخيص حب الشباب"),
    "חולצות": r("Shirts", "Camisas", "Camisas", "قمصان"),
    "שמלות": r("Dresses", "Vestidos", "Vestidos", "فساتين"),
    "מכנסיים": r("Pants", "Pantalones", "Calças", "بناطيل"),
    "להרשמה לסדנה": r("Workshop signup", "Inscripción al taller", "Inscrição na oficina", "التسجيل في الورشة"),
    "₪18,000/חודש": r("₪18,000/month", "₪18,000/mes", "₪18,000/mês", "₪18,000/شهر"),
    "ג׳ינס": r("Jeans", "Vaqueros", "Jeans", "جينز"),
    "ג׳קטים": r("Jackets", "Chaquetas", "Jaquetas", "سترات"),
    "טישרטים": r("T-shirts", "Camisetas", "Camisetas", "تيشيرتات"),
    "סוכר כחומר גלם — לא רק מתיקות.": r("Sugar as an ingredient — not only sweetness.", "El azúcar como materia: no solo dulzor.", "Açúcar como matéria — não só doçura.", "السكر كمادة خام — ليس حلاوة فقط."),
    "הקיטור מרים — הסל יורד לשולחן.": r("Steam rises — the basket lands on the table.", "El vapor sube: la cesta baja a la mesa.", "O vapor sobe — a cesta desce à mesa.", "البخار يرتفع — والسلة تصل إلى الطاولة."),
    "עיצוב אישי": r("Personal design", "Diseño personal", "Design pessoal", "تصميم شخصي"),
    "5 חדרים": r("5 rooms", "5 habitaciones", "5 quartos", "5 غرف"),
    "בלעדי": r("Exclusive", "Exclusivo", "Exclusivo", "حصري"),
    "לקביעת שיחה": r("To book a call", "Para reservar una llamada", "Para agendar uma chamada", "لحجز مكالمة"),
    "השף": r("The chef", "El chef", "O chef", "الشيف"),
    "בקשת גישה": r("Access request", "Solicitud de acceso", "Pedido de acesso", "طلب وصول"),
    "צמחי בית": r("Houseplants", "Plantas de interior", "Plantas de interior", "نباتات منزلية"),
    "סוקולנטים": r("Succulents", "Suculentas", "Suculentas", "عصاريات"),
    "עציצים": r("Pots", "Macetas", "Vasos", "أصص"),
    "טיפול": r("Treatment", "Tratamiento", "Tratamento", "علاج"),
    "קהילה": r("Community", "Comunidad", "Comunidade", "مجتمع"),
    "סטודיו צילום": r("Photo studio", "Estudio fotográfico", "Estúdio fotográfico", "استوديو تصوير"),
    "ההמסה היא חלק מהחוויה.": r("The melt is part of the experience.", "La fusión es parte de la experiencia.", "O derretimento faz parte da experiência.", "الذوبان جزء من التجربة."),
    "צמידים": r("Bracelets", "Pulseras", "Pulseiras", "أساور"),
    "הזמנת תור": r("Book an appointment", "Reservar cita", "Agendar horário", "حجز موعد"),
    "איפור": r("Makeup", "Maquillaje", "Maquiagem", "مكياج"),
    "ירקות": r("Vegetables", "Verduras", "Vegetais", "خضار"),
    "פירות": r("Fruit", "Fruta", "Frutas", "فاكهة"),
    "דגנים": r("Grains", "Cereales", "Cereais", "حبوب"),
    "ממרחים": r("Spreads", "Untables", "Pasta", "دهون"),
    "לשירותים": r("To services", "A los servicios", "Para os serviços", "إلى الخدمات"),
    "שיפוצים": r("Renovations", "Reformas", "Reformas", "تجديدات"),
    "טקסטיל": r("Textiles", "Textiles", "Têxteis", "منسوجات"),
    "רהיטים": r("Furniture", "Muebles", "Móveis", "أثاث"),
    "סחוט עכשיו — נשתייה מיד.": r("Squeeze now — we drink it right away.", "Exprime ahora: lo bebemos al momento.", "Esprema agora — bebemos na hora.", "اعصروا الآن — نشرب فوراً."),
    "הודים": r("Indian", "Indio", "Indiano", "هندي"),
    "כובעים": r("Hats", "Sombreros", "Chapéus", "قبعات"),
    "ייעוץ": r("Consulting", "Consultoría", "Consultoria", "استشارة"),
    "לקוחות חוזרים": r("Returning clients", "Clientes que vuelven", "Clientes que voltam", "عملاء عائدون"),
    "מצעים": r("Bedding", "Ropa de cama", "Roupa de cama", "مفروشات"),
    "מגבות": r("Towels", "Toallas", "Toalhas", "مناشف"),
    "כריות": r("Pillows", "Almohadas", "Travesseiros", "وسائد"),
    "וילונות": r("Curtains", "Cortinas", "Cortinas", "ستائر"),
    "פיג׳מות": r("Pajamas", "Pijamas", "Pijamas", "بيجامات"),
    "חלוקים": r("Robes", "Albornoces", "Roupões", "أردية"),
    "אודיו": r("Audio", "Audio", "Áudio", "صوت"),
    "סמארט הום": r("Smart home", "Hogar inteligente", "Casa inteligente", "منزل ذكي"),
    "בקשת הזמנה": r("Order request", "Solicitud de pedido", "Pedido de encomenda", "طلب طلبية"),
    "למסלולים": r("To the plans", "A los planes", "Para os planos", "إلى المسارات"),
    "ארגון": r("Organization", "Organización", "Organização", "تنظيم"),
    "מטבח": r("Kitchen", "Cocina", "Cozinha", "مطبخ"),
    "קערות": r("Bowls", "Cuencos", "Tigelas", "أطباق عميقة"),
    "בואו נדבר": r("Let’s talk", "Hablemos", "Vamos conversar", "لنتحدث"),
    "סירים": r("Pots", "Ollas", "Panelas", "قدور"),
    "סכינים": r("Knives", "Cuchillos", "Facas", "سكاكين"),
    "הבצק טרי — הרטב מספר סיפור.": r("The dough is fresh — the sauce tells a story.", "La masa está fresca: la salsa cuenta una historia.", "A massa está fresca — o molho conta uma história.", "العجين طازج — والصلصة تروي قصة."),
    "מזון": r("Food", "Alimentos", "Alimentos", "غذاء"),
    "מיטות": r("Beds", "Camas", "Camas", "أسرّة"),
    "היגיינה": r("Hygiene", "Higiene", "Higiene", "نظافة"),
    "עזרה ראשונה": r("First aid", "Primeros auxilios", "Primeiros socorros", "إسعاف أولي"),
    "תוספים": r("Supplements", "Complementos", "Suplementos", "مكملات"),
    "מהאדמה לצלחת — בלי פשרות על טעם.": r("From soil to plate — no compromise on flavor.", "De la tierra al plato, sin renunciar al sabor.", "Da terra ao prato — sem abrir mão do sabor.", "من الأرض إلى الطبق — بلا تنازل عن الطعم."),
    "משחקי קופסה": r("Board games", "Juegos de mesa", "Jogos de tabuleiro", "ألعاب طاولة"),
    "דמויות": r("Figures", "Figuras", "Bonecos", "شخصيات"),
    "חוץ": r("Outdoor", "Exterior", "Exterior", "خارج"),
    "כל קערה היא מסלול טעמים.": r("Every bowl is a flavor path.", "Cada cuenco es un recorrido de sabores.", "Cada tigela é um percurso de sabores.", "كل وعاء مسار نكهات."),
    "נרות": r("Candles", "Velas", "Velas", "شموع"),
    "דיפיוזרים": r("Diffusers", "Difusores", "Difusores", "موزّعات"),
    "שמנים": r("Oils", "Aceites", "Óleos", "زيوت"),
    "סלון": r("Living room", "Salón", "Sala", "صالة"),
    "הים מגיע לצלחת — בלי עיכובים.": r("The sea reaches the plate — without delay.", "El mar llega al plato, sin demoras.", "O mar chega ao prato — sem atrasos.", "البحر يصل إلى الطبق — بلا تأخير."),
    "השיפוד מסתובב — הטעם נשאר.": r("The spit turns — the flavor stays.", "El asador gira: el sabor se queda.", "O espeto gira — o sabor fica.", "السيخ يدور — والطعم يبقى."),
    "11 ביוני 2024": r("June 11, 2024", "11 de junio de 2024", "11 de junho de 2024", "11 يونيو 2024"),
    "עשן נמוך, חום ארוך, טעם עמוק.": r("Low smoke, long heat, deep flavor.", "Humo bajo, calor largo, sabor profundo.", "Fumaça baixa, calor longo, sabor profundo.", "دخان منخفض وحرارة طويلة وطعم عميق."),
    "לייפסטייל": r("Lifestyle", "Estilo de vida", "Lifestyle", "أسلوب حياة"),
    "ריצה": r("Running", "Running", "Corrida", "جري"),
    "קולאב": r("Collab", "Colab", "Collab", "تعاون"),
    "אלגנט": r("Elegant", "Elegante", "Elegante", "أنيق"),
    "יומיום": r("Everyday", "Día a día", "Dia a dia", "يومي"),
    "ידניים": r("Manual", "Manuales", "Manuais", "يدوي"),
    "אחסון": r("Storage", "Almacenaje", "Armazenamento", "تخزين"),
    "בטיחות": r("Safety", "Seguridad", "Segurança", "سلامة"),
    "אוהלים": r("Tents", "Tiendas", "Barracas", "خيام"),
    "תרמילים": r("Packs", "Mochilas", "Mochilas", "حقائب"),
    "בישול שטח": r("Camp cooking", "Cocina de campo", "Cozinha de campo", "طبخ ميداني"),
    "אדומים": r("Reds", "Tintos", "Tintos", "حمراء"),
    "לבנים": r("Whites", "Blancos", "Brancos", "بيضاء"),
    "מבעבעים": r("Sparkling", "Espumosos", "Espumantes", "فوارة"),
    "ויטמינים": r("Vitamins", "Vitaminas", "Vitaminas", "فيتامينات"),
    "מינרלים": r("Minerals", "Minerales", "Minerais", "معادن"),
    "חלבון": r("Protein", "Proteína", "Proteína", "بروتين"),
    "שינה": r("Sleep", "Sueño", "Sono", "نوم"),
    "סמארט": r("Smart", "Smart", "Smart", "ذكي"),
    "כביש": r("Road", "Carretera", "Estrada", "طريق"),
    "שטח": r("Off-road", "Campo", "Off-road", "أراضٍ"),

    # Library picker leftovers
    "5 כוכבים": r("5 stars", "5 estrellas", "5 estrelas", "5 نجوم"),
    "אבטחה": r("Security", "Seguridad", "Segurança", "أمن"),
    "אגודל למעלה": r("Thumbs up", "Pulgar arriba", "Joinha", "إعجاب"),
    "אדום": r("Red", "Rojo", "Vermelho", "أحمر"),
    "אופקי: מדיה משמאל ותוכן מימין": r("Horizontal: media on the left, content on the right", "Horizontal: media a la izquierda y contenido a la derecha", "Horizontal: mídia à esquerda e conteúdo à direita", "أفقي: وسائط يساراً ومحتوى يميناً"),
    "אזור אישי": r("Personal area", "Área personal", "Área pessoal", "منطقة شخصية"),
    "אייקון, כותרת וטקסט קצר": r("Icon, heading, and short text", "Icono, título y texto corto", "Ícone, título e texto curto", "أيقونة وعنوان ونص قصير"),
    "אימייל": r("Email", "Email", "E-mail", "بريد"),
    "אנימציית אישור ירוקה": r("Green confirmation animation", "Animación de confirmación verde", "Animação de confirmação verde", "حركة تأكيد خضراء"),
    "אנימציית חנות": r("Store animation", "Animación de tienda", "Animação de loja", "حركة متجر"),
    "באנר קריאה לפעולה": r("Call-to-action banner", "Banner de llamada a la acción", "Banner de chamada", "لافتة دعوة للإجراء"),
    "בועת שיחה": r("Chat bubble", "Burbuja de chat", "Bolha de chat", "فقاعة دردشة"),
    "בינוני": r("Medium", "Medio", "Médio", "متوسط"),
    "בלוק ריק ליצירת אוויר בין אלמנטים": r("Empty block to add air between elements", "Bloque vacío para aire entre elementos", "Bloco vazio para ar entre elementos", "كتلة فارغة لخلق فراغ بين العناصر"),
    "במה אפשר לעזור?": r("How can we help?", "¿En qué podemos ayudar?", "Como podemos ajudar?", "كيف يمكن المساعدة؟"),
    "ברכה אישית — אחרי התחברות מוצג שם הלקוח מהאזור האישי / CRM": r(
        "Personal greeting — after sign-in the client name from the portal / CRM is shown",
        "Saludo personal: tras entrar se muestra el nombre del cliente del área / CRM",
        "Saudação pessoal — após o login aparece o nome do cliente da área / CRM",
        "تحية شخصية — بعد تسجيل الدخول يظهر اسم العميل من المنطقة الشخصية / CRM",
    ),
    "גלגל שיניים": r("Gear", "Engranaje", "Engrenagem", "ترس"),
    "גלובוס": r("Globe", "Globo", "Globo", "كرة أرضية"),
    "גרף עולה": r("Rising chart", "Gráfico al alza", "Gráfico em alta", "رسم بياني صاعد"),
    "דירוג כוכבים": r("Star rating", "Valoración de estrellas", "Avaliação em estrelas", "تقييم نجوم"),
    "הגדרות": r("Settings", "Ajustes", "Configurações", "إعدادات"),
    "הודעה": r("Message", "Mensaje", "Mensagem", "رسالة"),
    "הזמנות": r("Orders", "Pedidos", "Pedidos", "طلبات"),
    "הנתונים שלי": r("My data", "Mis datos", "Meus dados", "بياناتي"),
    "העלאה לענן": r("Upload to the cloud", "Subir a la nube", "Enviar à nuvem", "رفع إلى السحابة"),
    "הפגישה הבאה": r("Next appointment", "Próxima cita", "Próximo horário", "الموعد التالي"),
    "הפגישה הבאה - מהיומן": r("Next appointment — from the calendar", "Próxima cita — del calendario", "Próximo horário — da agenda", "الموعد التالي — من التقويم"),
    "השקה וצמיחה": r("Launch and growth", "Lanzamiento y crecimiento", "Lançamento e crescimento", "إطلاق ونمو"),
    "התראה": r("Alert", "Alerta", "Alerta", "تنبيه"),
    "וי הצלחה": r("Success check", "Check de éxito", "Check de sucesso", "علامة نجاح"),
    "ורוד": r("Pink", "Rosa", "Rosa", "وردي"),
    "זכוכית מגדלת": r("Magnifying glass", "Lupa", "Lupa", "عدسة مكبرة"),
    "חגיגת הצלחה": r("Success celebration", "Celebración de éxito", "Celebração de sucesso", "احتفال نجاح"),
    "חיפוש": r("Search", "Buscar", "Busca", "بحث"),
    "טבלה": r("Table", "Tabla", "Tabela", "جدول"),
    "טבלה ניתנת לעריכה עם כותרות ושורות": r("Editable table with headings and rows", "Tabla editable con títulos y filas", "Tabela editável com títulos e linhas", "جدول قابل للتحرير بعناوين وصفوف"),
    "טבלה פשוטה": r("Simple table", "Tabla simple", "Tabela simples", "جدول بسيط"),
    "טבלת מחירים": r("Price table", "Tabla de precios", "Tabela de preços", "جدول أسعار"),
    "טבלת נתונים נקייה עם 3 עמודות": r("Clean data table with 3 columns", "Tabla de datos limpia con 3 columnas", "Tabela de dados limpa com 3 colunas", "جدول بيانات نظيف بـ 3 أعمدة"),
    "טורקיז": r("Turquoise", "Turquesa", "Turquesa", "فيروزي"),
    "טיל שיגור": r("Launch rocket", "Cohete", "Foguete", "صاروخ إطلاق"),
    "טלפון": r("Phone", "Teléfono", "Telefone", "هاتف"),
    "טלפון הלקוח מה-CRM": r("Client phone from the CRM", "Teléfono del cliente del CRM", "Telefone do cliente do CRM", "هاتف العميل من CRM"),
    "טלפון לקוח": r("Client phone", "Teléfono del cliente", "Telefone do cliente", "هاتف العميل"),
    "טעינה": r("Loading", "Carga", "Carregamento", "تحميل"),
    "יומן": r("Calendar", "Calendario", "Agenda", "تقويم"),
    "ירוק": r("Green", "Verde", "Verde", "أخضر"),
    "יתרה": r("Balance", "Saldo", "Saldo", "رصيد"),
    "יתרה - ערך מה-CRM של הלקוח המחובר": r("Balance — value from the signed-in client's CRM", "Saldo — valor del CRM del cliente conectado", "Saldo — valor do CRM do cliente conectado", "رصيد — قيمة من CRM للعميل المتصل"),
    "כוס קפה מעוררת": r("A waking coffee cup", "Taza de café que despierta", "Xícara de café que acorda", "فنجان قهوة منعش"),
    "כחול": r("Blue", "Azul", "Azul", "أزرق"),
    "כמות טיפולים": r("Number of treatments", "Cantidad de tratamientos", "Quantidade de tratamentos", "عدد العلاجات"),
    "כמות טיפולים - ערך מה-CRM של הלקוח המחובר": r(
        "Number of treatments — value from the signed-in client's CRM",
        "Cantidad de tratamientos — valor del CRM del cliente conectado",
        "Quantidade de tratamentos — valor do CRM do cliente conectado",
        "عدد العلاجات — قيمة من CRM للعميل المتصل",
    ),
    "כפתור הפעלה": r("Play button", "Botón de reproducción", "Botão de reprodução", "زر تشغيل"),
    "כרטיס אופקי": r("Horizontal card", "Tarjeta horizontal", "Cartão horizontal", "بطاقة أفقية"),
    "כרטיס אנכי מעוגל": r("Rounded vertical card", "Tarjeta vertical redondeada", "Cartão vertical arredondado", "بطاقة عمودية مستديرة"),
    "כרטיס בהיר עם צל עדין ופינות גדולות": r("Light card with a soft shadow and large corners", "Tarjeta clara con sombra suave y esquinas grandes", "Cartão claro com sombra suave e cantos grandes", "بطاقة فاتحة بظل لطيف وزوايا كبيرة"),
    "כרטיס גבוה עם פינות מעוגלות": r("Tall card with rounded corners", "Tarjeta alta con esquinas redondeadas", "Cartão alto com cantos arredondados", "بطاقة طويلة بزوايا مستديرة"),
    "כרטיס המלצה": r("Testimonial card", "Tarjeta de testimonio", "Cartão de depoimento", "بطاقة توصية"),
    "כרטיס כהה": r("Dark card", "Tarjeta oscura", "Cartão escuro", "بطاقة داكنة"),
    "כרטיס כהה בולט למידע חשוב": r("Bold dark card for important information", "Tarjeta oscura destacada para información importante", "Cartão escuro em destaque para informação importante", "بطاقة داكنة بارزة لمعلومة مهمة"),
    "כרטיס כמוסה": r("Capsule card", "Tarjeta cápsula", "Cartão cápsula", "بطاقة كبسولة"),
    "כרטיס מחיר": r("Price card", "Tarjeta de precio", "Cartão de preço", "بطاقة سعر"),
    "כרטיס מסגרת": r("Framed card", "Tarjeta con marco", "Cartão com moldura", "بطاقة بإطار"),
    "כרטיס מספר": r("Number card", "Tarjeta de número", "Cartão de número", "بطاقة رقم"),
    "כרטיס מרובע": r("Square card", "Tarjeta cuadrada", "Cartão quadrado", "بطاقة مربعة"),
    "כרטיס עם אייקון": r("Card with icon", "Tarjeta con icono", "Cartão com ícone", "بطاقة بأيقونة"),
    "כרטיס עם כותרת, טקסט וכפתור — הכל ניתן לעריכה": r(
        "Card with heading, text, and button — all editable",
        "Tarjeta con título, texto y botón: todo editable",
        "Cartão com título, texto e botão — tudo editável",
        "بطاقة بعنوان ونص وزر — الكل قابل للتحرير",
    ),
    "כרטיס צל רך": r("Soft-shadow card", "Tarjeta de sombra suave", "Cartão de sombra suave", "بطاقة ظل ناعم"),
    "כרטיס רחב לרוחב עם כותרת וטקסט בצד": r("Wide card with heading and text on the side", "Tarjeta ancha con título y texto al lado", "Cartão largo com título e texto ao lado", "بطاقة عريضة بعنوان ونص جانبي"),
    "כרטיס ריבועי עם פינות חדות יחסית": r("Square card with relatively sharp corners", "Tarjeta cuadrada con esquinas más vivas", "Cartão quadrado com cantos mais vivos", "بطاقة مربعة بزوايا حادة نسبياً"),
    "כרטיס שקוף עם מסגרת עבה": r("Transparent card with a thick frame", "Tarjeta transparente con marco grueso", "Cartão transparente com moldura grossa", "بطاقة شفافة بإطار سميك"),
    "כרטיס תמונה בצד": r("Card with side image", "Tarjeta con imagen al lado", "Cartão com imagem ao lado", "بطاقة بصورة جانبية"),
    "כרטיס תמחור עם מחיר וכפתור": r("Pricing card with a price and button", "Tarjeta de precios con precio y botón", "Cartão de preço com valor e botão", "بطاقة تسعير بسعر وزر"),
    "כרטיסיית פיצ׳ר": r("Feature card", "Tarjeta de función", "Cartão de recurso", "بطاقة ميزة"),
    "כתובת המייל של הלקוח מה-CRM": r("Client email from the CRM", "Email del cliente del CRM", "E-mail do cliente do CRM", "بريد العميل من CRM"),
    "כתום": r("Orange", "Naranja", "Laranja", "برتقالي"),
    "לב פועם": r("Beating heart", "Corazón latiente", "Coração batendo", "قلب نابض"),
    "לבן": r("White", "Blanco", "Branco", "أبيض"),
    "לייק": r("Like", "Me gusta", "Curtida", "إعجاب"),
    "לייק לב": r("Heart like", "Me gusta corazón", "Curtida coração", "إعجاب قلب"),
    "מוזיקה": r("Music", "Música", "Música", "موسيقى"),
    "מוסיף טקסט בפורמט ״שם - ערך״ בכל מקום בעמוד — בלי כרטיסייה": r(
        "Adds text in a “name - value” format anywhere on the page — without a card",
        "Añade texto en formato «nombre - valor» en cualquier parte, sin tarjeta",
        "Adiciona texto no formato “nome - valor” em qualquer lugar — sem cartão",
        "يضيف نصاً بصيغة «اسم - قيمة» في أي مكان بالصفحة — بلا بطاقة",
    ),
    "מייל לקוח": r("Client email", "Email del cliente", "E-mail do cliente", "بريد العميل"),
    "מנעול מאובטח": r("Secure lock", "Candado seguro", "Cadeado seguro", "قفل آمن"),
    "מסגרת סגול": r("Purple frame", "Marco morado", "Moldura roxa", "إطار بنفسجي"),
    "מספר גדול עם כותרת משנה — אידיאלי לסטטיסטיקות": r(
        "Large number with a subtitle — ideal for stats",
        "Número grande con subtítulo: ideal para estadísticas",
        "Número grande com subtítulo — ideal para estatísticas",
        "رقم كبير مع عنوان فرعي — مثالي للإحصاءات",
    ),
    "מעטפה נשלחת": r("Sending envelope", "Sobre enviándose", "Envelope sendo enviado", "ظرف يُرسل"),
    "מפגשים שבוצעו": r("Completed sessions", "Sesiones realizadas", "Sessões realizadas", "جلسات منفّذة"),
    "מפגשים שבוצעו - ערך מה-CRM של הלקוח המחובר": r(
        "Completed sessions — value from the signed-in client's CRM",
        "Sesiones realizadas — valor del CRM del cliente conectado",
        "Sessões realizadas — valor do CRM do cliente conectado",
        "جلسات منفّذة — قيمة من CRM للعميل المتصل",
    ),
    "מצלמה": r("Camera", "Cámara", "Câmera", "كاميرا"),
    "מרובע": r("Square", "Cuadrado", "Quadrado", "مربع"),
    "מרווח": r("Spacer", "Espacio", "Espaço", "مسافة"),
    "משאית משלוחים": r("Delivery truck", "Camión de envíos", "Caminhão de entregas", "شاحنة توصيل"),
    "משלוח": r("Shipping", "Envío", "Entrega", "شحن"),
    "משקל": r("Weight", "Peso", "Peso", "وزن"),
    "משקל אחרון ממעקב CRM (תאריך/שעה/ערך) של הלקוח המחובר": r(
        "Latest weight from CRM tracking (date/time/value) for the signed-in client",
        "Último peso del seguimiento CRM (fecha/hora/valor) del cliente conectado",
        "Último peso do acompanhamento CRM (data/hora/valor) do cliente conectado",
        "آخر وزن من متابعة CRM (تاريخ/وقت/قيمة) للعميل المتصل",
    ),
    "משתמש": r("User", "Usuario", "Usuário", "مستخدم"),
    "מתנה": r("Gift", "Regalo", "Presente", "هدية"),
    "נגן וידאו": r("Video player", "Reproductor de vídeo", "Player de vídeo", "مشغّل فيديو"),
    "נורה ורעיון": r("Bulb and idea", "Bombilla e idea", "Lâmpada e ideia", "مصباح وفكرة"),
    "נתון CRM": r("CRM stat", "Dato CRM", "Dado CRM", "بيان CRM"),
    "נתון משתנה מה-CRM": r("A live CRM value", "Un valor variable del CRM", "Um valor variável do CRM", "قيمة متغيرة من CRM"),
    "סגול": r("Purple", "Morado", "Roxo", "بنفسجي"),
    "סיכום": r("Summary", "Resumen", "Resumo", "ملخص"),
    "סיכום - ערך מהתיק ב-CRM": r("Summary — value from the CRM file", "Resumen — valor del expediente CRM", "Resumo — valor do prontuário CRM", "ملخص — قيمة من ملف CRM"),
    "סימון מפה": r("Map pin", "Marca de mapa", "Pino de mapa", "دبوس خريطة"),
    "סנכרון ענן": r("Cloud sync", "Sincronización en la nube", "Sincronização na nuvem", "مزامنة سحابية"),
    "ספינר טעינה מקצועי": r("Professional loading spinner", "Spinner de carga profesional", "Spinner de carregamento profissional", "دوّارة تحميل احترافية"),
    "עבודת צוות": r("Teamwork", "Trabajo en equipo", "Trabalho em equipe", "عمل جماعي"),
    "עגול": r("Round", "Redondo", "Redondo", "دائري"),
    "עולם ורשת": r("World and web", "Mundo y red", "Mundo e rede", "عالم وشبكة"),
    "עט וכתיבה": r("Pen and writing", "Pluma y escritura", "Caneta e escrita", "قلم وكتابة"),
    "פעמון התראות": r("Notification bell", "Campana de avisos", "Sino de alertas", "جرس تنبيهات"),
    "פרופיל": r("Profile", "Perfil", "Perfil", "ملف"),
    "צ'אט": r("Chat", "Chat", "Chat", "دردشة"),
    "צורת כמוסה מעוגלת מאוד": r("A very rounded capsule shape", "Forma cápsula muy redondeada", "Forma cápsula bem arredondada", "شكل كبسولة مستدير جداً"),
    "ציטוט לקוח עם שם ותפקיד": r("Client quote with name and role", "Cita de cliente con nombre y cargo", "Citação de cliente com nome e cargo", "اقتباس عميل مع الاسم والدور"),
    "צילום תמונה": r("Take a photo", "Hacer una foto", "Tirar uma foto", "التقاط صورة"),
    "צמיחה כספית": r("Financial growth", "Crecimiento financiero", "Crescimento financeiro", "نمو مالي"),
    "קו מפריד": r("Divider", "Separador", "Divisor", "فاصل"),
    "קונפטי": r("Confetti", "Confeti", "Confete", "قصاصات"),
    "קופסת מתנה": r("Gift box", "Caja de regalo", "Caixa de presente", "علبة هدية"),
    "קפה": r("Coffee", "Café", "Café", "قهوة"),
    "רך": r("Soft", "Suave", "Suave", "ناعم"),
    "רעיון": r("Idea", "Idea", "Ideia", "فكرة"),
    "רצועת CTA עם כותרת וכפתור": r("CTA strip with heading and button", "Franja CTA con título y botón", "Faixa CTA com título e botão", "شريط دعوة بعنوان وزر"),
    "שאלה ותשובה ניתנות לעריכה מלאה": r("Fully editable question and answer", "Pregunta y respuesta totalmente editables", "Pergunta e resposta totalmente editáveis", "سؤال وجواب قابلان للتحرير بالكامل"),
    "שאלת FAQ": r("FAQ question", "Pregunta FAQ", "Pergunta FAQ", "سؤال شائع"),
    "שורת 3 מדדים": r("Row of 3 metrics", "Fila de 3 métricas", "Linha de 3 métricas", "صف من 3 مؤشرات"),
    "שחור": r("Black", "Negro", "Preto", "أسود"),
    "שירות רצוי": r("Preferred service", "Servicio deseado", "Serviço desejado", "الخدمة المطلوبة"),
    "שיתוף פעולה": r("Collaboration", "Colaboración", "Colaboração", "تعاون"),
    "שלום, שם לקוח": r("Hello, client name", "Hola, nombre de cliente", "Olá, nome do cliente", "مرحباً، اسم العميل"),
    "שלושה כרטיסי מספר אופקיים": r("Three horizontal number cards", "Tres tarjetas de número horizontales", "Três cartões de número horizontais", "ثلاث بطاقات رقم أفقية"),
    "שליחת מייל": r("Send email", "Enviar email", "Enviar e-mail", "إرسال بريد"),
    "שם הלקוח מהאזור האישי / CRM": r("Client name from the portal / CRM", "Nombre del cliente del área / CRM", "Nome do cliente da área / CRM", "اسم العميل من المنطقة الشخصية / CRM"),
    "שם לקוח": r("Client name", "Nombre de cliente", "Nome do cliente", "اسم العميل"),
    "שם מלא": r("Full name", "Nombre completo", "Nome completo", "الاسم الكامل"),
    "שקית קניות": r("Shopping bag", "Bolsa de compra", "Sacola de compras", "كيس تسوق"),
    "תאריך מועדף": r("Preferred date", "Fecha preferida", "Data preferida", "التاريخ المفضّل"),
    "תג הנחה": r("Discount tag", "Etiqueta de descuento", "Etiqueta de desconto", "وسم خصم"),
    "תגית תווית": r("Label tag", "Etiqueta", "Etiqueta", "وسم تسمية"),
    "תו מוזיקלי": r("Music note", "Nota musical", "Nota musical", "نوتة موسيقية"),
    "תווית קטנה להדגשת יתרון או מבצע": r("Small label to highlight a benefit or promo", "Etiqueta pequeña para destacar una ventaja o promo", "Etiqueta pequena para destacar vantagem ou promoção", "وسم صغير لإبراز ميزة أو عرض"),
    "תוכנית המשך": r("Follow-up plan", "Plan de continuidad", "Plano de continuidade", "خطة متابعة"),
    "תוכנית המשך - מה-CRM": r("Follow-up plan — from the CRM", "Plan de continuidad — del CRM", "Plano de continuidade — do CRM", "خطة متابعة — من CRM"),
    "תוכנית טיפול": r("Care plan", "Plan de tratamiento", "Plano de tratamento", "خطة علاج"),
    "תזמון ופגישות": r("Scheduling and meetings", "Agenda y reuniones", "Agenda e reuniões", "جدولة واجتماعات"),
    "תכנית טיפול": r("Treatment plan", "Plan de tratamiento", "Plano de tratamento", "خطة علاج"),
    "תכנית טיפול - מה-CRM": r("Treatment plan — from the CRM", "Plan de tratamiento — del CRM", "Plano de tratamento — do CRM", "خطة علاج — من CRM"),
    "תכנית מעקב": r("Follow-up program", "Plan de seguimiento", "Plano de acompanhamento", "خطة متابعة"),
    "תכנית מעקב - מה-CRM": r("Follow-up program — from the CRM", "Plan de seguimiento — del CRM", "Plano de acompanhamento — do CRM", "خطة متابعة — من CRM"),
    "תמונת גיבור": r("Hero image", "Imagen hero", "Imagem hero", "صورة البطل"),
    "ברוכים הבאים": r("Welcome", "Bienvenidos", "Bem-vindos", "أهلاً وسهلاً"),
    "כותרת": r("Heading", "Título", "Título", "عنوان"),
}
