"""Extra leftover stems and verbs for compositional coverage."""


def r(en, es, pt, ar):
    return {"en": en, "es": es, "pt-BR": pt, "ar": ar}


EXTRA = {
    "טוב": r("good", "bueno", "bom", "جيد"),
    "נכון": r("right", "correcto", "certo", "صحيح"),
    "נעים": r("pleasant", "agradable", "agradável", "لطيف"),
    "מתעד": r("documents", "documenta", "documenta", "يوثّق"),
    "ניחוש": r("guesswork", "suposición", "achismo", "تخمين"),
    "לאורך": r("along", "a lo largo de", "ao longo de", "على مدار"),
    "הזמנה": r("order", "pedido", "pedido", "طلب"),
    "מול": r("versus", "frente a", "diante de", "أمام"),
    "עומס": r("load", "carga", "carga", "حمل"),
    "דק": r("thin", "fino", "fino", "رفيع"),
    "מנה": r("dish", "plato", "prato", "طبق"),
    "חנויות": r("stores", "tiendas", "lojas", "متاجر"),
    "אחרות": r("other", "otras", "outras", "أخرى"),
    "עשרות": r("dozens of", "decenas de", "dezenas de", "عشرات"),
    "קונים": r("buyers", "compradores", "compradores", "مشترون"),
    "זוהר": r("glow", "brillo", "brilho", "توهج"),
    "רמת": r("level of", "nivel de", "nível de", "مستوى"),
    "הפך": r("became", "se convirtió", "virou", "أصبح"),
    "שבוע": r("week", "semana", "semana", "أسبوع"),
    "תוך": r("within", "en", "em", "خلال"),
    "בניית": r("building", "construcción de", "construção de", "بناء"),
    "חבילות": r("packages", "paquetes", "pacotes", "باقات"),
    "מהרגע": r("from the moment", "desde el momento", "desde o momento", "من اللحظة"),
    "היה": r("was", "fue", "foi", "كان"),
    "יכולה": r("can", "puede", "pode", "تستطيع"),
    "רגע": r("moment", "momento", "momento", "لحظة"),
    "אמת": r("truth", "verdad", "verdade", "حقيقة"),
    "בדיקה": r("check", "revisión", "checagem", "فحص"),
    "בדיקות": r("checks", "revisiones", "checagens", "فحوصات"),
    "חמאה": r("butter", "mantequilla", "manteiga", "زبدة"),
    "שלי": r("mine", "mío", "meu", "لي"),
    "אליכם": r("to you", "a vosotros", "a vocês", "إليكم"),
    "רעש": r("noise", "ruido", "ruído", "ضجيج"),
    "אחרת": r("otherwise", "de otro modo", "de outro modo", "وإلا"),
    "חתימת": r("signature", "firma de", "assinatura de", "توقيع"),
    "בונה": r("builds", "construye", "constrói", "يبني"),
    "בלתי": r("un-", "in-", "in-", "غير"),
    "רשימת": r("list of", "lista de", "lista de", "قائمة"),
    "החל": r("starting", "desde", "a partir de", "اعتباراً من"),
    "כניסה": r("entrance", "entrada", "entrada", "دخول"),
    "רכיבה": r("riding", "equitación", "pedalada", "ركوب"),
    "שינוי": r("change", "cambio", "mudança", "تغيير"),
    "הכול": r("everything", "todo", "tudo", "كل شيء"),
    "בתוך": r("inside", "dentro de", "dentro de", "داخل"),
    "שלב": r("stage", "etapa", "etapa", "مرحلة"),
    "צוותים": r("teams", "equipos", "equipes", "فرق"),
    "מוצגים": r("are shown", "se muestran", "são exibidos", "تُعرض"),
    "מרגישה": r("feels", "se siente", "parece", "تشعر"),
    "אותו": r("it", "lo", "o", "إياه"),
    "שיחת": r("a call about", "una llamada de", "uma chamada de", "مكالمة"),
    "שוטף": r("ongoing", "continuo", "contínuo", "جارٍ"),
    "רכות": r("softness", "suavidad", "suavidade", "نعومة"),
    "דרופ": r("drop", "drop", "drop", "دروب"),
    "פארם": r("pharma", "farma", "farma", "أدوية"),
    "ראשונה": r("first", "primera", "primeira", "أولى"),
    "טאקוס": r("tacos", "tacos", "tacos", "تاكو"),
    "מקבל": r("receives", "recibe", "recebe", "يتلقى"),
    "פגישת": r("a meeting of", "una reunión de", "uma reunião de", "اجتماع"),
    "נשכח": r("forgotten", "olvidado", "esquecido", "منسي"),
    "עומד": r("stands", "está", "está", "يقف"),
    "מחובר": r("connected", "conectado", "conectado", "متصل"),
    "להרגל": r("into a habit", "en hábito", "em hábito", "إلى عادة"),
    "מוקדמות": r("early", "tempranas", "antecipadas", "مبكرة"),
    "פחות": r("less", "menos", "menos", "أقل"),
    "סיבות": r("reasons", "razones", "razões", "أسباب"),
    "התאמות": r("adjustments", "ajustes", "ajustes", "ملاءمات"),
    "טובה": r("good", "buena", "boa", "جيدة"),
    "ציר": r("axis", "eje", "eixo", "محور"),
    "מעושן": r("smoked", "ahumado", "defumado", "مدخّن"),
    "אין": r("there is no", "no hay", "não há", "لا يوجد"),
    "מדי": r("too", "demasiado", "demais", "جداً"),
    "לב": r("heart", "corazón", "coração", "قلب"),
    "הקינוח": r("the dessert", "el postre", "a sobremesa", "الحلوى"),
    "אביב": r("Aviv", "Aviv", "Aviv", "أبيب"),
    "המנה": r("the dish", "el plato", "o prato", "الطبق"),
    "לתחום": r("into the field", "al ámbito", "ao campo", "إلى المجال"),
    "לחות": r("moisture", "hidratación", "hidratação", "رطوبة"),
    "בן": r("son", "hijo", "filho", "ابن"),
    "השקות": r("launches", "lanzamientos", "lançamentos", "إطلاقات"),
    "קרם": r("cream", "crema", "creme", "كريم"),
    "מעלית": r("elevator", "ascensor", "elevador", "مصعد"),
    "יד": r("hand", "mano", "mão", "يد"),
    "יינות": r("wines", "vinos", "vinhos", "نبيذ"),
    "להרגיש": r("to feel", "sentir", "sentir", "للشعور"),
    "תמיכה": r("support", "soporte", "suporte", "دعم"),
    "אחר": r("other", "otro", "outro", "آخر"),
    "גיל": r("age", "edad", "idade", "عمر"),
    "מודל": r("model", "modelo", "modelo", "نموذج"),
    "קצרות": r("short", "cortas", "curtas", "قصيرة"),
    "אחריות": r("responsibility", "responsabilidad", "responsabilidade", "مسؤولية"),
    "שבועי": r("weekly", "semanal", "semanal", "أسبوعي"),
    "תחושה": r("feeling", "sensación", "sensação", "شعور"),
    "קונספט": r("concept", "concepto", "conceito", "مفهوم"),
    "ראשונית": r("initial", "inicial", "inicial", "أولية"),
    "ראשוני": r("initial", "inicial", "inicial", "أولي"),
    "בלבד": r("only", "solamente", "apenas", "فقط"),
    "השבוע": r("this week", "esta semana", "esta semana", "هذا الأسبوع"),
    "מידה": r("size", "talla", "tamanho", "مقاس"),
    "מחכה": r("waits", "espera", "espera", "ينتظر"),
    "דג": r("fish", "pescado", "peixe", "سمك"),
    "שוקולד": r("chocolate", "chocolate", "chocolate", "شوكولاتة"),
    "אל": r("to", "hacia", "a", "إلى"),
    "שתי": r("two", "dos", "duas", "اثنتان"),
    "עמודים": r("pages", "páginas", "páginas", "صفحات"),
    "אלון": r("Alon", "Alon", "Alon", "ألون"),
    "מחברת": r("notebook", "cuaderno", "caderno", "دفتر"),
    "מארז": r("set", "estuche", "kit", "علبة"),
    "מכירה": r("sale", "venta", "venda", "بيع"),
    "קל": r("easy", "fácil", "fácil", "سهل"),
    "כולל": r("includes", "incluye", "inclui", "يشمل"),
    "שליטה": r("control", "control", "controle", "سيطرة"),
    "צפייה": r("viewing", "visualización", "visualização", "مشاهدة"),
    "שעון": r("watch", "reloj", "relógio", "ساعة"),
    "מסמכים": r("documents", "documentos", "documentos", "مستندات"),
    "בוחרים": r("you choose", "elegís", "escolhem", "تختارون"),
    "כך": r("so", "así", "assim", "هكذا"),
    "עשירים": r("rich", "ricos", "ricos", "غنيّة"),
    "כלות": r("brides", "novias", "noivas", "عرائس"),
    "רפואית": r("medical", "médica", "médica", "طبية"),
    "קרמיקה": r("ceramics", "cerámica", "cerâmica", "سيراميك"),
    "לימון": r("lemon", "limón", "limão", "ليمون"),
    "התחילו": r("started", "empezaron", "começaram", "بدأوا"),
    "קריירה": r("career", "carrera", "carreira", "مسيرة"),
    "גוף": r("body", "cuerpo", "corpo", "جسم"),
    "עונתיים": r("seasonal", "de temporada", "sazonais", "موسمية"),
    "קוסמטיקה": r("cosmetics", "cosmética", "cosmética", "تجميل"),
    "ביטוח": r("insurance", "seguro", "seguro", "تأمين"),
    "התאמת": r("matching", "ajuste de", "ajuste de", "ملاءمة"),
    "מחברים": r("connectors", "conectores", "conectores", "موصّلات"),
    "שלבי": r("stages of", "etapas de", "etapas de", "مراحل"),
    "פסטה": r("pasta", "pasta", "massa", "باستا"),
    "לחיות": r("to live", "vivir", "viver", "للعيش"),
    "מחמד": r("pet", "mascota", "pet", "أليف"),
    "חיות": r("animals", "animales", "animais", "حيوانات"),
    "אוכל": r("food", "comida", "comida", "طعام"),
    "עירונית": r("urban", "urbana", "urbana", "حضرية"),
    "תרבות": r("culture", "cultura", "cultura", "ثقافة"),
    "בטוח": r("safe", "seguro", "seguro", "آمن"),
    "חיזוק": r("strengthening", "refuerzo", "reforço", "تعزيز"),
    "לחץ": r("pressure", "presión", "pressão", "ضغط"),
    "מעבר": r("transition", "paso", "passagem", "انتقال"),
    "שותף": r("partner", "socio", "parceiro", "شريك"),
    "לידים": r("leads", "leads", "leads", "عملاء محتملون"),
    "הליכה": r("walking", "paseo", "caminhada", "مشي"),
    "מקומיים": r("local", "locales", "locais", "محليون"),
    "עמוקה": r("deep", "profunda", "profunda", "عميقة"),
    "גב": r("back", "espalda", "costas", "ظهر"),
    "הרבה": r("a lot", "mucho", "muito", "كثير"),
    "הכי": r("the most", "lo más", "o mais", "الأكثر"),
    "חודשים": r("months", "meses", "meses", "أشهر"),
    "איכות": r("quality", "calidad", "qualidade", "جودة"),
    "תחת": r("under", "bajo", "sob", "تحت"),
    "משפחות": r("families", "familias", "famílias", "عائلات"),
    "שכבה": r("layer", "capa", "camada", "طبقة"),
    "סגנון": r("style", "estilo", "estilo", "أسلوب"),
    "שגרה": r("routine", "rutina", "rotina", "روتين"),
    "סוג": r("type", "tipo", "tipo", "نوع"),
    "שירה": r("poetry", "poesía", "poesia", "شعر"),
    "לוק": r("look", "look", "look", "لوك"),
    "רענון": r("refresh", "actualización", "atualização", "تحديث"),
    "מעיל": r("coat", "abrigo", "casaco", "معطف"),
    "חייב": r("must", "debe", "deve", "يجب"),
    "מגיע": r("arrives", "llega", "chega", "يصل"),
    "מותאמת": r("tailored", "adaptada", "adaptada", "مخصّصة"),
    "ראיונות": r("interviews", "entrevistas", "entrevistas", "مقابلات"),
    "כפר": r("village", "pueblo", "vila", "قرية"),
    "לאבד": r("to lose", "perder", "perder", "لفقدان"),
    "עונה": r("season", "temporada", "estação", "موسم"),
    "ליד": r("beside", "junto a", "ao lado de", "بجانب"),
    "אנרגיה": r("energy", "energía", "energia", "طاقة"),
    "שלבים": r("steps", "pasos", "etapas", "خطوات"),
    "רב": r("multi", "multi", "multi", "متعدد"),
    "בקרה": r("control", "control", "controle", "رقابة"),
    "אוטומציה": r("automation", "automatización", "automação", "أتمتة"),
    "סמאש": r("smash", "smash", "smash", "سماش"),
    "איטית": r("slow", "lenta", "lenta", "بطيئة"),
    "אורגני": r("organic", "orgánico", "orgânico", "عضوي"),
    "זקן": r("beard", "barba", "barba", "لحية"),
    "להורים": r("for parents", "para padres", "para pais", "للأهل"),
    "מילוי": r("filling", "relleno", "preenchimento", "حشو"),
    "ויזואלי": r("visual", "visual", "visual", "بصري"),
    "שדרות": r("boulevard", "bulevar", "avenida", "شارع"),
    "עו״ד": r("attorney", "abogado", "advogado", "محامٍ"),
    "ממשל": r("government", "gobierno", "governo", "حكومة"),
    "בקשת": r("a request for", "una solicitud de", "um pedido de", "طلب"),
    "הזמנת": r("booking", "reserva de", "reserva de", "حجز"),
    "מספיקה": r("is enough", "basta", "basta", "تكفي"),
    "מתעדכנים": r("update", "se actualizan", "atualizam", "تتحدّث"),
    "ישר": r("straight", "directo", "direto", "مباشرة"),
    "חוסך": r("saves", "ahorra", "poupa", "يوفر"),
    "מטורף": r("striking", "brutal", "absurdo", "مذهل"),
    "לוותר": r("to give up", "renunciar", "abrir mão", "للتخلّي"),
    "פונקציונליות": r("functionality", "funcionalidad", "funcionalidade", "وظائف"),
    "סננו": r("filter", "filtrad", "filtrem", "صفّوا"),
    "חפשו": r("search", "buscad", "busquem", "ابحثوا"),
    "שם": r("name", "nombre", "nome", "اسم"),
    "ומיינו": r("and sort", "y ordenad", "e ordenem", "وفرزوا"),
    "נטענים": r("load", "se cargan", "carregam", "تُحمَّل"),
    "שתגדירו": r("you define", "defináis", "definirem", "تعرّفوا"),
    "בתצוגה": r("on display", "en vitrina", "em exibição", "في العرض"),
    "פשוטה": r("simple", "sencilla", "simples", "بسيطة"),
    "תובנות": r("insights", "ideas", "insights", "رؤى"),
    "ושיפור": r("and improvement", "y mejora", "e melhoria", "وتحسين"),
    "מתמשך": r("continuous", "continuo", "contínuo", "مستمر"),
    "לייאאוט": r("layout", "maquetación", "layout", "تخطيط"),
    "המחלקות": r("the departments", "los departamentos", "os departamentos", "الأقسام"),
    "טיפולי": r("treatment", "de tratamiento", "de tratamento", "علاجي"),
    "מוצרי": r("products of", "productos de", "produtos de", "منتجات"),
    "ומסתיים": r("and ends", "y termina", "e termina", "وينتهي"),
    "בהנחיות": r("in the guidelines", "en las indicaciones", "nas orientações", "في الإرشادات"),
    "ואילו": r("while", "mientras", "enquanto", "بينما"),
    "שתבחרו": r("you choose", "elijáis", "escolherem", "تختارون"),
    "בבחירת": r("in choosing", "al elegir", "ao escolher", "في اختيار"),
    "חד": r("sharp", "nítido", "nítido", "حاد"),
    "שמתאימים": r("that fit", "que encajan", "que servem", "تناسب"),
    "האחרון": r("the last", "el último", "o último", "الأخير"),
    "דירת": r("apartment of", "piso de", "apartamento de", "شقة"),
    "תפעול": r("operations", "operación", "operação", "تشغيل"),
    "סוף": r("end", "final", "fim", "نهاية"),
    "הייתה": r("was", "fue", "foi", "كانت"),
    "אתכם": r("you", "os", "vocês", "معكم"),
    "שנשאר": r("that remains", "que queda", "que fica", "الذي يبقى"),
    "שמובילים": r("that lead", "que lideran", "que lideram", "الذين يقودون"),
    "שנכנסים": r("that enter", "que entran", "que entram", "الذين يدخلون"),
    "שעובד": r("that works", "que funciona", "que funciona", "الذي يعمل"),
    "שמרגישה": r("that feels", "que se siente", "que parece", "التي تشعر"),
    "שמכיר": r("that knows", "que conoce", "que conhece", "الذي يعرف"),
    "וסאונד": r("and sound", "y sonido", "e som", "وصوت"),
    "וריחות": r("and scents", "y aromas", "e aromas", "وروائح"),
    "וטיפים": r("and tips", "y consejos", "e dicas", "ونصائح"),
    "ומשתלה": r("and a nursery", "y un vivero", "e um viveiro", "ومشتل"),
    "וקמפינג": r("and camping", "y camping", "e camping", "وتخييم"),
    "מדידות": r("measurements", "medidas", "medições", "قياسات"),
    "שמרגישים": r("that feel", "que se sienten", "que sentem", "يشعرون"),
    "מדויקים": r("precise", "precisos", "precisos", "دقيقة"),
    "שמגיעים": r("that arrive", "que llegan", "que chegam", "الذين يصلون"),
    "בסופי": r("on weekend", "en fines de", "em fins de", "في نهايات"),
    "שמחזיקים": r("that hold", "que sostienen", "que sustentam", "الذين يمسكون"),
    "הנכון": r("the right one", "el correcto", "o certo", "الصحيح"),
    "וגימור": r("and finishing", "y acabado", "e acabamento", "وتشطيب"),
    "בשמם": r("in their name", "en su nombre", "em nome deles", "باسمهم"),
    "ושומר": r("and keeps", "y guarda", "e guarda", "ويحفظ"),
    "תחומי": r("fields of", "ámbitos de", "áreas de", "مجالات"),
    "עונתיים": r("seasonal", "de temporada", "sazonais", "موسمية"),
    "עירונית": r("urban", "urbana", "urbana", "حضرية"),
    "רפואת": r("medicine of", "medicina de", "medicina de", "طب"),
    "לוקבוק": r("lookbook", "lookbook", "lookbook", "لوك بوك"),
    "לוקים": r("looks", "looks", "looks", "إطلالات"),
    "לצוותים": r("for teams", "para equipos", "para equipes", "للفرق"),
    "לבחירת": r("for choosing", "para elegir", "para escolher", "لاختيار"),
}
