"""Exact translations for built-in website template descriptions."""


def r(en, es, pt, ar):
    return {"en": en, "es": es, "pt-BR": pt, "ar": ar}


EXACT = {
    "תבנית רב-עמודית עם סקשנים מורכבים, פינות ישרות, תנועה וכניסות — מוכנה לעריכה מלאה בעורך.": r(
        "A multi-page template with complex sections, square corners, motion, and entrances — ready for full editing in the editor.",
        "Plantilla de varias páginas con secciones complejas, esquinas rectas, movimiento y entradas, lista para edición completa.",
        "Modelo de várias páginas com seções complexas, cantos retos, movimento e entradas — pronto para edição completa.",
        "قالب متعدد الصفحات بأقسام مركّبة وزوايا مستقيمة وحركة ودخولات — جاهز للتحرير الكامل في المحرر.",
    ),
    "תבנית אדריכלות נוף וגינון בעברית: צילום בוטני מלא, קווים ישרים, זית ואבן — פריסה עריכתית בלי כרטיסים.": r(
        "A Hebrew landscape and garden architecture template: full botanical photography, straight lines, olive and stone — an editorial layout without cards.",
        "Plantilla hebrea de paisaje y jardinería: foto botánica, líneas rectas, olivo y piedra, maquetación editorial sin tarjetas.",
        "Modelo hebraico de paisagismo: foto botânica, linhas retas, oliveira e pedra — layout editorial sem cartões.",
        "قالب عمارة حدائق بالعبرية: تصوير نباتي كامل وخطوط مستقيمة وزيتون وحجر — تخطيط تحريري بلا بطاقات.",
    ),
    "תבנית diagonal: הירo מפוצל אלכסוני, כרטיסים על grid skewed וטופס קשר על פanel זווית.": r(
        "A diagonal template: a split angled hero, cards on a skewed grid, and a contact form on an angled panel.",
        "Plantilla diagonal: hero partido en ángulo, tarjetas en una grid sesgada y formulario en un panel angulado.",
        "Modelo diagonal: hero partido em ângulo, cartões em grade inclinada e formulário num painel angular.",
        "قالب قطري: بطل مقسوم بزاوية وبطاقات على شبكة مائلة ونموذج تواصل على لوحة زاوية.",
    ),
    "תבנית שכירת יאכטות: הירו מינימלי עם קו אופק ripple, נקודות מסלול, מפרטי כלי שייט ופס הזמנה — אפקט ripple-expand.": r(
        "A yacht-charter template: a minimal hero with a ripple horizon, route points, vessel specs, and a booking bar — ripple-expand effect.",
        "Plantilla de chárter de yates: hero mínimo con horizonte ripple, puntos de ruta, fichas de embarcaciones y barra de reserva.",
        "Modelo de aluguel de iates: hero mínimo com horizonte ripple, pontos de rota, fichas de embarcações e barra de reserva.",
        "قالب تأجير يخوت: بطل بسيط مع أفق متموج ونقاط مسار ومواصفات القوارب وشريط حجز — تأثير ripple-expand.",
    ),
    "תבנית מאפייה: שכבות בצק כמו למינציה, מדפי מאפים אופקיים, אדים עדינים וטופס הזמנה בסגנון תג מחיר — חמימות של תנור בבוקר.": r(
        "A bakery template: laminated dough layers, horizontal pastry shelves, soft steam, and a price-tag order form — morning-oven warmth.",
        "Plantilla de panadería: capas de masa, estantes de bollería, vapor suave y un formulario tipo etiqueta de precio.",
        "Modelo de padaria: camadas de massa, prateleiras de pães, vapor suave e formulário em estilo etiqueta.",
        "قالب مخبز: طبقات عجين كالتصفيح ورفوف معجنات أفقية وبخار لطيف ونموذج طلب بطابع بطاقة سعر — دفء فرن الصباح.",
    ),
    "תבנית בrutalist: בלוקים מוערמים עם stagger climb, אינדקס נכסים ממוספר ופס קשר טיפוגרפי נועז.": r(
        "A brutalist template: stacked blocks with a stagger climb, a numbered property index, and a bold typographic contact bar.",
        "Plantilla brutalista: bloques apilados con stagger climb, índice numerado de inmuebles y una franja de contacto tipográfica.",
        "Modelo brutalista: blocos empilhados com stagger climb, índice numerado de imóveis e faixa de contato tipográfica.",
        "قالب بروتالي: كتل مرصوصة مع stagger climb وفهرس عقارات مرقّم وشريط تواصل طباعي جريء.",
    ),
    "תבנית קולנועית: הירו מסך מלא, טיקר נכסים נגלל, כרטיסי נכס עם זום, צוות סוכנים וסטטיסטיקות מונפשות.": r(
        "A cinematic template: a full-screen hero, a scrolling property ticker, zooming listing cards, an agent team, and animated stats.",
        "Plantilla cinematográfica: hero a pantalla completa, ticker de inmuebles, tarjetas con zoom, equipo de agentes y estadísticas animadas.",
        "Modelo cinematográfico: hero em tela cheia, ticker de imóveis, cartões com zoom, equipe de corretores e estatísticas animadas.",
        "قالب سينمائي: بطل بملء الشاشة وشريط عقارات متحرّك وبطاقات عقار مع تكبير وفريق وسطاء وإحصاءات متحركة.",
    ),
    "תבנית בראנץ׳ שמשית: הירו עם קרני שמש מסתובבות, גלריית פולארויד מסובבת, לוח סוף-שבוע כרשת וטופס גלויה — תנועה קלילה ושמחה.": r(
        "A sunny brunch template: a hero with rotating sun rays, a tilted Polaroid gallery, a weekend grid, and a postcard form — light, happy motion.",
        "Plantilla de brunch soleado: hero con rayos, galería Polaroid, parrilla de fin de semana y formulario postal.",
        "Modelo de brunch ensolarado: hero com raios, galeria Polaroid, grade de fim de semana e formulário postal.",
        "قالب برانش مشمس: بطل بأشعة شمس دوّارة ومعرض بولارويد مائل ولوحة عطلة كشبكة ونموذج بطاقة بريدية — حركة خفيفة ومرحة.",
    ),
    "תבנית בורגר: שכבות סמאש, לחמנייה זהובה וטופס הזמנה כבד — גריל אמריקאי ישיר.": r(
        "A burger template: smash layers, a golden bun, and a heavy order form — straight-up American grill.",
        "Plantilla de hamburguesas: capas smash, pan dorado y un formulario contundente: grill americano directo.",
        "Modelo de hambúrguer: camadas smash, pão dourado e formulário pesado — grill americano direto.",
        "قالب برغر: طبقات سماش وخبزة ذهبية ونموذج طلب ثقيل — شواء أمريكي مباشر.",
    ),
    "תבנית בית קלייה וקפה בעברית: טיפוגרפיה ענקית, רצועות צילום חדות, תפריט כרשימה טיפוגרפית — בלי כרטיסים.": r(
        "A Hebrew roastery and coffee template: giant type, sharp photo strips, a typographic list menu — no cards.",
        "Plantilla hebrea de tueste y café: tipografía enorme, tiras fotográficas y un menú-lista, sin tarjetas.",
        "Modelo hebraico de torrefação e café: tipografia enorme, faixas fotográficas e cardápio em lista — sem cartões.",
        "قالب محمصة وقهوة بالعبرية: طباعة ضخمة وأشرطة صور حادة وقائمة كنص طباعي — بلا بطاقات.",
    ),
    "תבנית סייבר: אסתטיקת טרמינל, ירוק מטריקס, 6 עמודים עם אנימציות סריקה וכניסות.": r(
        "A cyber template: terminal aesthetics, matrix green, 6 pages with scan animations and entrances.",
        "Plantilla ciber: estética de terminal, verde matrix, 6 páginas con animaciones de escaneo.",
        "Modelo cyber: estética de terminal, verde matrix, 6 páginas com animações de varredura.",
        "قالب سيبراني: جمالية طرفية وأخضر ماتريكس و6 صفحات مع حركات مسح ودخول.",
    ),
    "תבנית בית ספר לצלילה: הירו תת-ימי עם בועות צפות, כרטיסי זכוכית, ציר עומק וטופס טבילה — אפקט shimmer ייחודי.": r(
        "A dive-school template: an underwater hero with floating bubbles, glass cards, a depth axis, and a splash form — a unique shimmer.",
        "Plantilla de escuela de buceo: hero submarino, burbujas, tarjetas de cristal, eje de profundidad y formulario de inmersión.",
        "Modelo de escola de mergulho: hero submerso, bolhas, cartões de vidro, eixo de profundidade e formulário de imersão.",
        "قالب مدرسة غوص: بطل تحت الماء وفقاعات عائمة وبطاقات زجاج ومحور عمق ونموذج غطس — تأثير لمعان فريد.",
    ),
    "תבנית פיצרייה: הירו באלכסון עם פיצה מסתובבת, תפריט כבלוקי משולשים, רצועת חום תנור וטופס כרטיס הזמנה — אבק קמח ואנימציית stretch.": r(
        "A pizzeria template: a diagonal hero with a spinning pizza, a triangle-block menu, an oven-heat strip, and a ticket order form — flour dust and a stretch animation. Crustora.",
        "Plantilla de pizzería: hero en diagonal con pizza giratoria, menú en bloques triangulares, franja de horno y formulario tipo ticket.",
        "Modelo de pizzaria: hero em diagonal com pizza girando, cardápio em blocos triangulares, faixa de forno e formulário tipo ticket.",
        "قالب بيتزا: بطل قطري مع بيتزا دوّارة وقائمة ككتل مثلثة وشريط حرارة الفرن ونموذج بطاقة طلب — غبار طحين وحركة stretch. Crustora.",
    ),
    "תבנית פטיסרי: גבישי סוכר, קינוחים גיאומטריים וטופס הזמנה אלגנטי — מעבדת מתיקות.": r(
        "A patisserie template: sugar crystals, geometric desserts, and an elegant order form — a sweetness lab.",
        "Plantilla de pastelería: cristales de azúcar, postres geométricos y un formulario elegante.",
        "Modelo de patisserie: cristais de açúcar, sobremesas geométricas e formulário elegante.",
        "قالب حلويات: بلورات سكر وحلويات هندسية ونموذج طلب أنيق — مختبر حلاوة.",
    ),
    "תבנית דימ סאם: סלי במבוק מאודים, ענני קיטור וטופס הזמנה עגול — סעודת בוקר אסייתית.": r(
        "A dim-sum template: steaming bamboo baskets, steam clouds, and a round order form — an Asian morning meal.",
        "Plantilla de dim sum: cestas de bambú al vapor, nubes de vapor y un formulario redondo.",
        "Modelo de dim sum: cestos de bambu no vapor, nuvens de vapor e formulário redondo.",
        "قالب ديم سام: سلال خيزران مطهوّة وغيم بخار ونموذج طلب دائري — فطور آسيوي.",
    ),
    "תבנית Citadel — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Citadel template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Citadel: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Citadel — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Citadel — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Framehaus — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Framehaus template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Framehaus: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Framehaus — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Framehaus — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Gridline — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Gridline template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Gridline: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Gridline — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Gridline — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Horizon — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Horizon template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Horizon: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Horizon — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Horizon — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Kinetic — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Kinetic template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Kinetic: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Kinetic — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Kinetic — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Ledger — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Ledger template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Ledger: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Ledger — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Ledger — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Monolith — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Monolith template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Monolith: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Monolith — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Monolith — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Prism — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Prism template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Prism: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Prism — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Prism — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Steelworks — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Steelworks template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Steelworks: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Steelworks — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Steelworks — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית Vertex — אתר רב-עמודי מקצועי עם עיצוב מלבני ותנועה.": r(
        "Vertex template — a professional multi-page site with rectangular design and motion.",
        "Plantilla Vertex: un sitio profesional de varias páginas con diseño rectangular y movimiento.",
        "Modelo Vertex — um site profissional de várias páginas com design retangular e movimento.",
        "قالب Vertex — موقع متعدد الصفحات احترافي بتصميم مستطيل وحركة.",
    ),
    "תבנית אפייה Pro": r("Baking Pro template", "Plantilla Baking Pro", "Modelo Baking Pro", "قالب خبز Pro"),
    "תבנית אפייה Pro מתוך קטלוג Panora — מטבח וכלי בישול.": r(
        "Baking Pro template from the Panora catalog — kitchen and cookware.",
        "Plantilla Baking Pro del catálogo Panora: cocina y utensilios.",
        "Modelo Baking Pro do catálogo Panora — cozinha e utensílios.",
        "قالب خبز Pro من كتالوج Panora — مطبخ وأدوات طبخ.",
    ),
    "תבנית לקוסמטיקה ותיאום תורים עם חוויית פרימיום, גלריה וטופס תור.": r(
        "A cosmetics and booking template with a premium experience, gallery, and appointment form.",
        "Plantilla de cosmética y citas con experiencia premium, galería y formulario.",
        "Modelo de cosmética e agendamento com experiência premium, galeria e formulário.",
        "قالب تجميل وحجز مواعيد مع تجربة فاخرة ومعرض ونموذج موعد.",
    ),
    "תבנית IDO לקוסמטיקה ותיאום תורים עם חוויית פרימיום, גלריה, טיפולים וטופס קביעת תור.": r(
        "The IDO cosmetics and booking template with a premium experience, gallery, treatments, and an appointment form.",
        "Plantilla IDO de cosmética y citas con experiencia premium, galería, tratamientos y formulario.",
        "Modelo IDO de cosmética e agendamento com experiência premium, galeria, tratamentos e formulário.",
        "قالب IDO للتجميل وحجز المواعيد مع تجربة فاخرة ومعرض وعلاجات ونموذج حجز.",
    ),
    "תבנית פרימיום לעסקים ושירותים עם Hero דרמטי, תמונה נפתחת לצדדים, שירותים, גלריה וטופס יצירת קשר.": r(
        "A premium business-and-services template with a dramatic hero, a photo that opens to the sides, services, gallery, and a contact form.",
        "Plantilla premium de negocios con hero dramático, foto que se abre a los lados, servicios, galería y formulario.",
        "Modelo premium de negócios com hero dramático, foto que se abre para os lados, serviços, galeria e formulário.",
        "قالب فاخر للأعمال والخدمات مع بطل درامي وصورة تنفتح جانبياً وخدمات ومعرض ونموذج تواصل.",
    ),
    "תבנית יוקרתית לעסקים ושירותים עם חוויית תיאום תורים ונוכחות מקצועית.": r(
        "A luxury business-and-services template with appointment booking and a professional presence.",
        "Plantilla de lujo para negocios con reserva de citas y presencia profesional.",
        "Modelo de luxo para negócios com agendamento e presença profissional.",
        "قالب فاخر للأعمال والخدمات مع تجربة حجز مواعيد وحضور مهني.",
    ),
    "תבנית עסקית נקייה עם הירו, שירותים, פרויקטים, תהליך עבודה, המלצות ויצירת קשר.": r(
        "A clean business template with a hero, services, projects, process, testimonials, and contact.",
        "Plantilla de negocio limpia con hero, servicios, proyectos, proceso, testimonios y contacto.",
        "Modelo de negócio limpo com hero, serviços, projetos, processo, depoimentos e contato.",
        "قالب أعمال نظيف مع بطل وخدمات ومشاريع وعملية عمل وتوصيات وتواصل.",
    ),
    "תבנית אתר עסקי נקייה, מקצועית ומודרנית לסוכנויות, יועצים, נותני שירותים ועסקים שרוצים נוכחות יוקרתית וברורה.": r(
        "A clean, professional, modern business-site template for agencies, consultants, and service businesses that want a clear luxury presence.",
        "Plantilla de sitio de negocio limpia y moderna para agencias, consultores y negocios que quieren una presencia clara y de lujo.",
        "Modelo de site de negócio limpo e moderno para agências, consultores e negócios que querem presença clara e sofisticada.",
        "قالب موقع أعمال نظيف ومهني وحديث للوكالات والمستشارين ومقدّمي الخدمات الذين يريدون حضوراً فاخراً وواضحاً.",
    ),
    "תבנית פרימיום לעסקים שרוצים להציג שירותים, פרויקטים, תהליך עבודה ויצירת קשר בצורה ברורה ומרשימה.": r(
        "A premium template for businesses that want to show services, projects, process, and contact in a clear, impressive way.",
        "Plantilla premium para negocios que quieren mostrar servicios, proyectos, proceso y contacto con claridad.",
        "Modelo premium para negócios que querem mostrar serviços, projetos, processo e contato com clareza.",
        "قالب فاخر للأعمال التي تريد عرض الخدمات والمشاريع وعملية العمل والتواصل بوضوح وإبهار.",
    ),
    "תבנית פרימיום לקליניקות, מטפלים, יועצים וקואצ׳רים שרוצים אתר מרגיע אבל לא משעמם — עם חוויית משתמש ברורה, שכבות ויזואליות, אמון, שירותים, מחירון ופנייה מהירה.": r(
        "A premium template for clinics, therapists, consultants, and coaches who want a calming site that is not dull — with a clear UX, visual layers, trust, services, pricing, and a fast inquiry.",
        "Plantilla premium para clínicas, terapeutas y coaches que quieren un sitio calmado pero no aburrido, con UX clara, capas visuales, confianza, servicios, precios y consulta rápida.",
        "Modelo premium para clínicas, terapeutas e coaches que querem um site calmo mas não sem graça — UX clara, camadas visuais, confiança, serviços, preços e consulta rápida.",
        "قالب فاخر للعيادات والمعالجين والمستشارين والمدربين الذين يريدون موقعاً هادئاً غير ممل — مع تجربة واضحة وطبقات بصرية وثقة وخدمات وأسعار وتواصل سريع.",
    ),
    "תבנית פרימיום רגועה לקליניקות, מטפלים, יועצים וקואצ׳רים עם אפקטים רכים, אזורי שירותים, מחירון, גלריה, מאמרים וטופס יצירת קשר.": r(
        "A calm premium template for clinics, therapists, consultants, and coaches with soft effects, service areas, pricing, gallery, articles, and a contact form.",
        "Plantilla premium calmada para clínicas y coaches, con efectos suaves, servicios, precios, galería, artículos y formulario.",
        "Modelo premium calmo para clínicas e coaches, com efeitos suaves, serviços, preços, galeria, artigos e formulário.",
        "قالب فاخر هادئ للعيادات والمعالجين والمستشارين والمدربين مع تأثيرات ناعمة ومناطق خدمات وأسعار ومعرض ومقالات ونموذج تواصل.",
    ),
    "תבנית דיגיטלית נועזת עם כרטיסים צפים, סקשנים יצירתיים, טיפוגרפיה חזקה ותנועה פרימיום.": r(
        "A bold digital template with floating cards, creative sections, strong type, and premium motion.",
        "Plantilla digital audaz con tarjetas flotantes, secciones creativas, tipografía fuerte y movimiento premium.",
        "Modelo digital ousado com cartões flutuantes, seções criativas, tipografia forte e movimento premium.",
        "قالب رقمي جريء ببطاقات عائمة وأقسام إبداعية وطباعة قوية وحركة فاخرة.",
    ),
    "תבנית סטודיو דיגיטלית צבעונית ומודרנית בסגנון Virello עם טיפוגרפיה ענקית, תמונות צפות, תנועה עדינה, שירותים, פרויקטים, צוות, תהליך, FAQ ובלוג.": r(
        "A colorful modern digital studio template in the Virello style with giant type, floating images, soft motion, services, projects, team, process, FAQ, and a blog.",
        "Plantilla de estudio digital colorida al estilo Virello: tipografía enorme, fotos flotantes, movimiento suave, servicios, proyectos, equipo, proceso, FAQ y blog.",
        "Modelo de estúdio digital colorido no estilo Virello: tipografia enorme, fotos flutuantes, movimento suave, serviços, projetos, equipe, processo, FAQ e blog.",
        "قالب استوديو رقمي ملون وحديث بأسلوب Virello مع طباعة ضخمة وصور عائمة وحركة لطيفة وخدمات ومشاريع وفريق وعملية وأسئلة شائعة ومدونة.",
    ),
    "תבנית סטודיו דיגיטלית מקורית בסגנון Virello: הירו טיפוגרפי ענק, תמונות צפות, כרטיסי שירות, פרויקטים, צוות, תהליך, FAQ ובלוג.": r(
        "An original digital studio template in the Virello style: a giant type hero, floating images, service cards, projects, team, process, FAQ, and a blog.",
        "Plantilla original de estudio digital al estilo Virello: hero tipográfico, fotos flotantes, tarjetas de servicio, proyectos, equipo, proceso, FAQ y blog.",
        "Modelo original de estúdio digital no estilo Virello: hero tipográfico, fotos flutuantes, cartões de serviço, projetos, equipe, processo, FAQ e blog.",
        "قالب استوديو رقمي أصيل بأسلوب Virello: بطل طباعي ضخم وصور عائمة وبطاقات خدمة ومشاريع وفريق وعملية وأسئلة شائعة ومدونة.",
    ),
    "תבנית פרימיום לסטודיו צילום ווידאו, עם פתיחה קולנועית, טיפוגרפיה גדולה, כרטיסי תמונה, עבודות נבחרות וקריאה לפעולה חזקה.": r(
        "A premium photo-and-video studio template with a cinematic opening, large type, image cards, selected work, and a strong call to action.",
        "Plantilla premium de estudio de foto y vídeo con apertura cinematográfica, tipografía grande, tarjetas de imagen, trabajos y una CTA fuerte.",
        "Modelo premium de estúdio de foto e vídeo com abertura cinematográfica, tipografia grande, cartões de imagem, trabalhos e uma CTA forte.",
        "قالب فاخر لاستوديو تصوير وفيديو مع افتتاح سينمائي وطباعة كبيرة وبطاقات صور وأعمال مختارة ودعوة قوية للإجراء.",
    ),
    "תבנית סטודיו קולנועית לצלמים, יוצרי וידאו, סטודיו קריאייטיב ומותגים שרוצים אתר פרימיום עם נראות חזקה, תנועה, גלריית עבודות ועמודי תוכן מלאים.": r(
        "A cinematic studio template for photographers, video creators, creative studios, and brands that want a premium site with a strong look, motion, a work gallery, and full content pages.",
        "Plantilla cinematográfica para fotógrafos, vídeo y marcas que quieren un sitio premium con presencia, movimiento, galería y páginas de contenido.",
        "Modelo cinematográfico para fotógrafos, vídeo e marcas que querem um site premium com presença, movimento, galeria e páginas de conteúdo.",
        "قالب استوديو سينمائي للمصورين وصنّاع الفيديو والاستوديوهات الإبداعية والعلامات التي تريد موقعاً فاخراً بحضور قوي وحركة ومعرض أعمال وصفحات محتوى كاملة.",
    ),
    "תבנית מסעדת שף פרימיום עם הירו כהה ואלגנטי, סיפור המסעדה, תפריט עונתי, חוויית סועד, גלריה, ביקורות והזמנת שולחן.": r(
        "A premium chef-restaurant template with a dark elegant hero, the restaurant story, a seasonal menu, the guest experience, gallery, reviews, and table booking.",
        "Plantilla premium de restaurante de chef con hero oscuro, historia, menú de temporada, experiencia, galería, reseñas y reserva.",
        "Modelo premium de restaurante de chef com hero escuro, história, cardápio sazonal, experiência, galeria, avaliações e reserva.",
        "قالب مطعم شيف فاخر مع بطل داكن وأنيق وقصة المطعم وقائمة موسمية وتجربة الضيف ومعرض ومراجعات وحجز طاولة.",
    ),
    "תבנית מסעדת שף פרימיום בסגנון fine dining: הירו קולנועי כהה, תפריט עונתי, חוויית סועד, גלריה, ביקורות והזמנת שולחן.": r(
        "A premium chef-restaurant template in a fine-dining style: a dark cinematic hero, seasonal menu, guest experience, gallery, reviews, and table booking.",
        "Plantilla premium de fine dining: hero cinematográfico oscuro, menú de temporada, experiencia, galería, reseñas y reserva.",
        "Modelo premium de fine dining: hero cinematográfico escuro, cardápio sazonal, experiência, galeria, avaliações e reserva.",
        "قالب مطعم شيف فاخر بأسلوب fine dining: بطل سينمائي داكن وقائمة موسمية وتجربة ضيف ومعرض ومراجعات وحجز طاولة.",
    ),
    "תבנית פרימיום לסוכני נדל״ן, יזמים ופרויקטים שרוצים לשדר יוקרה, סדר ואמון — עם עיצוב נקי, תמונות גדולות וקריאה ברורה לפנייה.": r(
        "A premium template for real-estate agents, developers, and projects that want to signal luxury, order, and trust — with a clean design, large photos, and a clear inquiry call.",
        "Plantilla premium para agentes e inmobiliarias que quieren lujo, orden y confianza: diseño limpio, fotos grandes y una llamada clara.",
        "Modelo premium para corretores e incorporadoras que querem luxo, ordem e confiança — design limpo, fotos grandes e chamada clara.",
        "قالب فاخر لوسطاء العقارات والمطوّرين والمشاريع التي تريد أن تبث الفخامة والترتيب والثقة — بتصميم نظيف وصور كبيرة ودعوة واضحة للتواصل.",
    ),
    "תבנית יוקרתית לסוכן נדל״ן שמעדיף לבנות אמון, להציג נכסים נבחרים ולייצר פניות איכותיות — בלי לפרסם מחירי בתים באתר.": r(
        "A luxury template for an agent who prefers to build trust, show selected listings, and generate quality inquiries — without publishing home prices on the site.",
        "Plantilla de lujo para un agente que prefiere generar confianza, mostrar inmuebles selectos y consultas de calidad, sin publicar precios.",
        "Modelo de luxo para um corretor que prefere gerar confiança, mostrar imóveis selecionados e consultas de qualidade — sem publicar preços.",
        "قالب فاخر لوسيط يفضّل بناء الثقة وعرض عقارات مختارة وتوليد استفسارات نوعية — دون نشر أسعار المنازل في الموقع.",
    ),
    "תבנית מקצועית בעברית לפלטפורמת ידע ופיד למפתחים: הירו עם כרטיסי פיד, קהילה, יכולות, תמחור, ביקורות וטופס הדגמה.": r(
        "A professional Hebrew template for a developer knowledge-and-feed platform: a hero with feed cards, community, capabilities, pricing, reviews, and a demo form.",
        "Plantilla hebrea profesional para una plataforma de conocimiento: hero con tarjetas de feed, comunidad, capacidades, precios, reseñas y demo.",
        "Modelo hebraico profissional para uma plataforma de conhecimento: hero com cartões de feed, comunidade, capacidades, preços, avaliações e demo.",
        "قالب مهني بالعبرية لمنصة معرفة وتغذية للمطوّرين: بطل ببطاقات تغذية ومجتمع وقدرات وتسعير ومراجعات ونموذج عرض.",
    ),
    "תבנית בעברית בהשראת פלטפורמות ידע למפתחים: פיד מותאם, קהילה מקצועית, תמחור שקוף ועיצוב כהה נקי.": r(
        "A Hebrew template inspired by developer knowledge platforms: a tailored feed, a professional community, transparent pricing, and a clean dark design.",
        "Plantilla hebrea inspirada en plataformas para desarrolladores: feed a medida, comunidad, precios transparentes y un diseño oscuro limpio.",
        "Modelo hebraico inspirado em plataformas para desenvolvedores: feed sob medida, comunidade, preços transparentes e design escuro limpo.",
        "قالب بالعبرية مستوحى من منصات معرفة المطوّرين: تغذية مخصّصة ومجتمع مهني وتسعير شفاف وتصميم داكن نظيف.",
    ),
    "תבנית פרימיום למשרד עורכי דין וייעוץ פיננסי עם הירו אלגנטי, ערכים, תחומי עיסוק, תהליך עבודה, הצלחות, צוות וטופס פנייה.": r(
        "A premium law-and-finance template with an elegant hero, values, practice areas, process, successes, team, and an inquiry form.",
        "Plantilla premium para despacho y asesoría financiera: hero elegante, valores, áreas, proceso, éxitos, equipo y formulario.",
        "Modelo premium para escritório e consultoria financeira: hero elegante, valores, áreas, processo, sucessos, equipe e formulário.",
        "قالب فاخر لمكتب محاماة واستشارة مالية مع بطل أنيق وقيم ومجالات عمل وعملية ونجاحات وفريق ونموذج تواصل.",
    ),
    "תבנית פרימיום למשרד עורכי דין וייעוץ פיננסי בסגנון קורפורייט יוקרתי: נייבי וזהב, תחומי עיסוק, הצלחות, צוות וטופס פנייה.": r(
        "A premium law-and-finance template in a luxury corporate style: navy and gold, practice areas, successes, team, and an inquiry form.",
        "Plantilla premium corporativa de lujo para despacho y finanzas: marino y oro, áreas, éxitos, equipo y formulario.",
        "Modelo premium corporativo de luxo para escritório e finanças: marinho e ouro, áreas, sucessos, equipe e formulário.",
        "قالب فاخر لمكتب محاماة واستشارة مالية بأسلوب شركات فخم: كحلي وذهب ومجالات عمل ونجاحات وفريق ونموذج تواصل.",
    ),
    "תבנית פרימיום למרפאת שיניים ובריאות עם הירו נקי, סרגל אמון, טיפולים, מסלול טיפול, צוות רפואי, ביקורות וקביעת תור.": r(
        "A premium dental-and-health template with a clean hero, a trust bar, treatments, a care path, medical team, reviews, and booking.",
        "Plantilla premium de clínica dental: hero limpio, barra de confianza, tratamientos, recorrido, equipo, reseñas y cita.",
        "Modelo premium de clínica odontológica: hero limpo, barra de confiança, tratamentos, percurso, equipe, avaliações e agendamento.",
        "قالب فاخر لعيادة أسنان وصحة مع بطل نظيف وشريط ثقة وعلاجات ومسار علاج وفريق طبي ومراجعات وحجز موعد.",
    ),
    "תבנית פרימיום למרפאת שיניים ובריאות: עיצוב נקי בטורקיז וכחול, טיפולים, צוות רפואי, ביקורות מטופלים וקביעת תור.": r(
        "A premium dental-and-health template: a clean turquoise-and-blue design, treatments, medical team, patient reviews, and booking.",
        "Plantilla premium de clínica dental: diseño limpio en turquesa y azul, tratamientos, equipo, reseñas y cita.",
        "Modelo premium de clínica odontológica: design limpo em turquesa e azul, tratamentos, equipe, avaliações e agendamento.",
        "قالب فاخر لعيادة أسنان وصحة: تصميم نظيف بفيروزي وأزرق وعلاجات وفريق طبي ومراجعات مرضى وحجز موعد.",
    ),
    "תבנית דף נחיתה ל-SaaS / הייטק עם הירו מוצר, לוגואים, גריד יכולות, תהליך, תמחור, ביקורות, שאלות נפוצות וטופס דמו.": r(
        "A SaaS / high-tech landing template with a product hero, logos, a capabilities grid, process, pricing, reviews, FAQ, and a demo form.",
        "Landing de SaaS / high-tech con hero de producto, logos, grid de capacidades, proceso, precios, reseñas, FAQ y demo.",
        "Landing de SaaS / high-tech com hero de produto, logos, grade de capacidades, processo, preços, avaliações, FAQ e demo.",
        "قالب صفحة هبوط لـ SaaS / هاي-تك مع بطل منتج وشعارات وشبكة قدرات وعملية وتسعير ومراجعات وأسئلة شائعة ونموذج عرض.",
    ),
    "תבנית דף נחיתה מודרנית ל-SaaS והייטק: הירו מוצר קולנועי, גריד יכולות, תמחור, ביקורות, FAQ וטופס תיאום דמו.": r(
        "A modern SaaS and high-tech landing: a cinematic product hero, capabilities grid, pricing, reviews, FAQ, and a demo-booking form.",
        "Landing moderna de SaaS: hero cinematográfico, grid de capacidades, precios, reseñas, FAQ y formulario de demo.",
        "Landing moderna de SaaS: hero cinematográfico, grade de capacidades, preços, avaliações, FAQ e formulário de demo.",
        "قالب صفحة هبوط حديث لـ SaaS والهاي-تك: بطل منتج سينمائي وشبكة قدرات وتسعير ومراجعات وأسئلة شائعة ونموذج تنسيق عرض.",
    ),
    "תבנית אופנה / מסחר אלקטרוני פרימיום עם הירו קולאז׳, מגה־מניו, באנרים זזים, רשת מוצרים, ביקורות, יומן, FAQ וניוזלטר.": r(
        "A premium fashion / ecommerce template with a collage hero, mega-menu, moving banners, a product grid, reviews, a journal, FAQ, and a newsletter.",
        "Plantilla premium de moda / ecommerce: hero collage, mega menú, banners, grid de productos, reseñas, diario, FAQ y newsletter.",
        "Modelo premium de moda / e-commerce: hero colagem, mega menu, banners, grade de produtos, avaliações, diário, FAQ e newsletter.",
        "قالب أزياء / تجارة إلكترونية فاخر مع بطل كولاج وقائمة ضخمة ولافتات متحركة وشبكة منتجات ومراجعات ويوميات وأسئلة شائعة ونشرة.",
    ),
    "תבנית אופנה פרימיום בסגנון Astral Threads: הירו קולאז׳, מגה־מניו, באנרים זזים, מוצרים, ביקורות, יומן, FAQ וניוזלטר.": r(
        "A premium fashion template in the Astral Threads style: a collage hero, mega-menu, moving banners, products, reviews, journal, FAQ, and a newsletter.",
        "Plantilla de moda premium al estilo Astral Threads: hero collage, mega menú, banners, productos, reseñas, diario, FAQ y newsletter.",
        "Modelo de moda premium no estilo Astral Threads: hero colagem, mega menu, banners, produtos, avaliações, diário, FAQ e newsletter.",
        "قالب أزياء فاخر بأسلوب Astral Threads: بطل كولاج وقائمة ضخمة ولافتات متحركة ومنتجات ومراجعات ويوميات وأسئلة شائعة ونشرة.",
    ),
    "תבנית סטודיו קריאייטיב / סוכנות עם הירו טיפוגרפי נועז, טקסט רץ, שירותים, תיק עבודות, סטטיסטיקות, ביקורות וטופס בריף.": r(
        "A creative-studio / agency template with a bold type hero, running text, services, portfolio, stats, reviews, and a brief form.",
        "Plantilla de estudio / agencia: hero tipográfico, texto en movimiento, servicios, portafolio, estadísticas, reseñas y brief.",
        "Modelo de estúdio / agência: hero tipográfico, texto em movimento, serviços, portfólio, estatísticas, avaliações e brief.",
        "قالب استوديو إبداعي / وكالة مع بطل طباعي جريء ونص راكض وخدمات ومعرض أعمال وإحصاءات ومراجعات ونموذج موجز.",
    ),
    "תבנית סטודיו קריאייטיב / סוכנות בסגנון עריכה נועז: שחור ולַיים, טיפוגרפיה גדולה, תיק עבודות, שירותים וטופס בריף.": r(
        "A creative-studio / agency template in a bold editorial style: black and lime, large type, portfolio, services, and a brief form.",
        "Plantilla de estudio / agencia editorial: negro y lima, tipografía grande, portafolio, servicios y brief.",
        "Modelo de estúdio / agência editorial: preto e lima, tipografia grande, portfólio, serviços e brief.",
        "قالب استوديو إبداعي / وكالة بأسلوب تحريري جريء: أسود وليم وطباعة كبيرة ومعرض أعمال وخدمات ونموذج موجز.",
    ),
    "תבנית וילות יוקרתית בשחור ושמפניה: כותרת קולנועית ממורכזת, תמונת 21:9, וילה מרכזית ענקית, רשימת וילות בשורות דקות ועקרונות אדריכלות אלגנטיים.": r(
        "A luxury villas template in black and champagne: a centered cinematic title, a 21:9 image, a giant central villa, thin villa rows, and elegant architecture principles.",
        "Plantilla de villas de lujo en negro y champán: título cinematográfico, imagen 21:9, villa central, filas finas y principios de arquitectura.",
        "Modelo de vilas de luxo em preto e champanhe: título cinematográfico, imagem 21:9, vila central, linhas finas e princípios de arquitetura.",
        "قالب فلل فاخر بالأسود والشامبانيا: عنوان سينمائي في الوسط وصورة 21:9 وفيلا مركزية ضخمة وقائمة فلل بصفوف رفيعة ومبادئ عمارة أنيقة.",
    ),
    "תבנית וילות יוקרתית עם הירו קולנועי, וילה מרכזית ענקית, שורות נכסים דקות וטופס פרטי ממורכז.": r(
        "A luxury villas template with a cinematic hero, a giant central villa, thin listing rows, and a centered private form.",
        "Plantilla de villas de lujo con hero cinematográfico, villa central, filas finas y un formulario privado centrado.",
        "Modelo de vilas de luxo com hero cinematográfico, vila central, linhas finas e formulário privado centralizado.",
        "قالب فلل فاخر مع بطل سينمائي وفيلا مركزية ضخمة وصفوف عقارات رفيعة ونموذج خاص في الوسط.",
    ),
    "תבנית בוטיק שקטה: הירו ציטוט גדול עם נכס מוביל, שלושה נכסים בלבד בערימה מרווחת, גישה כמכתב אישי וטופס קטן לצד פתק.": r(
        "A quiet boutique template: a large-quote hero with a lead listing, only three properties in a spacious stack, access as a personal letter, and a small form beside a note.",
        "Plantilla boutique quieta: hero de cita grande, tres inmuebles en una pila amplia, acceso como carta y un formulario pequeño.",
        "Modelo boutique silencioso: hero de citação grande, três imóveis numa pilha ampla, acesso como carta e um formulário pequeno.",
        "قالب بوتيك هادئ: بطل باقتباس كبير وعقار رائد وثلاثة عقارات فقط في رصّة مريحة ووصول كرسالة شخصية ونموذج صغير بجانب ورقة.",
    ),
    "תבנית בוטיק שקטה עם ציטוט גדול, נכס מוביל, שלושה נכסים מרווחים ומכתב גישה אישי.": r(
        "A quiet boutique template with a large quote, a lead listing, three spacious properties, and a personal access letter.",
        "Plantilla boutique quieta con una cita grande, un inmueble destacado, tres propiedades y una carta de acceso.",
        "Modelo boutique silencioso com uma citação grande, um imóvel destaque, três propriedades e uma carta de acesso.",
        "قالب بوتيك هادئ مع اقتباس كبير وعقار رائد وثلاثة عقارات مريحة ورسالة وصول شخصية.",
    ),
    "תבנית קרקעות ומגרשים בגישת סקר: מספר ענק על רשת מפה, תמונת חלקה משובצת, מפרטי מגרשים בסגנון מגזין והערות תכנון כשולי מסמך.": r(
        "A land-and-lots survey template: a giant number on a map grid, a tiled plot photo, magazine-style lot specs, and planning notes as document margins.",
        "Plantilla de suelos y parcelas: número enorme sobre mapa, foto de parcela, fichas de revista y notas de planeamiento.",
        "Modelo de terrenos e lotes: número enorme sobre mapa, foto de lote, fichas de revista e notas de planejamento.",
        "قالب أراضٍ وقطع بأسلوب مسح: رقم ضخم على شبكة خريطة وصورة قطعة مرصّعة ومواصفات قطع بطابع مجلة وملاحظات تخطيط كهوامش وثيقة.",
    ),
    "תבנית מגרשים עם הירו מספר ענק ורשת מפה, מפרטי חלקות מגזיניים, הערות תכנון ובקשת סקר.": r(
        "A lots template with a giant-number hero and map grid, magazine plot specs, planning notes, and a survey request.",
        "Plantilla de parcelas con hero de número enorme, fichas de revista, notas de planeamiento y solicitud de estudio.",
        "Modelo de lotes com hero de número enorme, fichas de revista, notas de planejamento e pedido de levantamento.",
        "قالب قطع مع بطل رقم ضخم وشبكة خريطة ومواصفات قطع مجلّية وملاحظات تخطيط وطلب مسح.",
    ),
    "תבנית נדל״ן טבעית ליד מים: הירו עם שלושה פסי נוף אופקיים, נכסים כשורות צילום רחבות, רצועת טבע מרובעת ופאנל קשר רגוע בגוון טורקיז.": r(
        "A natural waterside real-estate template: a hero with three horizontal landscape bands, listings as wide photo rows, a square nature strip, and a calm turquoise contact panel.",
        "Plantilla inmobiliaria junto al agua: hero con tres franjas de paisaje, inmuebles en filas anchas, cinta de naturaleza y un panel de contacto turquesa.",
        "Modelo imobiliário à beira d’água: hero com três faixas de paisagem, imóveis em linhas largas, faixa de natureza e painel turquesa.",
        "قالب عقاري طبيعي قرب الماء: بطل بثلاثة أشرطة منظر أفقية وعقارات كصفوف صور عريضة وشريط طبيعة مربع ولوحة تواصل هادئة فيروزية.",
    ),
    "תבנית נדל״ן טבעית ליד מים עם פסי נוף אופקיים, שורות נכסים רחבות ורצועת טבע ייחודית.": r(
        "A natural waterside real-estate template with horizontal landscape bands, wide listing rows, and a distinctive nature strip.",
        "Plantilla inmobiliaria junto al agua con franjas de paisaje, filas anchas y una cinta de naturaleza.",
        "Modelo imobiliário à beira d’água com faixas de paisagem, linhas largas e uma faixa de natureza.",
        "قالب عقاري طبيعي قرب الماء مع أشرطة منظر أفقية وصفوف عقارات عريضة وشريط طبيعة مميز.",
    ),
    "תבנית מגדלים בחצות וציאן: הירו מגדל אנכי עם סימוני קומות, רשימת דירות מטפסת, שורות שירותים בקווי מתאר ורצועת קו רקיע מלאה.": r(
        "A midnight-and-cyan towers template: a vertical tower hero with floor marks, a climbing apartment list, outline service rows, and a full skyline strip.",
        "Plantilla de torres en cian nocturno: hero de torre, lista de pisos, filas de servicios y una franja de skyline.",
        "Modelo de torres em ciano noturno: hero de torre, lista de apartamentos, linhas de serviços e uma faixa de skyline.",
        "قالب أبراج بمنتصف الليل والسيان: بطل برج عمودي مع علامات طوابق وقائمة شقق متسلقة وصفوف خدمات بخطوط محيط وشريط أفق كامل.",
    ),
    "תבנית היי-רייז עם עמוד מגדל אנכי, קומות מטפסות, שורות שירותים חדות ורצועת קו רקיע.": r(
        "A high-rise template with a vertical tower column, climbing floors, sharp service rows, and a skyline strip.",
        "Plantilla high-rise con una columna de torre, plantas que suben, filas de servicios y una franja de skyline.",
        "Modelo high-rise com uma coluna de torre, andares que sobem, linhas de serviços e uma faixa de skyline.",
        "قالب هاي-رايز مع عمود برج عمودي وطوابق متسلقة وصفوف خدمات حادة وشريط أفق.",
    ),
    "תבנית סלון יופי פרימיום בהשראת Shiny: הירו גדול, שירותים, ייעוץ חינמי, סטטיסטיקות, וידאו, מנהלת, המלצות, גלריה, חנות, בלוג ופוטר רחב.": r(
        "A premium beauty-salon template inspired by Shiny: a large hero, services, a free consult, stats, video, the manager, testimonials, gallery, store, blog, and a wide footer.",
        "Plantilla premium de salón inspirada en Shiny: hero grande, servicios, consulta gratis, estadísticas, vídeo, directora, testimonios, galería, tienda, blog y pie amplio.",
        "Modelo premium de salão inspirado em Shiny: hero grande, serviços, consulta grátis, estatísticas, vídeo, gestora, depoimentos, galeria, loja, blog e rodapé amplo.",
        "قالب صالون تجميل فاخر مستوحى من Shiny: بطل كبير وخدمات واستشارة مجانية وإحصاءات وفيديو ومديرة وتوصيات ومعرض ومتجر ومدونة وتذييل عريض.",
    ),
    "תבנית פרימיום למשרדי עורכי דין עם הירו סמכותי, תחומי התמחות, בדיקת תיק, צוות, תיקים, המלצות, מאמרים וטופס ייעוץ.": r(
        "A premium law-office template with an authoritative hero, practice areas, a case review, team, cases, testimonials, articles, and a consult form.",
        "Plantilla premium de despacho: hero de autoridad, áreas, revisión de caso, equipo, casos, testimonios, artículos y consulta.",
        "Modelo premium de escritório: hero de autoridade, áreas, revisão de caso, equipe, casos, depoimentos, artigos e consulta.",
        "قالب فاخر لمكاتب المحاماة مع بطل ذي سلطة ومجالات تخصص وفحص ملف وفريق وقضايا وتوصيات ومقالات ونموذج استشارة.",
    ),
}

