"""Phrase and word fragments for composing leftover template copy."""


def r(en, es, pt, ar):
    return {"en": en, "es": es, "pt-BR": pt, "ar": ar}


FRAGMENTS = {
    "עם": r("with", "con", "com", "مع"),
    "את": r("", "", "", ""),
    "של": r("of", "de", "de", "ل"),
    "על": r("on", "sobre", "sobre", "على"),
    "כדי": r("so that", "para que", "para que", "لكي"),
    "בלי": r("without", "sin", "sem", "بدون"),
    "כמו": r("like", "como", "como", "مثل"),
    "או": r("or", "o", "ou", "أو"),
    "לפי": r("according to", "según", "conforme", "حسب"),
    "לא": r("not", "no", "não", "لا"),
    "בין": r("between", "entre", "entre", "بين"),
    "עד": r("until", "hasta", "até", "حتى"),
    "רק": r("only", "solo", "só", "فقط"),
    "גם": r("also", "también", "também", "أيضاً"),
    "אם": r("if", "si", "se", "إذا"),
    "זה": r("this", "esto", "isso", "هذا"),
    "הוא": r("he", "él", "ele", "هو"),
    "היא": r("she", "ella", "ela", "هي"),
    "הם": r("they", "ellos", "eles", "هم"),
    "לנו": r("for us", "para nosotros", "para nós", "لنا"),
    "לכם": r("for you", "para vosotros", "para vocês", "لكم"),
    "אתם": r("you", "vosotros", "vocês", "أنتم"),
    "דרך": r("through", "a través de", "por", "عبر"),
    "סביב": r("around", "alrededor de", "em torno de", "حول"),
    "מתוך": r("from", "desde", "de", "من"),
    "בכל": r("in every", "en cada", "em cada", "في كل"),
    "לכל": r("for every", "para cada", "para cada", "لكل"),
    "ולא": r("and not", "y no", "e não", "وليس"),
    "שלא": r("that not", "que no", "que não", "الذي لا"),
    "ועד": r("through", "hasta", "até", "وحتى"),
    "מאחורי": r("behind", "detrás de", "atrás de", "خلف"),
    "מתחיל": r("starts", "empieza", "começa", "يبدأ"),
    "זמן": r("time", "tiempo", "tempo", "وقت"),
    "יום": r("day", "día", "dia", "يوم"),
    "תנועה": r("motion", "movimiento", "movimento", "حركة"),
    "המשך": r("follow-up", "seguimiento", "continuidade", "متابعة"),
    "כתובות": r("written", "escritas", "escritas", "مكتوبة"),
    "והמלצות": r("and recommendations", "y recomendaciones", "e recomendações", "وتوصيات"),
    "ועיצוב": r("and design", "y diseño", "e design", "وتصميم"),
    "וטופס": r("and a form", "y un formulario", "e um formulário", "ونموذج"),
    "ותוצאות": r("and results", "y resultados", "e resultados", "ونتائج"),
    "ומדויק": r("and precise", "y preciso", "e preciso", "ودقيق"),
    "ומוצרים": r("and products", "y productos", "e produtos", "ومنتجات"),
    "ואפקטים": r("and effects", "y efectos", "e efeitos", "وتأثيرات"),
    "וחיבור": r("and connection", "y conexión", "e ligação", "واتصال"),
    "חוויית": r("experience of", "experiencia de", "experiência de", "تجربة"),
    "עמודי": r("pages of", "páginas de", "páginas de", "صفحات"),
    "הטיפולים": r("the treatments", "los tratamientos", "os tratamentos", "العلاجات"),
    "העבודה": r("the work", "el trabajo", "o trabalho", "العمل"),
    "האנשים": r("the people", "las personas", "as pessoas", "الناس"),
    "מהשטח": r("from the field", "del terreno", "do campo", "من الميدان"),
    "לשולחן": r("to the table", "a la mesa", "à mesa", "إلى الطاولة"),
    "ללקוח": r("for the client", "para el cliente", "para o cliente", "للعميل"),
    "לצוות": r("for the team", "para el equipo", "para a equipe", "للفريق"),
    "ולהנהלה": r("and for leadership", "y para la dirección", "e para a direção", "وللإدارة"),
    "בפועל": r("in practice", "en la práctica", "na prática", "عملياً"),
    "תקציב": r("budget", "presupuesto", "orçamento", "ميزانية"),
    "ולוחות": r("and boards", "y tableros", "e quadros", "وألواح"),
    "מדורג": r("phased", "por etapas", "em etapas", "متدرج"),
    "מביאים": r("bring", "traemos", "trazemos", "نحضر"),
    "רבעונית": r("quarterly", "trimestral", "trimestral", "ربع سنوية"),
    "שעובדת": r("that works", "que funciona", "que funciona", "تعمل"),
    "מסגרת": r("framework", "marco", "quadro", "إطار"),
    "לתעדוף": r("to prioritize", "para priorizar", "para priorizar", "لترتيب الأولويات"),
    "מהלכים": r("moves", "movimientos", "movimentos", "خطوات"),
    "השפעה": r("impact", "impacto", "impacto", "تأثير"),
    "סימנים": r("signs", "señales", "sinais", "علامات"),
    "מוקדמים": r("early", "tempranos", "precoce", "مبكرة"),
    "כדאי": r("it is worth", "conviene", "vale a pena", "يُستحسن"),
    "לתפוס": r("to catch", "captar", "captar", "للإمساك"),
    "למדנו": r("we learned", "aprendimos", "aprendemos", "تعلّمنا"),
    "מקמפיינים": r("from campaigns", "de campañas", "de campanhas", "من الحملات"),
    "ותהליכים": r("and processes", "y procesos", "e processos", "وعمليات"),
    "שנכשלו": r("that failed", "que fallaron", "que falharam", "فشلت"),
    "מדדי": r("metrics of", "indicadores de", "indicadores de", "مؤشرات"),
    "הצלחה": r("success", "éxito", "sucesso", "نجاح"),
    "שסוכנות": r("that an agency", "que una agencia", "que uma agência", "أن وكالة"),
    "חייבת": r("must", "debe", "deve", "يجب"),
    "הבנת": r("understanding", "comprensión de", "compreensão de", "فهم"),
    "מצב": r("situation", "situación", "situação", "وضع"),
    "יעדים": r("goals", "objetivos", "metas", "أهداف"),
    "ואילוצים": r("and constraints", "y límites", "e restrições", "وقيود"),
    "נראית": r("looks", "se ve", "parece", "تبدو"),
    "נקודות": r("points", "puntos", "pontos", "نقاط"),
    "מבט": r("view", "vista", "vista", "نظرة"),
    "הגשה": r("plating", "emplatado", "empratamento", "تقديم"),
    "סינונים": r("filters", "filtros", "filtros", "تصفيات"),
    "החלטות": r("decisions", "decisiones", "decisões", "قرارات"),
    "שכל": r("that every", "que cada", "que cada", "أن كل"),
    "קו": r("line", "línea", "linha", "خط"),
    "שמחבר": r("that connects", "que conecta", "que liga", "يربط"),
    "המטרה": r("the goal", "el objetivo", "o objetivo", "الهدف"),
    "מ״ר": r("sqm", "m²", "m²", "م²"),
    "פרטית": r("private", "privada", "privada", "خاصة"),
    "כיוון": r("direction", "dirección", "direção", "اتجاه"),
    "יהיה": r("will be", "será", "será", "سيكون"),
    "נראה": r("looks", "parece", "parece", "يبدو"),
    "שמרגיש": r("that feels", "que se siente", "que parece", "يشعر"),
    "מספרים": r("tell", "cuentan", "contam", "يروون"),
    "לחוויה": r("to the experience", "a la experiencia", "à experiência", "للتجربة"),
    "פרוטוקול": r("protocol", "protocolo", "protocolo", "بروتوكول"),
    "שצריך": r("that is needed", "que hace falta", "que é preciso", "المطلوب"),
    "לשדרג": r("to upgrade", "mejorar", "atualizar", "للترقية"),
    "לפנות": r("to inquire", "consultar", "procurar", "للتواصل"),
    "ממשיך": r("continues", "sigue", "continua", "يستمر"),
    "שאלות": r("questions", "preguntas", "perguntas", "أسئلة"),
    "פתיחת": r("opening of", "apertura de", "abertura de", "افتتاح"),
    "רגישויות": r("sensitivities", "sensibilidades", "sensibilidades", "حساسيات"),
    "נבנתה": r("was built", "se construyó", "foi construída", "بُنيت"),
    "צריך": r("needs", "hace falta", "precisa", "يحتاج"),
    "בזמן": r("on time", "a tiempo", "no tempo", "في الوقت"),
    "ספרו": r("tell us", "contad", "contem", "أخبرونا"),
    "נבנה": r("we will build", "construiremos", "construiremos", "سنبني"),
    "חד": r("sharp", "nítido", "nítido", "حاد"),
    "ברורות": r("clear", "claras", "claras", "واضحة"),
    "למי": r("for those who", "para quien", "para quem", "لمن"),
    "מתוך קטלוג": r("from the catalog", "del catálogo", "do catálogo", "من الكتالوج"),
    "תוסף החנות": r("the store plugin", "el plugin de la tienda", "o plugin da loja", "إضافة المتجر"),
    "מתוסף החנות": r("from the store plugin", "del plugin de la tienda", "do plugin da loja", "من إضافة المتجر"),
    "לתוסף החנות": r("to the store plugin", "al plugin de la tienda", "ao plugin da loja", "إلى إضافة المتجر"),
    "אבחון קצר": r("a short assessment", "un diagnóstico breve", "um diagnóstico curto", "تشخيص قصير"),
    "התאמה אישית": r("personal fitting", "ajuste personal", "ajuste pessoal", "ملاءمة شخصية"),
    "עבודה מדויקת": r("precise work", "trabajo preciso", "trabalho preciso", "عمل دقيق"),
    "המלצות המשך": r("aftercare notes", "recomendaciones de seguimiento", "recomendações de continuidade", "توصيات متابعة"),
    "גם אחרי": r("even after", "incluso después de", "mesmo depois de", "حتى بعد"),
    "היציאה מהסטודיו": r("leaving the studio", "salir del estudio", "sair do estúdio", "الخروج من الاستوديو"),
    "שהתוצאה תישאר יפה": r("so the result stays beautiful", "para que el resultado siga bello", "para o resultado continuar bonito", "كي تبقى النتيجة جميلة"),
    "תל אביב": r("Tel Aviv", "Tel Aviv", "Tel Aviv", "تل أبيب"),
    "אתר מלא": r("a full website", "un sitio completo", "um site completo", "موقع كامل"),
    "דף נחיתה": r("landing page", "landing page", "landing page", "صفحة هبوط"),
    "השאירו פרטים": r("leave your details", "deja tus datos", "deixe seus dados", "اتركوا بياناتكم"),
    "ונחזור עם": r("and we will come back with", "y volveremos con", "e voltaremos com", "وسنعود بـ"),
    "שיחה קצרה": r("a short conversation", "una conversación breve", "uma conversa curta", "حديث قصير"),
    "בשיחה קצרה": r("in a short conversation", "en una conversación breve", "numa conversa curta", "في حديث قصير"),
    "ימי עסקים": r("business days", "días laborables", "dias úteis", "أيام عمل"),
    "לכל הארץ": r("nationwide", "a todo el país", "para todo o país", "لكل أنحاء البلاد"),
    "איסוף עצמי": r("pickup", "recogida", "retirada", "استلام ذاتي"),
    "צור קשר": r("contact", "contacto", "contato", "تواصل"),
    "יצירת קשר": r("getting in touch", "ponerse en contacto", "entrar em contato", "التواصل"),
    "שאלות נפוצות": r("FAQ", "preguntas frecuentes", "perguntas frequentes", "الأسئلة الشائعة"),
    "שנות ניסיון": r("years of experience", "años de experiencia", "anos de experiência", "سنوات خبرة"),
    "למה אנחנו": r("why us", "por qué nosotros", "por que nós", "لماذا نحن"),
    "דברו איתנו": r("talk to us", "habla con nosotros", "fale conosco", "تحدثوا معنا"),
    "הסיפור שלנו": r("our story", "nuestra historia", "nossa história", "قصتنا"),
    "תשלום מאובטח": r("secure payment", "pago seguro", "pagamento seguro", "دفع آمن"),
    "משלוח מהיר": r("fast shipping", "envío rápido", "entrega rápida", "شحن سريع"),
    "לפני ואחרי": r("before and after", "antes y después", "antes e depois", "قبل وبعد"),
    "קביעת תור": r("book an appointment", "reservar cita", "agendar horário", "حجز موعد"),
    "שעות פעילות": r("opening hours", "horario", "horário", "ساعات العمل"),
    "שליחת בקשה": r("send a request", "enviar solicitud", "enviar pedido", "إرسال طلب"),
    "שליחת פנייה": r("send an inquiry", "enviar consulta", "enviar consulta", "إرسال استفسار"),
    "תיאום תורים": r("appointment booking", "reserva de citas", "agendamento", "تنسيق مواعيد"),
    "מועדון לקוחות": r("customer club", "club de clientes", "clube de clientes", "نادي العملاء"),
    "סקשן חדש": r("new section", "nueva sección", "nova seção", "قسم جديد"),
    "עמוד ריק": r("blank page", "página en blanco", "página em branco", "صفحة فارغة"),
    "דף הבית": r("home page", "página de inicio", "página inicial", "الصفحة الرئيسية"),
    "סל קניות": r("shopping cart", "carrito", "carrinho", "سلة التسوق"),
    "החל אתר מוכן": r("apply a ready website", "aplicar un sitio listo", "aplicar um site pronto", "تطبيق موقع جاهز"),
    "חוויית קנייה": r("shopping experience", "experiencia de compra", "experiência de compra", "تجربة تسوق"),
    "חוויית משתמש": r("user experience", "experiencia de usuario", "experiência do usuário", "تجربة مستخدم"),
    "קריאה לפעולה": r("call to action", "llamada a la acción", "chamada para ação", "دعوة لاتخاذ إجراء"),
    "תיק עבודות": r("portfolio", "portafolio", "portfólio", "معرض أعمال"),
    "לוחות זמנים": r("timelines", "calendarios", "cronogramas", "جداول زمنية"),
    "מפת דרכים": r("roadmap", "hoja de ruta", "mapa do caminho", "خارطة طريق"),
    "שיחת ייעוץ": r("consulting call", "llamada de consulta", "chamada de consultoria", "مكالمة استشارة"),
    "לשיחת ייעוץ": r("to a consulting call", "a una llamada de consulta", "para uma chamada de consultoria", "لمكالمة استشارة"),
    "שיחת היכרות": r("intro call", "llamada de presentación", "chamada de apresentação", "مكالمة تعارف"),
    "ניהול החנות": r("store management", "gestión de la tienda", "gestão da loja", "إدارة المتجر"),
    "עמוד החנות": r("the store page", "la página de la tienda", "a página da loja", "صفحة المتجر"),
    "לעמוד החנות": r("to the store page", "a la página de la tienda", "para a página da loja", "إلى صفحة المتجر"),
    "מדיניות ההחזרות": r("the returns policy", "la política de devoluciones", "a política de devoluções", "سياسة الإرجاع"),
    "מדיניות הביטול": r("the cancellation policy", "la política de cancelación", "a política de cancelamento", "سياسة الإلغاء"),
    "יצירת הקשר": r("contact", "el contacto", "o contato", "التواصل"),
    "עמוד יצירת הקשר": r("the contact page", "la página de contacto", "a página de contato", "صفحة التواصل"),
    "הגעות חדשות": r("new arrivals", "novedades", "novidades", "وصولات جديدة"),
    "סינון לפי קטגוריה": r("filter by category", "filtrar por categoría", "filtrar por categoria", "التصفية حسب الفئة"),
    "בלי כרטיסים": r("without cards", "sin tarjetas", "sem cartões", "بلا بطاقات"),
    "בלי כרטיסיות": r("without cards", "sin tarjetas", "sem cartões", "بلا بطاقات"),
    "פינות ישרות": r("square corners", "esquinas rectas", "cantos retos", "زوايا مستقيمة"),
    "עיצוב מלבני": r("rectangular design", "diseño rectangular", "design retangular", "تصميم مستطيل"),
    "אתר רב-עמודי": r("a multi-page website", "un sitio de varias páginas", "um site de várias páginas", "موقع متعدد الصفحات"),
    "מוכנה לעריכה מלאה": r("ready for full editing", "lista para edición completa", "pronta para edição completa", "جاهزة للتحرير الكامل"),
    "בעורך": r("in the editor", "en el editor", "no editor", "في المحرر"),
    "עם תנועה": r("with motion", "con movimiento", "com movimento", "مع حركة"),
    "וכניסות": r("and entrances", "y entradas", "e entradas", "ودخولات"),
    "סקשנים מורכבים": r("complex sections", "secciones complejas", "seções complexas", "أقسام مركّبة"),
    "תבנית רב-עמודית": r("A multi-page template", "Una plantilla de varias páginas", "Um modelo de várias páginas", "قالب متعدد الصفحات"),
    "תבנית פרימיום": r("A premium template", "Una plantilla premium", "Um modelo premium", "قالب فاخر"),
    "תבנית מקצועית": r("A professional template", "Una plantilla profesional", "Um modelo profissional", "قالب احترافي"),
    "תבנית יוקרתית": r("A luxury template", "Una plantilla de lujo", "Um modelo de luxo", "قالب فاخر"),
    "תבנית בוטיק": r("A boutique template", "Una plantilla boutique", "Um modelo boutique", "قالب بوتيك"),
    "תבנית סטודיו": r("A studio template", "Una plantilla de estudio", "Um modelo de estúdio", "قالب استوديو"),
    "תבנית מסעדה": r("A restaurant template", "Una plantilla de restaurante", "Um modelo de restaurante", "قالب مطعم"),
    "תבנית דף נחיתה": r("A landing-page template", "Una plantilla de landing", "Um modelo de landing", "قالب صفحة هبوط"),
    "תבנית נדל״ן": r("A real-estate template", "Una plantilla inmobiliaria", "Um modelo imobiliário", "قالب عقاري"),
    "תבנית אופנה": r("A fashion template", "Una plantilla de moda", "Um modelo de moda", "قالب أزياء"),
    "תבנית עסקית": r("A business template", "Una plantilla de negocio", "Um modelo de negócio", "قالب أعمال"),
    "תבנית דיגיטלית": r("A digital template", "Una plantilla digital", "Um modelo digital", "قالب رقمي"),
    "תבנית בעברית": r("A Hebrew template", "Una plantilla en hebreo", "Um modelo em hebraico", "قالب بالعبرية"),
    "תבנית": r("Template", "Plantilla", "Modelo", "قالب"),
    "מוצר אביזרים מתוך קטלוג": r("Accessories product from the catalog", "Producto de accesorios del catálogo", "Produto de acessórios do catálogo", "منتج إكسسوارات من الكتالوج"),
    "מוצר דקור מתוך קטלוג": r("Decor product from the catalog", "Producto de decoración del catálogo", "Produto de decoração do catálogo", "منتج ديكور من الكتالوج"),
    "כולל אבחון": r("includes an assessment", "incluye diagnóstico", "inclui diagnóstico", "يشمل تشخيصاً"),
    "המלצות המשך כתובות": r("written aftercare notes", "recomendaciones de seguimiento por escrito", "recomendações de continuidade por escrito", "توصيات متابعة مكتوبة"),
    "מהסטודיו": r("from the studio", "del estudio", "do estúdio", "من الاستوديو"),
    "מאחורי הקלעים": r("behind the scenes", "entre bastidores", "bastidores", "خلف الكواليس"),
    "קריאה לפעולה חזקה": r("a strong call to action", "una llamada a la acción fuerte", "uma chamada forte", "دعوة قوية للإجراء"),
    "טופס יצירת קשר": r("contact form", "formulario de contacto", "formulário de contato", "نموذج تواصل"),
    "טופס קביעת תור": r("appointment form", "formulario de cita", "formulário de horário", "نموذج حجز موعد"),
    "טופס הזמנה": r("order form", "formulario de pedido", "formulário de pedido", "نموذج طلب"),
    "טופס ייעוץ": r("consulting form", "formulario de consulta", "formulário de consultoria", "نموذج استشارة"),
    "טופס פנייה": r("inquiry form", "formulario de consulta", "formulário de consulta", "نموذج استفسار"),
    "טופס דמו": r("demo form", "formulario de demo", "formulário de demo", "نموذج تجريبي"),
    "קביעת תור": r("booking an appointment", "reserva de cita", "agendamento", "حجز موعد"),
    "הזמנת שולחן": r("table reservation", "reserva de mesa", "reserva de mesa", "حجز طاولة"),
    "ביקורות מטופלים": r("patient reviews", "reseñas de pacientes", "avaliações de pacientes", "مراجعات المرضى"),
    "צוות רפואי": r("medical team", "equipo médico", "equipe médica", "فريق طبي"),
    "מרפאת שיניים": r("dental clinic", "clínica dental", "clínica odontológica", "عيادة أسنان"),
    "עורכי דין": r("lawyers", "abogados", "advogados", "محامون"),
    "ייעוץ פיננסי": r("financial advice", "asesoría financiera", "consultoria financeira", "استشارة مالية"),
    "סוכני נדל״ן": r("real-estate agents", "agentes inmobiliarios", "corretores", "وسطاء عقاريون"),
    "סוכן נדל״ן": r("real-estate agent", "agente inmobiliario", "corretor", "وسيط عقاري"),
    "משרדי עורכי דין": r("law offices", "despachos de abogados", "escritórios de advocacia", "مكاتب محاماة"),
    "משרד עורכי דין": r("law office", "despacho de abogados", "escritório de advocacia", "مكتب محاماة"),
    "סטודיו צילום": r("photo studio", "estudio fotográfico", "estúdio fotográfico", "استوديو تصوير"),
    "יוצרי וידאו": r("video creators", "creadores de vídeo", "criadores de vídeo", "صنّاع فيديو"),
    "מסעדת שף": r("chef restaurant", "restaurante de chef", "restaurante de chef", "مطعم شيف"),
    "תפריט עונתי": r("seasonal menu", "menú de temporada", "cardápio sazonal", "قائمة موسمية"),
    "הזמנת שולחן": r("reserving a table", "reservar mesa", "reservar mesa", "حجز طاولة"),
    "fine dining": r("fine dining", "fine dining", "fine dining", "fine dining"),
    "Hero דרמטי": r("a dramatic hero", "un hero dramático", "um hero dramático", "بطل درامي"),
    "טיפוגרפיה ענקית": r("giant typography", "tipografía enorme", "tipografia enorme", "طباعة ضخمة"),
    "טיפוגרפיה גדולה": r("large typography", "tipografía grande", "tipografia grande", "طباعة كبيرة"),
    "תמונות צפות": r("floating images", "imágenes flotantes", "imagens flutuantes", "صور عائمة"),
    "כרטיסי שירות": r("service cards", "tarjetas de servicio", "cartões de serviço", "بطاقات خدمة"),
    "עבודות נבחרות": r("selected work", "trabajos destacados", "trabalhos em destaque", "أعمال مختارة"),
    "גלריית עבודות": r("work gallery", "galería de trabajos", "galeria de trabalhos", "معرض أعمال"),
    "עמודי תוכן מלאים": r("full content pages", "páginas de contenido completas", "páginas de conteúdo completas", "صفحات محتوى كاملة"),
    "נוכחות מקצועית": r("a professional presence", "una presencia profesional", "uma presença profissional", "حضور مهني"),
    "נוכחות יוקרתית": r("a luxury presence", "una presencia de lujo", "uma presença sofisticada", "حضور فاخر"),
    "שפה חדה": r("sharp language", "lenguaje nítido", "linguagem nítida", "لغة حادة"),
    "תהליך שקוף": r("a transparent process", "un proceso transparente", "um processo transparente", "عملية شفافة"),
    "תוצאה מדידה": r("a measurable result", "un resultado medible", "um resultado mensurável", "نتيجة قابلة للقياس"),
    "שיפור מתמיד": r("continuous improvement", "mejora continua", "melhoria contínua", "تحسين مستمر"),
    "על בסיס נתונים": r("based on data", "basado en datos", "com base em dados", "على أساس بيانات"),
    "לוחות זמנים": r("schedules", "plazos", "prazos", "جداول"),
    "תשובה מקצועית ומהירה": r("a fast professional reply", "una respuesta profesional y rápida", "uma resposta profissional e rápida", "رد مهني وسريع"),
    "הצעד הבא": r("the next step", "el siguiente paso", "o próximo passo", "الخطوة التالية"),
    "בלי התחייבות": r("with no commitment", "sin compromiso", "sem compromisso", "بلا التزام"),
    "בלי רעש": r("without noise", "sin ruido", "sem ruído", "بلا ضجيج"),
    "בלי לחץ": r("without pressure", "sin presión", "sem pressão", "بلا ضغط"),
    "בלי פשרות": r("without compromise", "sin compromisos", "sem concessões", "بلا تنازلات"),
    "בלי קיצורי דרך": r("without shortcuts", "sin atajos", "sem atalhos", "بلا اختصارات"),
    "מוכנים להתחיל": r("ready to start", "listos para empezar", "prontos para começar", "مستعدون للبدء"),
    "מוכנים לדבר": r("ready to talk", "listos para hablar", "prontos para conversar", "مستعدون للحديث"),
    "בואו נבנה": r("let’s build", "construyamos", "vamos construir", "لنبنِ"),
    "השלב הבא": r("the next stage", "la siguiente etapa", "a próxima etapa", "المرحلة التالية"),
    "המהלך הבא": r("the next move", "el siguiente movimiento", "o próximo movimento", "الخطوة التالية"),
    "אנחנו בונים": r("we build", "construimos", "construímos", "نبني"),
    "כל פרויקט": r("every project", "cada proyecto", "cada projeto", "كل مشروع"),
    "מתחיל באבחון": r("starts with an assessment", "empieza con un diagnóstico", "começa com um diagnóstico", "يبدأ بتشخيص"),
    "מסתיים ב": r("ends with", "termina en", "termina em", "ينتهي بـ"),
    "שאפשר להפעיל מיד": r("that you can run immediately", "que se pueden activar al momento", "que dá para ativar na hora", "يمكن تشغيلها فوراً"),
    "8 עמודים": r("8 pages", "8 páginas", "8 páginas", "8 صفحات"),
    "6 עמודים": r("6 pages", "6 páginas", "6 páginas", "6 صفحات"),
    "5 עמודים": r("5 pages", "5 páginas", "5 páginas", "5 صفحات"),
    "11 עמודים": r("11 pages", "11 páginas", "11 páginas", "11 صفحة"),
    "4 שלבים": r("4 steps", "4 pasos", "4 etapas", "4 خطوات"),
    "3 שלבים": r("3 steps", "3 pasos", "3 etapas", "3 خطوات"),
    "שקיפות מלאה": r("full transparency", "transparencia total", "transparência total", "شفافية كاملة"),
    "ליווי מלא": r("full guidance", "acompañamiento completo", "acompanhamento completo", "مرافقة كاملة"),
    "ליווי אישי": r("personal guidance", "acompañamiento personal", "acompanhamento pessoal", "مرافقة شخصية"),
    "תוכן עריך": r("editable content", "contenido editable", "conteúdo editável", "محتوى قابل للتحرير"),
    "תוכן שמלווה": r("content that accompanies", "contenido que acompaña", "conteúdo que acompanha", "محتوى يرافق"),
    "בחירת מוצרים": r("product selection", "elección de productos", "escolha de produtos", "اختيار المنتجات"),
    "חומרי עבודה": r("working materials", "materiales de trabajo", "materiais de trabalho", "مواد العمل"),
    "חומרי גלם": r("raw ingredients", "materias primas", "matérias-primas", "مواد خام"),
    "חומר גלם": r("raw ingredient", "materia prima", "matéria-prima", "مادة خام"),
    "זמן הייעוץ": r("consultation time", "tiempo de consulta", "tempo de consulta", "وقت الاستشارة"),
    "הנחיות ההמשך": r("aftercare notes", "indicaciones de seguimiento", "orientações de continuidade", "إرشادات المتابعة"),
    "לוח התורים": r("the booking board", "la agenda", "a agenda", "لوحة المواعيد"),
    "סביבת טיפול": r("treatment environment", "entorno de tratamiento", "ambiente de tratamento", "بيئة علاج"),
    "תוצאה עקבית": r("a consistent result", "un resultado constante", "um resultado consistente", "نتيجة ثابتة"),
    "תיק עבודות": r("a portfolio", "un portafolio", "um portfólio", "معرض أعمال"),
    "תהליך עבודה": r("a working process", "un proceso de trabajo", "um processo de trabalho", "عملية عمل"),
    "תהליך עבודה ברור": r("a clear working process", "un proceso de trabajo claro", "um processo de trabalho claro", "عملية عمل واضحة"),
    "קבלת פנים": r("a welcome", "una bienvenida", "uma recepção", "ترحيب"),
    "אזורי טיפול": r("treatment areas", "zonas de tratamiento", "áreas de tratamento", "مناطق علاج"),
    "עמדות עבודה": r("work stations", "puestos de trabajo", "estações de trabalho", "محطات عمل"),
    "פינת סיום": r("a finishing corner", "un rincón de cierre", "um canto de encerramento", "ركن ختام"),
    "הסבר אישי": r("a personal explanation", "una explicación personal", "uma explicação pessoal", "شرح شخصي"),
    "שגרת הבית": r("the home routine", "la rutina de casa", "a rotina de casa", "روتين المنزل"),
    "תחושה טבעית": r("a natural feel", "una sensación natural", "uma sensação natural", "إحساس طبيعي"),
    "תוצאה מורגשת": r("a noticeable result", "un resultado perceptible", "um resultado perceptível", "نتيجة ملموسة"),
    "משך הטיפול": r("treatment duration", "duración del tratamiento", "duração do tratamento", "مدة العلاج"),
    "זמן התאמה": r("fitting time", "tiempo de ajuste", "tempo de ajuste", "وقت الملاءمة"),
    "בין תורים": r("between appointments", "entre citas", "entre horários", "بين المواعيد"),
    "עבודה רגועה": r("calm work", "trabajo calmado", "trabalho calmo", "عمل هادئ"),
    "לדחוס לקוחות": r("to rush clients", "apretar a las clientas", "apressar clientes", "حشر العميلات"),
    "מסכה מרגיעה": r("a calming mask", "una mascarilla calmante", "uma máscara calmante", "قناع مهدئ"),
    "עיסוי קצר": r("a short massage", "un masaje breve", "uma massagem curta", "تدليك قصير"),
    "צילום תוצאה": r("a result photo", "una foto del resultado", "uma foto do resultado", "تصوير النتيجة"),
    "תיעוד אישי": r("a personal record", "un registro personal", "um registro pessoal", "توثيق شخصي"),
    "בלי הבטחות מוגזמות": r("without exaggerated promises", "sin promesas exageradas", "sem promessas exageradas", "بلا وعود مبالغ فيها"),
    "לשמור על התוצאה": r("to keep the result", "cuidar el resultado", "manter o resultado", "للحفاظ على النتيجة"),
    "לפני כל תוספת": r("before every add-on", "antes de cada extra", "antes de cada extra", "قبل كل إضافة"),
    "הסבר ואישור": r("an explanation and approval", "explicación y confirmación", "explicação e confirmação", "شرح وموافقة"),
    "יום ושעה": r("day and time", "día y hora", "dia e horário", "يوم ووقت"),
    "מדיניות ביטולים": r("cancellation policy", "política de cancelación", "política de cancelamento", "سياسة الإلغاء"),
    "פרטי יצירת קשר": r("contact details", "datos de contacto", "dados de contato", "بيانات التواصل"),
    "איך מגיעים": r("how to get here", "cómo llegar", "como chegar", "كيف تصلون"),
    "בלי חיוב": r("at no charge", "sin cargo", "sem cobrança", "دون رسوم"),
    "עד 24 שעות": r("up to 24 hours", "hasta 24 horas", "até 24 horas", "حتى 24 ساعة"),
    "לפני התור": r("before the appointment", "antes de la cita", "antes do horário", "قبل الموعد"),
    "חניון קרוב": r("nearby parking", "parking cercano", "estacionamento perto", "موقف قريب"),
    "חניה ברחוב": r("street parking", "aparcamiento en la calle", "estacionamento na rua", "وقوف في الشارع"),
    "הודעת האישור": r("the confirmation message", "el mensaje de confirmación", "a mensagem de confirmação", "رسالة التأكيد"),
    "נחזור אליכן": r("we will get back to you", "volveremos", "voltaremos", "سنعود إليكن"),
    "לאישור התור": r("to confirm the appointment", "para confirmar la cita", "para confirmar o horário", "لتأكيد الموعد"),
    "בהקדם": r("soon", "pronto", "em breve", "قريباً"),
    "נדאג לשאר": r("we will take care of the rest", "nos ocupamos del resto", "cuidamos do resto", "سنتولى الباقي"),
    "ייעוץ פתיחה": r("an opening consult", "consulta inicial", "consulta inicial", "استشارة افتتاح"),
    "התאמת חומרי עבודה": r("matching working materials", "ajuste de materiales", "ajuste de materiais", "ملاءمة مواد العمل"),
    "סיכום כתוב": r("a written summary", "un resumen escrito", "um resumo escrito", "ملخص مكتوب"),
    "להמשך בבית": r("for home follow-up", "para el seguimiento en casa", "para o acompanhamento em casa", "للمتابعة في المنزل"),
    "שלושה טיפולים": r("three treatments", "tres tratamientos", "três tratamentos", "ثلاثة علاجات"),
    "מתוכננים מראש": r("planned in advance", "planificados de antemano", "planejados com antecedência", "مخططة مسبقاً"),
    "מעקב תוצאה": r("result follow-up", "seguimiento del resultado", "acompanhamento do resultado", "متابعة النتيجة"),
    "בין ביקורים": r("between visits", "entre visitas", "entre visitas", "بين الزيارات"),
    "יום טיפוח": r("a care day", "un día de cuidado", "um dia de cuidado", "يوم عناية"),
    "הפסקת שתייה": r("a drink break", "una pausa para beber", "uma pausa para bebida", "استراحة مشروب"),
    "תור המשך": r("a follow-up appointment", "una cita de seguimiento", "um horário de continuidade", "موعد متابعة"),
    "לפי הצורך": r("as needed", "si hace falta", "se precisar", "عند الحاجة"),
    "בריאות מעל הכל": r("health comes first", "la salud es lo primero", "saúde em primeiro lugar", "الصحة أولاً"),
    "איחור מעל": r("arriving more than", "un retraso de más de", "atraso acima de", "تأخير أكثر من"),
    "עלול לקצר": r("may shorten", "puede acortar", "pode encurtar", "قد يقصّر"),
    "את הטיפול": r("the treatment", "el tratamiento", "o tratamento", "العلاج"),

    # Content words used across templates
    "קטלוג": r("catalog", "catálogo", "catálogo", "كتالوج"),
    "עבודה": r("work", "trabajo", "trabalho", "عمل"),
    "אבחון": r("assessment", "diagnóstico", "diagnóstico", "تشخيص"),
    "התאמה": r("fitting", "ajuste", "ajuste", "ملاءمة"),
    "טיפול": r("treatment", "tratamiento", "tratamiento", "علاج"),
    "טיפולים": r("treatments", "tratamientos", "tratamentos", "علاجات"),
    "חנות": r("store", "tienda", "loja", "متجر"),
    "החנות": r("the store", "la tienda", "a loja", "المتجر"),
    "מוצר": r("product", "producto", "produto", "منتج"),
    "מוצרים": r("products", "productos", "produtos", "منتجات"),
    "המוצרים": r("the products", "los productos", "os produtos", "المنتجات"),
    "המוצר": r("the product", "el producto", "o produto", "المنتج"),
    "עיצוב": r("design", "diseño", "design", "تصميم"),
    "צוות": r("team", "equipo", "equipe", "فريق"),
    "הצוות": r("the team", "el equipo", "a equipe", "الفريق"),
    "תהליך": r("process", "proceso", "processo", "عملية"),
    "אתר": r("website", "sitio", "site", "موقع"),
    "עמודים": r("pages", "páginas", "páginas", "صفحات"),
    "עמוד": r("page", "página", "página", "صفحة"),
    "תוכן": r("content", "contenido", "conteúdo", "محتوى"),
    "סוכנות": r("agency", "agencia", "agência", "وكالة"),
    "לסוכנות": r("for an agency", "para una agencia", "para uma agência", "لوكالة"),
    "סטודיו": r("studio", "estudio", "estúdio", "استوديو"),
    "ליווי": r("guidance", "acompañamiento", "acompanhamento", "مرافقة"),
    "נכסים": r("properties", "inmuebles", "imóveis", "عقارات"),
    "נכס": r("property", "inmueble", "imóvel", "عقار"),
    "הנכס": r("the property", "el inmueble", "o imóvel", "العقار"),
    "פרימיום": r("premium", "premium", "premium", "فاخر"),
    "ייעוץ": r("consulting", "consultoría", "consultoria", "استشارة"),
    "שירות": r("service", "servicio", "serviço", "خدمة"),
    "שירותים": r("services", "servicios", "serviços", "خدمات"),
    "השירותים": r("the services", "los servicios", "os serviços", "الخدمات"),
    "צילום": r("photography", "fotografía", "fotografia", "تصوير"),
    "מסלול": r("plan", "ruta", "percurso", "مسار"),
    "מסלולים": r("plans", "rutas", "percursos", "مسارات"),
    "קטגוריות": r("categories", "categorías", "categorias", "فئات"),
    "קטגוריה": r("category", "categoría", "categoria", "فئة"),
    "ערב": r("evening", "tarde", "noite", "مساء"),
    "צבע": r("color", "color", "cor", "لون"),
    "תכנון": r("planning", "planificación", "planejamento", "تخطيط"),
    "סיפור": r("story", "historia", "história", "قصة"),
    "הסיפור": r("the story", "la historia", "a história", "القصة"),
    "חדר": r("room", "habitación", "quarto", "غرفة"),
    "חדרים": r("rooms", "habitaciones", "quartos", "غرف"),
    "פעולה": r("action", "acción", "ação", "إجراء"),
    "אור": r("light", "luz", "luz", "ضوء"),
    "תור": r("appointment", "cita", "horário", "موعد"),
    "תורים": r("appointments", "citas", "horários", "مواعيد"),
    "שקט": r("quiet", "calma", "silêncio", "هدوء"),
    "מערכת": r("system", "sistema", "sistema", "نظام"),
    "מטבח": r("kitchen", "cocina", "cozinha", "مطبخ"),
    "המטבח": r("the kitchen", "la cocina", "a cozinha", "المطبخ"),
    "שעות": r("hours", "horas", "horas", "ساعات"),
    "אפקטים": r("effects", "efectos", "efeitos", "تأثيرات"),
    "ידע": r("knowledge", "conocimiento", "conhecimento", "معرفة"),
    "ניסיון": r("experience", "experiencia", "experiência", "خبرة"),
    "פנים": r("interior", "interior", "interior", "داخل"),
    "יכולות": r("capabilities", "capacidades", "capacidades", "قدرات"),
    "תפריט": r("menu", "menú", "cardápio", "قائمة"),
    "טעם": r("flavor", "sabor", "sabor", "طعم"),
    "עור": r("skin", "piel", "pele", "بشرة"),
    "מותג": r("brand", "marca", "marca", "علامة"),
    "המותג": r("the brand", "la marca", "a marca", "العلامة"),
    "נחיתה": r("landing", "aterrizaje", "pouso", "هبوط"),
    "איפור": r("makeup", "maquillaje", "maquiagem", "مكياج"),
    "מחיר": r("price", "precio", "preço", "سعر"),
    "מחירים": r("prices", "precios", "preços", "أسعار"),
    "תיק": r("case", "caso", "caso", "ملف"),
    "מקום": r("place", "lugar", "lugar", "مكان"),
    "שף": r("chef", "chef", "chef", "شيف"),
    "סקשנים": r("sections", "secciones", "seções", "أقسام"),
    "חוויה": r("experience", "experiencia", "experiência", "تجربة"),
    "החוויה": r("the experience", "la experiencia", "a experiência", "التجربة"),
    "התוצאה": r("the result", "el resultado", "o resultado", "النتيجة"),
    "תוצאה": r("result", "resultado", "resultado", "نتيجة"),
    "תוצאות": r("results", "resultados", "resultados", "نتائج"),
    "פרטי": r("details", "datos", "dados", "تفاصيل"),
    "פרטים": r("details", "datos", "dados", "بيانات"),
    "תמונות": r("photos", "fotos", "fotos", "صور"),
    "תמונה": r("photo", "foto", "foto", "صورة"),
    "דף": r("page", "página", "página", "صفحة"),
    "קפה": r("coffee", "café", "café", "قهوة"),
    "מפגש": r("session", "encuentro", "encontro", "لقاء"),
    "גלריה": r("gallery", "galería", "galeria", "معرض"),
    "תוספות": r("add-ons", "extras", "extras", "إضافات"),
    "שולחן": r("table", "mesa", "mesa", "طاولة"),
    "בוקר": r("morning", "mañana", "manhã", "صباح"),
    "סט": r("set", "set", "set", "طقم"),
    "שיחה": r("conversation", "conversación", "conversa", "حديث"),
    "סניקרס": r("sneakers", "zapatillas", "tênis", "سنيكرز"),
    "נוף": r("view", "paisaje", "vista", "منظر"),
    "משלוח": r("shipping", "envío", "entrega", "شحن"),
    "משלוחים": r("shipments", "envíos", "entregas", "شحنات"),
    "חיים": r("life", "vida", "vida", "حياة"),
    "חומר": r("material", "material", "material", "مادة"),
    "חומרים": r("materials", "materiales", "materiais", "مواد"),
    "פיתוח": r("development", "desarrollo", "desenvolvimento", "تطوير"),
    "גן": r("garden", "jardín", "jardim", "حديقة"),
    "העדפות": r("preferences", "preferencias", "preferências", "تفضيلات"),
    "מפרט": r("spec", "ficha", "especificação", "مواصفات"),
    "טיפוח": r("care", "cuidado", "cuidado", "عناية"),
    "אמון": r("trust", "confianza", "confiança", "ثقة"),
    "אסטרטגיה": r("strategy", "estrategia", "estratégia", "استراتيجية"),
    "תוכנית": r("plan", "plan", "plano", "خطة"),
    "תוכניות": r("plans", "planes", "planos", "خطط"),
    "קצב": r("pace", "ritmo", "ritmo", "إيقاع"),
    "שפה": r("language", "lenguaje", "linguagem", "لغة"),
    "עומק": r("depth", "profundidad", "profundidade", "عمق"),
    "קנייה": r("purchase", "compra", "compra", "شراء"),
    "יוקרה": r("luxury", "lujo", "luxo", "فخامة"),
    "ניהול": r("management", "gestión", "gestão", "إدارة"),
    "תיאום": r("coordination", "coordinación", "coordenação", "تنسيق"),
    "תאורה": r("lighting", "iluminación", "iluminação", "إضاءة"),
    "בוטיק": r("boutique", "boutique", "boutique", "بوتيك"),
    "אופנה": r("fashion", "moda", "moda", "أزياء"),
    "ים": r("sea", "mar", "mar", "بحر"),
    "הים": r("the sea", "el mar", "o mar", "البحر"),
    "אימון": r("training", "entrenamiento", "treino", "تدريب"),
    "מכירות": r("sales", "ventas", "vendas", "مبيعات"),
    "נתונים": r("data", "datos", "dados", "بيانات"),
    "בר": r("bar", "bar", "bar", "بار"),
    "קומה": r("floor", "planta", "andar", "طابق"),
    "קומות": r("floors", "plantas", "andares", "طوابق"),
    "מים": r("water", "agua", "água", "ماء"),
    "דקות": r("minutes", "minutos", "minutos", "دقائق"),
    "דירה": r("apartment", "piso", "apartamento", "شقة"),
    "דירות": r("apartments", "pisos", "apartamentos", "شقق"),
    "פרויקטים": r("projects", "proyectos", "projetos", "مشاريع"),
    "פרויקט": r("project", "proyecto", "projeto", "مشروع"),
    "סל": r("cart", "carrito", "carrinho", "سلة"),
    "סינון": r("filtering", "filtro", "filtro", "تصفية"),
    "שוק": r("market", "mercado", "mercado", "سوق"),
    "מיפוי": r("mapping", "mapeo", "mapeamento", "رسم"),
    "אירועים": r("events", "eventos", "eventos", "فعاليات"),
    "אירוע": r("event", "evento", "evento", "فعالية"),
    "ציוד": r("equipment", "equipo", "equipamento", "معدات"),
    "כרטיסי": r("cards of", "tarjetas de", "cartões de", "بطاقات"),
    "תכשיטים": r("jewelry", "joyería", "joias", "مجوهرات"),
    "רחוב": r("street", "calle", "rua", "شارع"),
    "מדיה": r("media", "medios", "mídia", "وسائط"),
    "למידה": r("learning", "aprendizaje", "aprendizagem", "تعلّم"),
    "הבית": r("the home", "la casa", "a casa", "المنزل"),
    "בית": r("home", "casa", "casa", "بيت"),
    "שימוש": r("use", "uso", "uso", "استخدام"),
    "טקסטיל": r("textiles", "textiles", "têxteis", "منسوجات"),
    "ספר": r("book", "libro", "livro", "كتاب"),
    "ספרים": r("books", "libros", "livros", "كتب"),
    "קריאה": r("reading", "lectura", "leitura", "قراءة"),
    "בתים": r("homes", "casas", "casas", "منازل"),
    "קשר": r("contact", "contacto", "contato", "تواصل"),
    "יופי": r("beauty", "belleza", "beleza", "جمال"),
    "עבודות": r("works", "trabajos", "trabalhos", "أعمال"),
    "שיווק": r("marketing", "marketing", "marketing", "تسويق"),
    "עסקאות": r("deals", "operaciones", "negócios", "صفقات"),
    "מבנה": r("structure", "estructura", "estrutura", "هيكل"),
    "צמיחה": r("growth", "crecimiento", "crescimento", "نمو"),
    "שיער": r("hair", "cabello", "cabelo", "شعر"),
    "בשר": r("meat", "carne", "carne", "لحم"),
    "תיקים": r("bags", "bolsos", "bolsas", "حقائب"),
    "לוח": r("board", "tablero", "quadro", "لوحة"),
    "מדף": r("shelf", "estante", "prateleira", "رف"),
    "טיפולים": r("treatments", "tratamientos", "tratamentos", "علاجات"),
    "רגעים": r("moments", "momentos", "momentos", "لحظات"),
    "דמו": r("demo", "demo", "demo", "تجريبي"),
    "גישה": r("access", "acceso", "acesso", "وصول"),
    "נעליים": r("shoes", "zapatos", "sapatos", "أحذية"),
    "גבות": r("brows", "cejas", "sobrancelhas", "حواجب"),
    "חודש": r("month", "mes", "mês", "شهر"),
    "ניקוי": r("cleaning", "limpieza", "limpeza", "تنظيف"),
    "חוף": r("beach", "playa", "praia", "شاطئ"),
    "תרגול": r("practice", "práctica", "prática", "تمرين"),
    "כוח": r("strength", "fuerza", "força", "قوة"),
    "משחק": r("game", "juego", "jogo", "لعبة"),
    "מרפסת": r("balcony", "terraza", "varanda", "شرفة"),
    "מדריך": r("guide", "guía", "guia", "دليل"),
    "אורחים": r("guests", "huéspedes", "hóspedes", "ضيوف"),
    "נרות": r("candles", "velas", "velas", "شموع"),
    "הרצליה": r("Herzliya", "Herzliya", "Herzliya", "هرتسليا"),
    "תיקון": r("repair", "reparación", "reparo", "إصلاح"),
    "כלי": r("tool", "herramienta", "ferramenta", "أداة"),
    "כלים": r("tools", "herramientas", "ferramentas", "أدوات"),
    "חצר": r("yard", "patio", "quintal", "فناء"),
    "ימים": r("days", "días", "dias", "أيام"),
    "פתיחה": r("opening", "apertura", "abertura", "افتتاح"),
    "הנהלה": r("leadership", "dirección", "direção", "إدارة"),
    "טעמים": r("flavors", "sabores", "sabores", "نكهات"),
    "חום": r("heat", "calor", "calor", "حرارة"),
    "אודיו": r("audio", "audio", "áudio", "صوت"),
    "מספר": r("number", "número", "número", "رقم"),
    "קערה": r("bowl", "cuenco", "tigela", "وعاء"),
    "שיעורים": r("lessons", "clases", "aulas", "دروس"),
    "קלייה": r("roasting", "tueste", "torra", "تحميص"),
    "יין": r("wine", "vino", "vinho", "نبيذ"),
    "פגישות": r("meetings", "reuniones", "reuniões", "اجتماعات"),
    "קולקציות": r("collections", "colecciones", "coleções", "مجموعات"),
    "המלצות": r("recommendations", "recomendaciones", "recomendações", "توصيات"),
    "היכרות": r("introduction", "presentación", "apresentação", "تعارف"),
    "קריאייטיב": r("creative", "creativo", "criativo", "إبداعي"),
    "סיורים": r("tours", "visitas", "tours", "جولات"),
    "סיור": r("tour", "visita", "tour", "جولة"),
    "אזורים": r("areas", "zonas", "áreas", "مناطق"),
    "אזור": r("area", "zona", "área", "منطقة"),
    "ירקות": r("vegetables", "verduras", "vegetais", "خضار"),
    "מתיקות": r("sweetness", "dulzor", "doçura", "حلاوة"),
    "פירות": r("fruit", "fruta", "frutas", "فاكهة"),
    "סלון": r("salon", "salón", "salão", "صالون"),
    "מגדל": r("tower", "torre", "torre", "برج"),
    "חלל": r("space", "espacio", "espaço", "فضاء"),
    "נשימה": r("breath", "respiración", "respiração", "نفس"),
    "שיעור": r("lesson", "clase", "aula", "درس"),
    "משקיע": r("investor", "inversor", "investidor", "مستثمر"),
    "משקיעים": r("investors", "inversores", "investidores", "مستثمرون"),
    "השקה": r("launch", "lanzamiento", "lançamento", "إطلاق"),
    "כלה": r("bride", "novia", "noiva", "عروس"),
    "מחירון": r("price list", "lista de precios", "lista de preços", "قائمة أسعار"),
    "מעקב": r("follow-up", "seguimiento", "acompanhamento", "متابعة"),
    "הפקה": r("production", "producción", "produção", "إنتاج"),
    "קהל": r("audience", "público", "público", "جمهور"),
    "יעד": r("goal", "objetivo", "meta", "هدف"),
    "העסק": r("the business", "el negocio", "o negócio", "العمل"),
    "ספורט": r("sport", "deporte", "esporte", "رياضة"),
    "ילדים": r("children", "niños", "crianças", "أطفال"),
    "מתנה": r("gift", "regalo", "presente", "هدية"),
    "מזון": r("food", "alimentos", "alimentos", "غذاء"),
    "עשן": r("smoke", "humo", "fumaça", "دخان"),
    "וידאו": r("video", "vídeo", "vídeo", "فيديو"),
    "ספיישלטי": r("specialty", "especialidad", "especialidade", "تخصص"),
    "בגדים": r("clothes", "ropa", "roupas", "ملابس"),
    "בריכה": r("pool", "piscina", "piscina", "مسبح"),
    "מגורים": r("residence", "vivienda", "moradia", "سكن"),
    "צמחים": r("plants", "plantas", "plantas", "نباتات"),
    "קול": r("voice", "voz", "voz", "صوت"),
    "נוכחות": r("presence", "presencia", "presença", "حضور"),
    "פריטים": r("items", "artículos", "itens", "عناصر"),
    "בחירה": r("choice", "elección", "escolha", "اختيار"),
    "מערכות": r("systems", "sistemas", "sistemas", "أنظمة"),
    "ערך": r("value", "valor", "valor", "قيمة"),
    "שמן": r("oil", "aceite", "óleo", "زيت"),
    "הכנות": r("preparations", "preparativos", "preparos", "تحضيرات"),
    "אש": r("fire", "fuego", "fogo", "نار"),
    "קהילה": r("community", "comunidad", "comunidade", "مجتمع"),
    "אדריכלות": r("architecture", "arquitectura", "arquitetura", "عمارة"),
    "מרכז": r("center", "centro", "centro", "مركز"),
    "פרחים": r("flowers", "flores", "flores", "زهور"),
    "חברות": r("companies", "empresas", "empresas", "شركات"),
    "מחקר": r("research", "investigación", "pesquisa", "بحث"),
    "כושר": r("fitness", "fitness", "fitness", "لياقة"),
    "ריסים": r("lashes", "pestañas", "cílios", "رموش"),
    "לילה": r("night", "noche", "noite", "ليل"),
    "גיוס": r("recruiting", "captación", "recrutamento", "توظيف"),
    "שיחות": r("calls", "llamadas", "chamadas", "مكالمات"),
    "מומחים": r("experts", "expertos", "especialistas", "خبراء"),
    "החלטה": r("decision", "decisión", "decisão", "قرار"),
    "מסר": r("message", "mensaje", "mensagem", "رسالة"),
    "שבועות": r("weeks", "semanas", "semanas", "أسابيع"),
    "השרון": r("the Sharon", "el Sharón", "o Sharon", "شارون"),
    "מילים": r("words", "palabras", "palavras", "كلمات"),
    "חיתוך": r("cut", "corte", "corte", "قص"),
    "תאריך": r("date", "fecha", "data", "تاريخ"),
    "משפחה": r("family", "familia", "família", "عائلة"),
    "שותפים": r("partners", "socios", "parceiros", "شركاء"),
    "מראה": r("look", "aspecto", "aparência", "مظهر"),
    "מרקם": r("texture", "textura", "textura", "ملمس"),
    "זמנים": r("timings", "plazos", "prazos", "أوقات"),
    "שכונות": r("neighborhoods", "barrios", "bairros", "أحياء"),
    "טכניקה": r("technique", "técnica", "técnica", "تقنية"),
    "דוחות": r("reports", "informes", "relatórios", "تقارير"),
    "ספקים": r("suppliers", "proveedores", "fornecedores", "مورّدون"),
    "ביטחון": r("confidence", "confianza", "confiança", "ثقة"),
    "חשמל": r("electricity", "electricidad", "elétrica", "كهرباء"),
    "כרטיסים": r("cards", "tarjetas", "cartões", "بطاقات"),
    "עיר": r("city", "ciudad", "cidade", "مدينة"),
    "פנטהאוז": r("penthouse", "ático", "cobertura", "بنتهاوس"),
    "רוטשילד": r("Rothschild", "Rothschild", "Rothschild", "روتشيلد"),
    "טיפוגרפיה": r("typography", "tipografía", "tipografia", "طباعة"),
    "תקשורת": r("communications", "comunicación", "comunicação", "اتصال"),
    "גינה": r("garden", "jardín", "jardim", "حديقة"),
    "וילות": r("villas", "villas", "vilas", "فيلات"),
    "רשת": r("network", "red", "rede", "شبكة"),
    "קמפיינים": r("campaigns", "campañas", "campanhas", "حملات"),
    "קמפיין": r("campaign", "campaña", "campanha", "حملة"),
    "חידוש": r("renewal", "renovación", "renovação", "تجديد"),
    "יקב": r("winery", "bodega", "vinícola", "معصرة"),
    "מענה": r("response", "respuesta", "resposta", "رد"),
    "הלקוח": r("the client", "el cliente", "o cliente", "العميل"),
    "לקוח": r("client", "cliente", "cliente", "عميل"),
    "לקוחות": r("clients", "clientes", "clientes", "عملاء"),
    "רוח": r("spirit", "aire", "ar", "روح"),
    "צורה": r("shape", "forma", "forma", "شكل"),
    "גודל": r("size", "tamaño", "tamanho", "حجم"),
    "כוס": r("cup", "taza", "xícara", "كأس"),
    "גוון": r("tone", "tono", "tom", "درجة"),
    "יפו": r("Jaffa", "Jaffa", "Jaffa", "يافا"),
    "אופניים": r("bicycles", "bicicletas", "bicicletas", "دراجات"),
    "ויטמינים": r("vitamins", "vitaminas", "vitaminas", "فيتامينات"),
    "ביקורות": r("reviews", "reseñas", "avaliações", "مراجعات"),
    "שיניים": r("teeth", "dientes", "dentes", "أسنان"),
    "אבן": r("stone", "piedra", "pedra", "حجر"),
    "טעימות": r("tastings", "catas", "degustações", "تذوّقات"),
    "טכנולוגיה": r("technology", "tecnología", "tecnologia", "تكنولوجيا"),
    "חדש": r("new", "nuevo", "novo", "جديد"),
    "חדשה": r("new", "nueva", "nova", "جديدة"),
    "חדשות": r("news", "novedades", "novidades", "أخبار"),
    "מלא": r("full", "completo", "completo", "كامل"),
    "מלאה": r("full", "completa", "completa", "كاملة"),
    "קצר": r("short", "corto", "curto", "قصير"),
    "קצרה": r("short", "corta", "curta", "قصيرة"),
    "קצרים": r("short", "cortos", "curtos", "قصيرة"),
    "אישית": r("personal", "personal", "pessoal", "شخصية"),
    "אישי": r("personal", "personal", "pessoal", "شخصي"),
    "מדויקת": r("precise", "precisa", "precisa", "دقيقة"),
    "מדויק": r("precise", "preciso", "preciso", "دقيق"),
    "מדויקות": r("precise", "precisas", "precisas", "دقيقة"),
    "יפה": r("beautiful", "bello", "bonito", "جميل"),
    "מקצועי": r("professional", "profesional", "profissional", "مهني"),
    "מקצועית": r("professional", "profesional", "profissional", "مهنية"),
    "ברור": r("clear", "claro", "claro", "واضح"),
    "ברורה": r("clear", "clara", "clara", "واضحة"),
    "ברורים": r("clear", "claros", "claros", "واضحة"),
    "רגועה": r("calm", "calmada", "calma", "هادئة"),
    "רגוע": r("calm", "calmado", "calmo", "هادئ"),
    "מהיר": r("fast", "rápido", "rápido", "سريع"),
    "מהירה": r("fast", "rápida", "rápida", "سريعة"),
    "נקי": r("clean", "limpio", "limpo", "نظيف"),
    "נקייה": r("clean", "limpia", "limpa", "نظيفة"),
    "חם": r("warm", "cálido", "quente", "دافئ"),
    "חמה": r("warm", "cálida", "quente", "دافئة"),
    "טבעי": r("natural", "natural", "natural", "طبيعي"),
    "טבעית": r("natural", "natural", "natural", "طبيعية"),
    "קטן": r("small", "pequeño", "pequeno", "صغير"),
    "קטנה": r("small", "pequeña", "pequena", "صغيرة"),
    "קטנות": r("small", "pequeñas", "pequenas", "صغيرة"),
    "קטנים": r("small", "pequeños", "pequenos", "صغيرة"),
    "גדול": r("large", "grande", "grande", "كبير"),
    "גדולה": r("large", "grande", "grande", "كبيرة"),
    "גדולים": r("large", "grandes", "grandes", "كبيرة"),
    "טרי": r("fresh", "fresco", "fresco", "طازج"),
    "פתוח": r("open", "abierto", "aberto", "مفتوح"),
    "עדין": r("subtle", "sutil", "sutil", "لطيف"),
    "עדינה": r("subtle", "sutil", "sutil", "لطيفة"),
    "ייחודי": r("unique", "único", "único", "فريد"),
    "יוקרתי": r("luxurious", "de lujo", "sofisticado", "فاخر"),
    "יוקרתית": r("luxurious", "de lujo", "sofisticada", "فاخرة"),
    "עסקי": r("business", "empresarial", "empresarial", "تجاري"),
    "עסקית": r("business", "empresarial", "empresarial", "تجارية"),
    "חכם": r("smart", "inteligente", "inteligente", "ذكي"),
    "חכמה": r("smart", "inteligente", "inteligente", "ذكية"),
    "אמיתי": r("real", "real", "real", "حقيقي"),
    "אמיתית": r("real", "real", "real", "حقيقية"),
    "אמיתיים": r("real", "reales", "reais", "حقيقية"),
    "מותאם": r("tailored", "adaptado", "adaptado", "مخصّص"),
    "כהה": r("dark", "oscuro", "escuro", "داكن"),
    "גבוה": r("high", "alto", "alto", "عالٍ"),
    "גבוהה": r("high", "alta", "alta", "عالية"),
    "נמוך": r("low", "bajo", "baixo", "منخفض"),
    "קלאסי": r("classic", "clásico", "clássico", "كلاسيكي"),
    "מושלם": r("perfect", "perfecto", "perfeito", "مثالي"),
    "מושלמת": r("perfect", "perfecta", "perfeita", "مثالية"),
    "אלגנטי": r("elegant", "elegante", "elegante", "أنيق"),
    "רכה": r("soft", "suave", "suave", "ناعمة"),
    "רך": r("soft", "suave", "suave", "ناعم"),
    "רכים": r("soft", "suaves", "suaves", "ناعمة"),
    "חדה": r("sharp", "nítida", "nítida", "حادة"),
    "חד": r("sharp", "nítido", "nítido", "حاد"),
    "ארוך": r("long", "largo", "longo", "طويل"),
    "מתקדם": r("advanced", "avanzado", "avançado", "متقدم"),
    "מודרנית": r("modern", "moderna", "moderna", "حديثة"),
    "דיגיטלית": r("digital", "digital", "digital", "رقمية"),
    "דיגיטלי": r("digital", "digital", "digital", "رقمي"),
    "חזקה": r("strong", "fuerte", "forte", "قوية"),
    "פשוט": r("simple", "sencillo", "simples", "بسيط"),
    "שקטה": r("quiet", "tranquila", "tranquila", "هادئة"),
    "שקוף": r("transparent", "transparente", "transparente", "شفاف"),
    "מסודר": r("tidy", "ordenado", "organizado", "منظّم"),
    "חם": r("hot", "caliente", "quente", "ساخن"),
    "עכשיו": r("now", "ahora", "agora", "الآن"),
    "כאן": r("here", "aquí", "aqui", "هنا"),
    "יחד": r("together", "juntos", "juntos", "معاً"),
    "עוד": r("more", "más", "mais", "المزيد"),
    "מחדש": r("again", "de nuevo", "de novo", "من جديد"),
    "מראש": r("in advance", "de antemano", "com antecedência", "مسبقاً"),
    "באמת": r("truly", "de verdad", "de verdade", "حقاً"),
    "מהר": r("quickly", "rápido", "rápido", "بسرعة"),
    "בדיוק": r("exactly", "exactamente", "exatamente", "تماماً"),
    "היום": r("today", "hoy", "hoje", "اليوم"),
    "אונליין": r("online", "en línea", "online", "أونلاين"),
    "אנחנו": r("we", "nosotros", "nós", "نحن"),
    "שלנו": r("our", "nuestro", "nosso", "لنا"),
    "שלכם": r("your", "vuestro", "de vocês", "لكم"),
    "שלך": r("your", "tuyo", "seu", "لك"),
    "הבא": r("next", "siguiente", "próximo", "التالي"),
    "הראשון": r("the first", "el primero", "o primeiro", "الأول"),
    "הראשונה": r("the first", "la primera", "a primeira", "الأولى"),
    "ראשון": r("first", "primero", "primeiro", "أول"),
    "שלושה": r("three", "tres", "três", "ثلاثة"),
    "שלוש": r("three", "tres", "três", "ثلاث"),
    "אחד": r("one", "uno", "um", "واحد"),
    "אחת": r("one", "una", "uma", "واحدة"),
    "כל": r("every", "cada", "cada", "كل"),
    "יותר": r("more", "más", "mais", "أكثر"),
    "כמה": r("how many", "cuánto", "quanto", "كم"),
    "איך": r("how", "cómo", "como", "كيف"),
    "מה": r("what", "qué", "o que", "ماذا"),
    "למה": r("why", "por qué", "por que", "لماذا"),
    "מתי": r("when", "cuándo", "quando", "متى"),
    "איפה": r("where", "dónde", "onde", "أين"),
    "האם": r("whether", "si", "se", "هل"),
    "אפשר": r("you can", "se puede", "é possível", "يمكن"),
    "כן": r("yes", "sí", "sim", "نعم"),
    "יש": r("there is", "hay", "há", "هناك"),
    "בואו": r("come", "venid", "venham", "تعالوا"),
    "בחרו": r("choose", "elige", "escolha", "اختاروا"),
    "הזמינו": r("order", "pedid", "peçam", "اطلبوا"),
    "כתבו": r("write", "escribid", "escrevam", "اكتبوا"),
    "קבעו": r("book", "reservad", "agendem", "احجزوا"),
    "שמרו": r("save", "guardad", "salvem", "احفظوا"),
    "שלחו": r("send", "enviad", "enviem", "أرسلوا"),
    "גלו": r("discover", "descubrid", "descubram", "اكتشفوا"),
    "צפו": r("view", "ved", "vejam", "شاهدوا"),
    "לבחור": r("to choose", "elegir", "escolher", "للاختيار"),
    "להתחיל": r("to start", "empezar", "começar", "للبدء"),
    "לבנות": r("to build", "construir", "construir", "للبناء"),
    "לראות": r("to see", "ver", "ver", "لرؤية"),
    "להבין": r("to understand", "entender", "entender", "للفهم"),
    "לעזור": r("to help", "ayudar", "ajudar", "للمساعدة"),
    "לדעת": r("to know", "saber", "saber", "لمعرفة"),
    "לבדוק": r("to check", "revisar", "verificar", "لفحص"),
    "לקבל": r("to receive", "recibir", "receber", "للحصول"),
    "להגיע": r("to arrive", "llegar", "chegar", "للوصول"),
    "להיות": r("to be", "ser", "ser", "ليكون"),
    "לתכנן": r("to plan", "planear", "planejar", "للتخطيط"),
    "להפוך": r("to become", "convertir", "tornar", "لتحويل"),
    "נחזור": r("we will return", "volveremos", "voltaremos", "سنعود"),
    "בונים": r("we build", "construimos", "construímos", "نبني"),
    "עובדים": r("we work", "trabajamos", "trabalhamos", "نعمل"),
    "מתחילים": r("we start", "empezamos", "começamos", "نبدأ"),
    "רוצים": r("want", "queréis", "querem", "تريدون"),
    "מוכנים": r("ready", "listos", "prontos", "مستعدون"),
    "מוכנות": r("ready", "listas", "prontas", "جاهزات"),
    "צריכים": r("need", "necesitáis", "precisam", "تحتاجون"),
    "נשמח": r("we would be glad", "estaremos encantados", "teremos prazer", "يسعدنا"),
    "נדאג": r("we will take care", "nos ocuparemos", "cuidaremos", "سنتولى"),
    "מקבלים": r("you receive", "recibís", "recebem", "تحصلون"),
    "בודקים": r("we check", "revisamos", "verificamos", "نفحص"),
    "מציגה": r("shows", "muestra", "mostra", "تعرض"),
    "מתאים": r("fits", "encaja", "serve", "يناسب"),
    "מתאימה": r("fits", "encaja", "serve", "تناسب"),
    "חשוב": r("important", "importante", "importante", "مهم"),
    "מומלץ": r("recommended", "recomendado", "recomendado", "موصى به"),
    "ניתן": r("it is possible", "se puede", "é possível", "يمكن"),
    "נבחרים": r("featured", "destacados", "destaques", "مميز"),
    "נבחר": r("selected", "elegido", "escolhido", "مختار"),
    "פעילים": r("active", "activos", "ativos", "نشطة"),
    "ממוצע": r("average", "media", "média", "متوسط"),
    "יומי": r("daily", "diario", "diário", "يومي"),
    "יומית": r("daily", "diaria", "diária", "يومية"),
    "עונתי": r("seasonal", "de temporada", "sazonal", "موسمي"),
    "פרטיים": r("private", "privados", "privados", "خاصة"),
    "משפחתי": r("family", "familiar", "familiar", "عائلي"),
    "משפטי": r("legal", "jurídico", "jurídico", "قانوني"),
    "משפטית": r("legal", "jurídica", "jurídica", "قانونية"),
    "חיה": r("live", "viva", "viva", "حية"),
    "חי": r("live", "vivo", "vivo", "حي"),
    "עמוק": r("deep", "profundo", "profundo", "عميق"),
    "צמוד": r("adjacent", "adosado", "colado", "ملاصق"),
    "בלעדי": r("exclusive", "exclusivo", "exclusivo", "حصري"),
    "קבוע": r("regular", "fijo", "fixo", "ثابت"),
    "ממוקד": r("focused", "enfocado", "focado", "مركّز"),
    "מודרני": r("modern", "moderno", "moderno", "حديث"),
    "קולנועי": r("cinematic", "cinemático", "cinematográfico", "سينمائي"),
    "קולנועית": r("cinematic", "cinemática", "cinematográfica", "سينمائية"),
    "מינימלי": r("minimal", "mínimo", "mínimo", "بسيط"),
    "נועז": r("bold", "audaz", "ousado", "جريء"),
    "נועזת": r("bold", "audaz", "ousada", "جريئة"),
    "נקייה": r("clean", "limpia", "limpa", "نظيفة"),
    "מרגיע": r("calming", "calmante", "calmante", "مهدئ"),
    "מרגיעה": r("calming", "calmante", "calmante", "مهدئة"),
    "צבעונית": r("colorful", "de color", "colorida", "ملونة"),
    "צבעוני": r("colorful", "de color", "colorido", "ملون"),
    "מונפשות": r("animated", "animadas", "animadas", "متحركة"),
    "מונפש": r("animated", "animado", "animado", "متحرك"),
    "אסימטרי": r("asymmetric", "asimétrico", "assimétrico", "غير متماثل"),
    "אסימטרית": r("asymmetric", "asimétrica", "assimétrica", "غير متماثلة"),
    "אופקיים": r("horizontal", "horizontales", "horizontais", "أفقية"),
    "אופקי": r("horizontal", "horizontal", "horizontal", "أفقي"),
    "אנכי": r("vertical", "vertical", "vertical", "عمودي"),
    "אנכיים": r("vertical", "verticales", "verticais", "عمودية"),
    "עגול": r("round", "redondo", "redondo", "دائري"),
    "עגולה": r("round", "redonda", "redonda", "دائرية"),
    "רחב": r("wide", "ancho", "largo", "عريض"),
    "רחבה": r("wide", "ancha", "larga", "عريضة"),
    "רחבים": r("wide", "anchos", "largos", "عريضة"),
    "חדים": r("sharp", "vivos", "vivos", "حادة"),
    "חדות": r("sharpness", "nitidez", "nitidez", "حدة"),
    "זהב": r("gold", "oro", "ouro", "ذهب"),
    "מוזהב": r("golden", "dorado", "dourado", "ذهبي"),
    "שחור": r("black", "negro", "preto", "أسود"),
    "לבן": r("white", "blanco", "branco", "أبيض"),
    "ירוק": r("green", "verde", "verde", "أخضر"),
    "כחול": r("blue", "azul", "azul", "أزرق"),
    "טורקיז": r("turquoise", "turquesa", "turquesa", "فيروزي"),
    "שמפניה": r("champagne", "champán", "champanhe", "شامبانيا"),
    "שנהב": r("ivory", "marfil", "marfim", "عاجي"),
    "נייבי": r("navy", "marino", "marinho", "كحلي"),
    "הירו": r("hero", "hero", "hero", "hero"),
    "פוטר": r("footer", "pie", "rodapé", "تذييل"),
    "FAQ": r("FAQ", "FAQ", "FAQ", "FAQ"),
    "KPI": r("KPI", "KPI", "KPI", "KPI"),
    "CRM": r("CRM", "CRM", "CRM", "CRM"),
    "SaaS": r("SaaS", "SaaS", "SaaS", "SaaS"),
    "VIP": r("VIP", "VIP", "VIP", "VIP"),
}
