/** Partner Agreement page chrome. Follows the site UI language, not the contract locale. */

const LOCALES = ["en", "he", "es", "pt-BR", "ar"];

const en = {
  list: {
    eyebrow: "Bizuply Admin",
    title: "Partner Agreements",
    intro: "The legal agreement is a fixed template. Create a record only when you are ready to set the partner and commercial details. Nothing is generated or sent on its own.",
    create: "Create agreement",
    loadError: "Could not load partner agreements.",
    territoryTitle: "Territory availability",
    territoryHelp: "A country stays available until an exclusive agreement is signed, paid, and active.",
    all: "All countries",
    available: "Available",
    agreement_pending: "Agreement pending",
    exclusive_active: "Exclusive active",
    renewal_window: "Renewal window",
    expiring_soon: "Expiring soon",
    search: "Search country, partner, or agreement",
    country: "Country",
    status: "Status",
    partner: "Partner",
    agreement: "Agreement",
    start: "Start",
    expiry: "Expiry",
    loading: "Loading territories...",
    showing: "Showing {shown} of {total}. Search to narrow the list.",
    agreements: "Agreements",
    number: "Number",
    type: "Type",
    payment: "Payment",
    term: "Term",
    empty: "No agreements yet.",
    exclusive: "Exclusive",
    nonExclusive: "Non-exclusive",
    rangeTo: "to",
  },
  status: {
    draft: "Draft",
    ready_for_review: "Ready for review",
    sent: "Sent",
    awaiting_signatures: "Awaiting Partner Signatures",
    awaiting_partner_signatures: "Awaiting Partner Signatures",
    awaiting_bizuply_signatures: "Awaiting Bizuply Signatures",
    partially_signed: "Partially Signed",
    partner_signed: "Awaiting Bizuply Signatures",
    bizuply_signed: "Awaiting Partner Signatures",
    payment_pending: "Payment pending",
    signed: "Signed",
    fully_signed: "Fully Signed",
    active: "Active",
    expired: "Expired",
    terminated: "Terminated",
    cancelled: "Cancelled",
    unpaid: "Unpaid",
    paid: "Paid",
    pending: "Pending",
  },
  actions: {
    create: "Created",
    save_draft: "Draft saved",
    amend: "New version",
    ready_for_review: "Ready for review",
    send: "Sent for review",
    payment_pending: "Payment pending",
    record_payment: "Payment recorded",
    activate: "Activated",
    renew_create: "Renewal created",
    approve_renewal: "Renewal approved",
    expire: "Expired",
    terminate: "Terminated",
    cancel: "Cancelled",
    auto_expire: "Expired automatically",
    sign: "Signed",
    new: "New",
  },
  editor: {
    back: "Partner Agreements",
    agreement: "Agreement",
    create: "Create agreement",
    fill: "Fill the commercial details. The legal text stays in the template.",
    meta: "{number} · {status} · version {version}",
    sample: "Test sample only. Harbor & Co. is not a real partner and nothing has been saved.",
    openError: "Could not open the agreement.",
    partner: "Partner",
    existingPartner: "Existing partner",
    searchPartner: "Search by name or company",
    brand: "Partner / brand name",
    legal: "Legal company name",
    registration: "Registration number",
    incorporation: "Country of incorporation",
    address: "Registered address",
    contact: "Main contact",
    contactEmail: "Contact email",
    phone: "Phone",
    whatsapp: "WhatsApp",
    entity: "Entity type",
    tax: "Tax / VAT number",
    territory: "Territory & Exclusivity",
    territoryType: "Territory type",
    country: "Country / territory",
    wholeCountry: "Whole country",
    countryLevel: "This country is sold at country level. A state or province is not required.",
    locality: "City / metro / custom territory",
    city: "City",
    metro: "Metro",
    customTerritory: "Custom territory",
    localityPlaceholder: "Optional. Example: Miami or South Florida",
    exclusivity: "Exclusivity becomes effective only after every required signatory has signed, the required payment has been completed, and the agreement is active.",
    exclusiveTaken: "Exclusive — Unavailable. {name} · {start} to {end}",
    draftNoReserve: "A draft, a sent agreement, or interest from a prospect does not reserve this country.",
    commercial: "Commercial Terms",
    language: "Agreement language",
    bilingual: "Bilingual with",
    oneLanguage: "One language",
    agreementDate: "Agreement date",
    paymentStatus: "Payment status",
    renewalNotes: "Renewal notes",
    quoteTitle: "Commission quote",
    quoteHelp: "This calculator does not save an agreement.",
    customers: "Active paying customers",
    gross: "Gross collected",
    taxes: "Taxes",
    refunds: "Refunds",
    chargebacks: "Chargebacks",
    passThrough: "Pass-through usage",
    calculate: "Calculate commission",
    quoteError: "Could not calculate commission.",
    customCommission: "This partner profile has a custom commission of {percent}%. This agreement still uses the 30/35/40 template unless you override the percentages.",
    agreementSection: "Agreement",
    agreementNumber: "Agreement number",
    numberPlaceholder: "Assigned on save if left blank",
    specialNote: "Special commercial terms are set in the commercial section. The fixed legal sections are not edited here.",
    save: "Save draft",
    saved: "Draft saved. The territory is not reserved.",
    saveError: "Could not save the draft.",
    preview: "Preview agreement",
    previewRefused: "Preview was refused because it would save an agreement.",
    previewError: "Could not open the preview.",
    newVersion: "New Agreement Version / Amendment",
    amendError: "Could not create a new agreement version.",
    pdf: "Generate PDF",
    pdfError: "Could not generate the PDF.",
    ready: "Ready for review",
    send: "Send for review",
    markSigned: "Mark signed",
    paymentPending: "Payment pending",
    recordPayment: "Record payment",
    activate: "Activate agreement",
    expire: "Expire",
    terminate: "Terminate",
    cancel: "Cancel",
    sendNote: "Send for review marks the agreement as sent. No email is sent.",
    statusNow: "Status is now {status}.",
    updateError: "Could not update the agreement.",
    renewTitle: "Renew",
    renewHelp: "Renewal activates the next term in the same step, so an exclusive country does not become available in between.",
    newNumber: "New agreement number",
    renew: "Renew",
    renewError: "Could not renew the agreement.",
    audit: "Commercial audit",
    auditHelp: "Manual overrides record the field, the previous value, the new value, the Admin, and the time. A signed version is not edited in place.",
    admin: "Admin",
    noAudit: "No manual commercial overrides have been saved on this agreement.",
    history: "History",
    version: "Version {version}",
    versionSigned: "Version {version} · signed",
    linkReady: "Signing link ready. No email was sent.",
    resendError: "Could not resend the signing link.",
    revokeError: "Could not revoke the signing link.",
    signError: "Could not sign for Bizuply.",
  },
  subdivision: {
    state: "State",
    province: "Province / territory",
    stateTerritory: "State / territory",
    emirate: "Emirate",
    union: "State / union territory",
    region: "State / province / emirate / region",
  },
  country: {
    search: "Search countries",
    empty: "No countries match.",
    exclusiveUnavailable: "Exclusive — Unavailable",
    to: "to",
  },
  commercial: {
    title: "Advanced / manual commercial terms",
    help: "The standard agreement stays the default. Choose Custom only for a term you negotiated. The contract uses the value on this agreement and leaves the default out when you override it.",
    resetAll: "Reset commercial section to default",
    customTerm: "Custom term",
    useDefault: "Use default",
    custom: "Custom",
    reset: "Reset to default",
    licenseFee: "License fee",
    licenseFeeDefault: "No standard amount. The fee is completed for this agreement.",
    currency: "Currency",
    duration: "Agreement duration",
    months12: "12 months",
    paymentDue: "Payment due date",
    paymentDueDefault: "Set when the agreement is prepared.",
    start: "Start date",
    startDefault: "Set for this agreement.",
    end: "End date",
    endDefault: "Set for this agreement. It must be after the start date.",
    schedule: "Payment schedule",
    scheduleDefault: "Single payment of the license fee",
    single: "Single payment",
    depositBalance: "Deposit and remaining balance",
    installmentsOption: "Installments",
    customSchedule: "Custom schedule",
    deposit: "Deposit / upfront payment",
    remaining: "Remaining balance",
    remainingDefault: "License fee minus the deposit",
    installmentCount: "Number of installments",
    installmentAmounts: "Installment amounts",
    installmentDefault: "One installment for the license fee",
    label: "Label",
    amount: "Amount",
    addInstallment: "Add installment",
    installmentName: "Installment {n}",
    commission: "Commission",
    commissionDefault: "1–19 customers = 30% · 20–39 = 35% · 40+ = 40%",
    tiers: "Customer-count tiers",
    flat: "Flat recurring commission",
    product: "Different rate by product or service",
    flatPercent: "Flat commission %",
    productName: "Product or service",
    percent: "Percent",
    addProduct: "Add product rate",
    fallback: "Fallback flat % if a product has no rate",
    openEnded: "Open ended",
    addTier: "Add tier",
    minimum: "Minimum customer target",
    minimumDefault: "No minimum customer target",
    performance: "Performance target",
    performanceDefault: "No numeric performance target",
    period: "Performance measurement period",
    periodDefault: "The license term",
    cure: "Cure period",
    cureDefault: "30 days",
    renewalPrice: "Renewal price",
    renewalPriceDefault: "The license fee then in effect",
    renewalTerm: "Renewal term",
    exclusivity: "Exclusive / Non-exclusive",
    nonExclusiveDefault: "Non-exclusive",
    additional: "Additional commercial amounts",
    none: "None",
    addAmount: "Add amount",
    special: "Special terms",
    specialDefault: "No special commercial terms. The fixed legal sections stay unchanged.",
    exclusive: "Exclusive",
    nonExclusive: "Non-exclusive",
  },
  preview: {
    backCreate: "Back to create agreement",
    back: "Back to agreement",
    unsaved: "Preview only. No agreement record was saved.",
    empty: "This preview is empty. Open it from Create Agreement. Nothing is saved.",
    unreadable: "This preview could not be read. Nothing is saved.",
    error: "Could not preview the agreement.",
    program: "Partner Program",
    signedPreserved: "signed version preserved",
    currentTemplate: "current template",
    version: "version {version}",
    partner: "Partner",
    territory: "Territory",
    type: "Type",
    fee: "License fee",
    bizuply: "Bizuply",
    name: "Name",
    title: "Title",
    signature: "Signature",
    date: "Date",
    authorized: "Authorized representative",
    loading: "Loading preview...",
    issuesTitle: "These fields need attention. The preview still shows the values you entered. Nothing was saved.",
    issueLegalProfile: "Bizuply legal profile is missing or incomplete.",
    issueLegalCompanyName: "Partner legal company name is required before Preview.",
    issueBrandName: "Partner / brand name is missing.",
    issueCountry: "Country is missing or not a valid ISO country.",
    issueTerritoryType: "Territory type is missing or not valid.",
    issueDates: "Start and end dates are missing, or the end date is not after the start date.",
    issueLicenseFee: "License fee is missing or not a valid amount.",
    issueCurrency: "Currency is missing or not a valid ISO code.",
    issueContactEmail: "Contact email is missing or not a valid email.",
    issueSignatoryEmail: "A signatory email is missing or not valid.",
    issueSignatories: "A required signatory is missing a name, title, or email.",
    issueSubdivision: "Choose a state, province, emirate, or region before a city.",
    issueIncorporation: "Country of incorporation is missing or not a valid ISO country.",
    issueLocale: "A bilingual agreement needs two different languages.",
    issueCommission: "Commission terms are not valid.",
    issuePayment: "Payment terms are not valid.",
    issueGeneric: "This field needs attention.",
  },
  sign: {
    section: "Signatories",
    partner: "Partner Signatories",
    bizuply: "Bizuply Signatories",
    requiredPartner: "Required Partner Signatures",
    requiredBizuply: "Required Bizuply Signatures",
    custom: "Custom",
    add: "Add signatory",
    remove: "Remove signatory",
    required: "Required",
    optional: "Optional",
    order: "Signing order",
    email: "Email",
    phone: "Phone / WhatsApp",
    name: "Full legal name",
    title: "Title / position",
    mode: "Signing mode",
    parallel: "Parallel",
    sequential: "Sequential",
    parallelHelp: "All required signatories may sign in any order.",
    sequentialHelp: "The next signatory can sign only after the previous required signature.",
    status: "Status",
    signed: "Signed",
    pending: "Pending",
    signedDate: "Signed date",
    resend: "Resend signing link",
    revoke: "Revoke signing link",
    signNow: "Sign as this Bizuply signatory",
    partnerProgress: "Partner signatures",
    bizuplyProgress: "Bizuply signatures",
    of: "of",
    completed: "completed",
    locked: "Someone has signed this version. Create a new agreement version before changing signatories.",
    linkReady: "Signing link ready. No email was sent.",
    saveFirst: "Save the agreement before sending a signing link.",
    signPageTitle: "Sign Partner Agreement",
    signingAs: "You are signing as",
    typeName: "Type your full legal name",
    signButton: "Sign agreement",
    invalidLink: "This signing link is not valid.",
    couldNotSign: "Could not sign.",
    signedAgreement: "Signed",
    company: "Company",
    territory: "Territory",
    exclusivity: "Exclusivity",
    fee: "Fee",
    dates: "Dates",
    linkOpen: "Link open",
    linkConsumed: "Link used",
    linkRevoked: "Link revoked",
    linkExpired: "Link expired",
  },
};

const he = {
  list: {
    eyebrow: "ניהול Bizuply",
    title: "הסכמי פרטנר",
    intro: "ההסכם המשפטי הוא תבנית קבועה. יוצרים רשומה רק כשמוכנים להגדיר את הפרטנר ואת התנאים המסחריים. שום דבר לא נוצר או נשלח מעצמו.",
    create: "יצירת הסכם",
    loadError: "לא ניתן לטעון את הסכמי הפרטנר.",
    territoryTitle: "זמינות טריטוריות",
    territoryHelp: "מדינה נשארת זמינה עד שהסכם בלעדי נחתם, שולם והפך לפעיל.",
    all: "כל המדינות",
    available: "זמין",
    agreement_pending: "הסכם בהמתנה",
    exclusive_active: "בלעדיות פעילה",
    renewal_window: "חלון חידוש",
    expiring_soon: "פג בקרוב",
    search: "חיפוש מדינה, פרטנר או הסכם",
    country: "מדינה",
    status: "סטטוס",
    partner: "פרטנר",
    agreement: "הסכם",
    start: "התחלה",
    expiry: "תפוגה",
    loading: "טוען טריטוריות...",
    showing: "מוצגות {shown} מתוך {total}. חפשו כדי לצמצם את הרשימה.",
    agreements: "הסכמים",
    number: "מספר",
    type: "סוג",
    payment: "תשלום",
    term: "תקופה",
    empty: "אין עדיין הסכמים.",
    exclusive: "בלעדי",
    nonExclusive: "לא בלעדי",
    rangeTo: "עד",
  },
  status: {
    draft: "טיוטה",
    ready_for_review: "מוכן לבדיקה",
    sent: "נשלח",
    awaiting_signatures: "ממתין לחתימות השותף",
    awaiting_partner_signatures: "ממתין לחתימות השותף",
    awaiting_bizuply_signatures: "ממתין לחתימות Bizuply",
    partially_signed: "חתום חלקית",
    partner_signed: "ממתין לחתימות Bizuply",
    bizuply_signed: "ממתין לחתימות השותף",
    payment_pending: "ממתין לתשלום",
    signed: "נחתם",
    fully_signed: "חתום במלואו",
    active: "פעיל",
    expired: "פג תוקף",
    terminated: "הופסק",
    cancelled: "בוטל",
    unpaid: "לא שולם",
    paid: "שולם",
    pending: "ממתין",
  },
  actions: {
    create: "נוצר",
    save_draft: "טיוטה נשמרה",
    amend: "גרסה חדשה",
    ready_for_review: "מוכן לבדיקה",
    send: "נשלח לבדיקה",
    payment_pending: "ממתין לתשלום",
    record_payment: "תשלום נרשם",
    activate: "הופעל",
    renew_create: "חידוש נוצר",
    approve_renewal: "חידוש אושר",
    expire: "פג תוקף",
    terminate: "הופסק",
    cancel: "בוטל",
    auto_expire: "פג תוקף אוטומטית",
    sign: "נחתם",
    new: "חדש",
  },
  editor: {
    back: "הסכמי פרטנר",
    agreement: "הסכם",
    create: "יצירת הסכם",
    fill: "מלאו את הפרטים המסחריים. הנוסח המשפטי נשאר בתבנית.",
    meta: "{number} · {status} · גרסה {version}",
    sample: "דוגמת בדיקה בלבד. Harbor & Co. אינו פרטנר אמיתי ושום דבר לא נשמר.",
    openError: "לא ניתן לפתוח את ההסכם.",
    partner: "פרטנר",
    existingPartner: "פרטנר קיים",
    searchPartner: "חיפוש לפי שם או חברה",
    brand: "שם פרטנר / מותג",
    legal: "שם חברה משפטי",
    registration: "מספר רישום",
    incorporation: "מדינת התאגדות",
    address: "כתובת רשומה",
    contact: "איש קשר ראשי",
    contactEmail: "דוא״ל ליצירת קשר",
    phone: "טלפון",
    whatsapp: "וואטסאפ",
    entity: "סוג ישות",
    tax: "מספר מס / מע״מ",
    territory: "טריטוריה ובלעדיות",
    territoryType: "סוג טריטוריה",
    country: "מדינה / טריטוריה",
    wholeCountry: "כל המדינה",
    countryLevel: "המדינה הזו נמכרת ברמת מדינה. מדינה פנימית או מחוז אינם נדרשים.",
    locality: "עיר / מטרופולין / טריטוריה מותאמת",
    city: "עיר",
    metro: "מטרופולין",
    customTerritory: "טריטוריה מותאמת",
    localityPlaceholder: "אופציונלי. לדוגמה: מיאמי או דרום פלורידה",
    exclusivity: "בלעדיות נכנסת לתוקף רק אחרי שכל החותמים הנדרשים חתמו, התשלום הנדרש הושלם, וההסכם פעיל.",
    exclusiveTaken: "בלעדי — לא זמין. {name} · {start} עד {end}",
    draftNoReserve: "טיוטה, הסכם שנשלח, או התעניינות של ליד אינם שומרים את המדינה.",
    commercial: "תנאים מסחריים",
    language: "שפת ההסכם",
    bilingual: "דו־לשוני עם",
    oneLanguage: "שפה אחת",
    agreementDate: "תאריך ההסכם",
    paymentStatus: "סטטוס תשלום",
    renewalNotes: "הערות חידוש",
    quoteTitle: "הצעת עמלה",
    quoteHelp: "המחשבון הזה לא שומר הסכם.",
    customers: "לקוחות משלמים פעילים",
    gross: "גבייה ברוטו",
    taxes: "מסים",
    refunds: "החזרים",
    chargebacks: "הכחשות עסקה",
    passThrough: "שימוש בהעברה",
    calculate: "חישוב עמלה",
    quoteError: "לא ניתן לחשב עמלה.",
    customCommission: "לפרופיל הפרטנר הזה יש עמלה מותאמת של {percent}%. ההסכם הזה עדיין משתמש בתבנית 30/35/40 אלא אם משנים את האחוזים.",
    agreementSection: "הסכם",
    agreementNumber: "מספר הסכם",
    numberPlaceholder: "יוקצה בשמירה אם נשאר ריק",
    specialNote: "תנאים מסחריים מיוחדים נקבעים במקטע המסחרי. הסעיפים המשפטיים הקבועים לא נערכים כאן.",
    save: "שמירת טיוטה",
    saved: "הטיוטה נשמרה. הטריטוריה לא נשמרה.",
    saveError: "לא ניתן לשמור את הטיוטה.",
    preview: "תצוגה מקדימה של ההסכם",
    previewRefused: "התצוגה נדחתה כי היא הייתה שומרת הסכם.",
    previewError: "לא ניתן לפתוח את התצוגה המקדימה.",
    newVersion: "גרסת הסכם חדשה / תיקון",
    amendError: "לא ניתן ליצור גרסת הסכם חדשה.",
    pdf: "יצירת PDF",
    pdfError: "לא ניתן ליצור את ה־PDF.",
    ready: "מוכן לבדיקה",
    send: "שליחה לבדיקה",
    markSigned: "סימון כחתום",
    paymentPending: "ממתין לתשלום",
    recordPayment: "רישום תשלום",
    activate: "הפעלת ההסכם",
    expire: "פקיעת תוקף",
    terminate: "הפסקה",
    cancel: "ביטול",
    sendNote: "שליחה לבדיקה מסמנת את ההסכם כנשלח. לא נשלח דוא״ל.",
    statusNow: "הסטטוס עכשיו הוא {status}.",
    updateError: "לא ניתן לעדכן את ההסכם.",
    renewTitle: "חידוש",
    renewHelp: "החידוש מפעיל את התקופה הבאה באותו צעד, כדי שמדינה בלעדית לא תהפוך לזמינה באמצע.",
    newNumber: "מספר הסכם חדש",
    renew: "חידוש",
    renewError: "לא ניתן לחדש את ההסכם.",
    audit: "ביקורת מסחרית",
    auditHelp: "עקיפות ידניות רושמות את השדה, הערך הקודם, הערך החדש, המנהל והשעה. גרסה חתומה לא נערכת במקום.",
    admin: "מנהל",
    noAudit: "לא נשמרו עקיפות מסחריות ידניות בהסכם הזה.",
    history: "היסטוריה",
    version: "גרסה {version}",
    versionSigned: "גרסה {version} · חתומה",
    linkReady: "קישור החתימה מוכן. לא נשלח דוא״ל.",
    resendError: "לא ניתן לשלוח מחדש את קישור החתימה.",
    revokeError: "לא ניתן לבטל את קישור החתימה.",
    signError: "לא ניתן לחתום עבור Bizuply.",
  },
  subdivision: {
    state: "מדינה",
    province: "מחוז / טריטוריה",
    stateTerritory: "מדינה / טריטוריה",
    emirate: "אמירות",
    union: "מדינה / טריטוריית איחוד",
    region: "מדינה / מחוז / אמירות / אזור",
  },
  country: {
    search: "חיפוש מדינות",
    empty: "אין מדינות תואמות.",
    exclusiveUnavailable: "בלעדי — לא זמין",
    to: "עד",
  },
  commercial: {
    title: "תנאים מסחריים מתקדמים / ידניים",
    help: "ההסכם הסטנדרטי נשאר ברירת המחדל. בוחרים מותאם רק לתנאי שסוכם. החוזה משתמש בערך שבהסכם הזה ומשמיט את ברירת המחדל כשעוקפים אותה.",
    resetAll: "איפוס המקטע המסחרי לברירת מחדל",
    customTerm: "תנאי מותאם",
    useDefault: "ברירת מחדל",
    custom: "מותאם",
    reset: "איפוס לברירת מחדל",
    licenseFee: "דמי רישיון",
    licenseFeeDefault: "אין סכום סטנדרטי. הסכום מושלם עבור ההסכם הזה.",
    currency: "מטבע",
    duration: "משך ההסכם",
    months12: "12 חודשים",
    paymentDue: "תאריך יעד לתשלום",
    paymentDueDefault: "נקבע כשמכינים את ההסכם.",
    start: "תאריך התחלה",
    startDefault: "נקבע עבור ההסכם הזה.",
    end: "תאריך סיום",
    endDefault: "נקבע עבור ההסכם הזה. חייב להיות אחרי תאריך ההתחלה.",
    schedule: "לוח תשלומים",
    scheduleDefault: "תשלום יחיד של דמי הרישיון",
    single: "תשלום יחיד",
    depositBalance: "מקדמה ויתרה",
    installmentsOption: "תשלומים",
    customSchedule: "לוח מותאם",
    deposit: "מקדמה / תשלום מראש",
    remaining: "יתרה",
    remainingDefault: "דמי הרישיון פחות המקדמה",
    installmentCount: "מספר תשלומים",
    installmentAmounts: "סכומי התשלומים",
    installmentDefault: "תשלום אחד עבור דמי הרישיון",
    label: "תווית",
    amount: "סכום",
    addInstallment: "הוספת תשלום",
    installmentName: "תשלום {n}",
    commission: "עמלה",
    commissionDefault: "1–19 לקוחות = 30% · 20–39 = 35% · 40+ = 40%",
    tiers: "מדרגות לפי מספר לקוחות",
    flat: "עמלת מנוי קבועה",
    product: "שיעור שונה לפי מוצר או שירות",
    flatPercent: "אחוז עמלה קבוע",
    productName: "מוצר או שירות",
    percent: "אחוז",
    addProduct: "הוספת שיעור למוצר",
    fallback: "אחוז קבוע חלופי אם למוצר אין שיעור",
    openEnded: "ללא תקרה",
    addTier: "הוספת מדרגה",
    minimum: "יעד לקוחות מינימלי",
    minimumDefault: "אין יעד לקוחות מינימלי",
    performance: "יעד ביצוע",
    performanceDefault: "אין יעד ביצוע מספרי",
    period: "תקופת מדידת ביצוע",
    periodDefault: "תקופת הרישיון",
    cure: "תקופת תיקון",
    cureDefault: "30 יום",
    renewalPrice: "מחיר חידוש",
    renewalPriceDefault: "דמי הרישיון שבתוקף באותה עת",
    renewalTerm: "תקופת חידוש",
    exclusivity: "בלעדי / לא בלעדי",
    nonExclusiveDefault: "לא בלעדי",
    additional: "סכומים מסחריים נוספים",
    none: "אין",
    addAmount: "הוספת סכום",
    special: "תנאים מיוחדים",
    specialDefault: "אין תנאים מסחריים מיוחדים. הסעיפים המשפטיים הקבועים נשארים ללא שינוי.",
    exclusive: "בלעדי",
    nonExclusive: "לא בלעדי",
  },
  preview: {
    backCreate: "חזרה ליצירת הסכם",
    back: "חזרה להסכם",
    unsaved: "תצוגה בלבד. לא נשמרה רשומת הסכם.",
    empty: "התצוגה ריקה. פתחו אותה מיצירת הסכם. שום דבר לא נשמר.",
    unreadable: "לא ניתן לקרוא את התצוגה. שום דבר לא נשמר.",
    error: "לא ניתן להציג את ההסכם.",
    program: "תוכנית פרטנרים",
    signedPreserved: "גרסה חתומה נשמרה",
    currentTemplate: "תבנית נוכחית",
    version: "גרסה {version}",
    partner: "פרטנר",
    territory: "טריטוריה",
    type: "סוג",
    fee: "דמי רישיון",
    bizuply: "Bizuply",
    name: "שם",
    title: "תפקיד",
    signature: "חתימה",
    date: "תאריך",
    authorized: "נציג מורשה",
    loading: "טוען תצוגה...",
    issuesTitle: "השדות האלה דורשים השלמה או תיקון. התצוגה מציגה את הערכים שהוזנו. לא נשמר דבר.",
    issueLegalProfile: "הפרופיל המשפטי של Bizuply חסר או לא הושלם.",
    issueLegalCompanyName: "חסר שם החברה המשפטי.",
    issueBrandName: "חסר שם השותף או המותג.",
    issueCountry: "חסרה מדינה, או שהקוד אינו מדינת ISO תקינה.",
    issueTerritoryType: "חסר סוג טריטוריה, או שהסוג אינו תקין.",
    issueDates: "חסרים תאריך התחלה ותאריך סיום, או שתאריך הסיום אינו אחרי תאריך ההתחלה.",
    issueLicenseFee: "חסרים דמי רישיון, או שהסכום אינו תקין.",
    issueCurrency: "חסר מטבע, או שהקוד אינו קוד ISO תקין.",
    issueContactEmail: "דוא״ל איש הקשר חסר או אינו תקין.",
    issueSignatoryEmail: "דוא״ל של חותם חסר או אינו תקין.",
    issueSignatories: "לחותם נדרש חסרים שם, תפקיד או דוא״ל.",
    issueSubdivision: "יש לבחור מדינה, מחוז, אמירות או אזור לפני עיר.",
    issueIncorporation: "חסרה מדינת ההתאגדות, או שהקוד אינו מדינת ISO תקינה.",
    issueLocale: "הסכם דו-לשוני צריך שתי שפות שונות.",
    issueCommission: "תנאי העמלה אינם תקינים.",
    issuePayment: "תנאי התשלום אינם תקינים.",
    issueGeneric: "השדה הזה דורש תשומת לב.",
  },
  sign: {
    section: "חותמים",
    partner: "חותמי השותף",
    bizuply: "חותמי Bizuply",
    requiredPartner: "חתימות שותף נדרשות",
    requiredBizuply: "חתימות Bizuply נדרשות",
    custom: "מותאם",
    add: "הוספת חותם",
    remove: "הסרת חותם",
    required: "נדרש",
    optional: "רשות",
    order: "סדר חתימה",
    email: "דוא״ל",
    phone: "טלפון / וואטסאפ",
    name: "שם משפטי מלא",
    title: "תפקיד",
    mode: "מצב חתימה",
    parallel: "מקביל",
    sequential: "רציף",
    parallelHelp: "כל החותמים הנדרשים יכולים לחתום בכל סדר.",
    sequentialHelp: "החותם הבא יכול לחתום רק אחרי שהחתימה הנדרשת הקודמת הושלמה.",
    status: "סטטוס",
    signed: "נחתם",
    pending: "ממתין",
    signedDate: "תאריך חתימה",
    resend: "שליחה מחדש של קישור החתימה",
    revoke: "ביטול קישור החתימה",
    signNow: "חתימה כחותם זה של Bizuply",
    partnerProgress: "חתימות השותף",
    bizuplyProgress: "חתימות Bizuply",
    of: "מתוך",
    completed: "הושלמו",
    locked: "מישהו כבר חתם על גרסה זו. צרו גרסת הסכם חדשה לפני שינוי החותמים.",
    linkReady: "קישור החתימה מוכן. לא נשלח דוא״ל.",
    saveFirst: "שמרו את ההסכם לפני שליחת קישור חתימה.",
    signPageTitle: "חתימה על הסכם פרטנר",
    signingAs: "אתם חותמים בתור",
    typeName: "הקלידו את השם המשפטי המלא",
    signButton: "חתימה על ההסכם",
    invalidLink: "קישור החתימה הזה אינו תקף.",
    couldNotSign: "לא ניתן לחתום.",
    signedAgreement: "נחתם",
    company: "חברה",
    territory: "טריטוריה",
    exclusivity: "בלעדיות",
    fee: "עמלה",
    dates: "תאריכים",
    linkOpen: "קישור פתוח",
    linkConsumed: "הקישור נוצל",
    linkRevoked: "הקישור בוטל",
    linkExpired: "הקישור פג",
  },
};

const es = {
  list: {
    eyebrow: "Administración de Bizuply",
    title: "Acuerdos de Partner",
    intro: "El acuerdo legal es una plantilla fija. Cree un registro solo cuando esté listo para definir el partner y las condiciones comerciales. Nada se genera ni se envía solo.",
    create: "Crear acuerdo",
    loadError: "No se pudieron cargar los acuerdos de partner.",
    territoryTitle: "Disponibilidad de territorios",
    territoryHelp: "Un país sigue disponible hasta que un acuerdo exclusivo esté firmado, pagado y activo.",
    all: "Todos los países",
    available: "Disponible",
    agreement_pending: "Acuerdo pendiente",
    exclusive_active: "Exclusiva activa",
    renewal_window: "Ventana de renovación",
    expiring_soon: "Vence pronto",
    search: "Buscar país, partner o acuerdo",
    country: "País",
    status: "Estado",
    partner: "Partner",
    agreement: "Acuerdo",
    start: "Inicio",
    expiry: "Vencimiento",
    loading: "Cargando territorios...",
    showing: "Mostrando {shown} de {total}. Busque para reducir la lista.",
    agreements: "Acuerdos",
    number: "Número",
    type: "Tipo",
    payment: "Pago",
    term: "Plazo",
    empty: "Aún no hay acuerdos.",
    exclusive: "Exclusivo",
    nonExclusive: "No exclusivo",
    rangeTo: "a",
  },
  status: {
    draft: "Borrador",
    ready_for_review: "Listo para revisión",
    sent: "Enviado",
    awaiting_signatures: "En espera de firmas del Partner",
    awaiting_partner_signatures: "En espera de firmas del Partner",
    awaiting_bizuply_signatures: "En espera de firmas de Bizuply",
    partially_signed: "Firmado parcialmente",
    partner_signed: "En espera de firmas de Bizuply",
    bizuply_signed: "En espera de firmas del Partner",
    payment_pending: "Pago pendiente",
    signed: "Firmado",
    fully_signed: "Totalmente firmado",
    active: "Activo",
    expired: "Vencido",
    terminated: "Rescindido",
    cancelled: "Cancelado",
    unpaid: "Impago",
    paid: "Pagado",
    pending: "Pendiente",
  },
  actions: {
    create: "Creado",
    save_draft: "Borrador guardado",
    amend: "Nueva versión",
    ready_for_review: "Listo para revisión",
    send: "Enviado a revisión",
    payment_pending: "Pago pendiente",
    record_payment: "Pago registrado",
    activate: "Activado",
    renew_create: "Renovación creada",
    approve_renewal: "Renovación aprobada",
    expire: "Vencido",
    terminate: "Rescindido",
    cancel: "Cancelado",
    auto_expire: "Vencido automáticamente",
    sign: "Firmado",
    new: "Nuevo",
  },
  editor: {
    back: "Acuerdos de Partner",
    agreement: "Acuerdo",
    create: "Crear acuerdo",
    fill: "Complete los datos comerciales. El texto legal permanece en la plantilla.",
    meta: "{number} · {status} · versión {version}",
    sample: "Solo una muestra de prueba. Harbor & Co. no es un partner real y no se ha guardado nada.",
    openError: "No se pudo abrir el acuerdo.",
    partner: "Partner",
    existingPartner: "Partner existente",
    searchPartner: "Buscar por nombre o empresa",
    brand: "Nombre del partner / marca",
    legal: "Razón social",
    registration: "Número de registro",
    incorporation: "País de constitución",
    address: "Domicilio social",
    contact: "Contacto principal",
    contactEmail: "Correo de contacto",
    phone: "Teléfono",
    whatsapp: "WhatsApp",
    entity: "Tipo de entidad",
    tax: "Número fiscal / IVA",
    territory: "Territorio y exclusividad",
    territoryType: "Tipo de territorio",
    country: "País / territorio",
    wholeCountry: "Todo el país",
    countryLevel: "Este país se vende a nivel de país. No se requiere un estado o provincia.",
    locality: "Ciudad / área metro / territorio personalizado",
    city: "Ciudad",
    metro: "Área metro",
    customTerritory: "Territorio personalizado",
    localityPlaceholder: "Opcional. Ejemplo: Miami o el sur de Florida",
    exclusivity: "La exclusividad entra en vigor solo cuando todos los firmantes requeridos han firmado, el pago requerido se ha completado y el acuerdo está activo.",
    exclusiveTaken: "Exclusivo — No disponible. {name} · {start} a {end}",
    draftNoReserve: "Un borrador, un acuerdo enviado o el interés de un prospecto no reservan este país.",
    commercial: "Condiciones comerciales",
    language: "Idioma del acuerdo",
    bilingual: "Bilingüe con",
    oneLanguage: "Un idioma",
    agreementDate: "Fecha del acuerdo",
    paymentStatus: "Estado del pago",
    renewalNotes: "Notas de renovación",
    quoteTitle: "Cálculo de comisión",
    quoteHelp: "Esta calculadora no guarda un acuerdo.",
    customers: "Clientes de pago activos",
    gross: "Cobrado bruto",
    taxes: "Impuestos",
    refunds: "Reembolsos",
    chargebacks: "Contracargos",
    passThrough: "Uso de traspaso",
    calculate: "Calcular comisión",
    quoteError: "No se pudo calcular la comisión.",
    customCommission: "El perfil de este partner tiene una comisión personalizada del {percent}%. Este acuerdo sigue usando la plantilla 30/35/40 salvo que cambie los porcentajes.",
    agreementSection: "Acuerdo",
    agreementNumber: "Número de acuerdo",
    numberPlaceholder: "Se asigna al guardar si se deja en blanco",
    specialNote: "Las condiciones comerciales especiales se definen en la sección comercial. Las secciones legales fijas no se editan aquí.",
    save: "Guardar borrador",
    saved: "Borrador guardado. El territorio no queda reservado.",
    saveError: "No se pudo guardar el borrador.",
    preview: "Vista previa del acuerdo",
    previewRefused: "La vista previa se rechazó porque guardaría un acuerdo.",
    previewError: "No se pudo abrir la vista previa.",
    newVersion: "Nueva versión del acuerdo / enmienda",
    amendError: "No se pudo crear una nueva versión del acuerdo.",
    pdf: "Generar PDF",
    pdfError: "No se pudo generar el PDF.",
    ready: "Listo para revisión",
    send: "Enviar a revisión",
    markSigned: "Marcar como firmado",
    paymentPending: "Pago pendiente",
    recordPayment: "Registrar pago",
    activate: "Activar acuerdo",
    expire: "Vencer",
    terminate: "Rescindir",
    cancel: "Cancelar",
    sendNote: "Enviar a revisión marca el acuerdo como enviado. No se envía ningún correo.",
    statusNow: "El estado ahora es {status}.",
    updateError: "No se pudo actualizar el acuerdo.",
    renewTitle: "Renovar",
    renewHelp: "La renovación activa el siguiente plazo en el mismo paso, para que un país exclusivo no quede disponible en el intervalo.",
    newNumber: "Nuevo número de acuerdo",
    renew: "Renovar",
    renewError: "No se pudo renovar el acuerdo.",
    audit: "Auditoría comercial",
    auditHelp: "Las modificaciones manuales registran el campo, el valor anterior, el valor nuevo, el administrador y la hora. Una versión firmada no se edita en el mismo lugar.",
    admin: "Administrador",
    noAudit: "No se han guardado modificaciones comerciales manuales en este acuerdo.",
    history: "Historial",
    version: "Versión {version}",
    versionSigned: "Versión {version} · firmada",
    linkReady: "Enlace de firma listo. No se envió ningún correo.",
    resendError: "No se pudo reenviar el enlace de firma.",
    revokeError: "No se pudo revocar el enlace de firma.",
    signError: "No se pudo firmar por Bizuply.",
  },
  subdivision: {
    state: "Estado",
    province: "Provincia / territorio",
    stateTerritory: "Estado / territorio",
    emirate: "Emirato",
    union: "Estado / territorio de la unión",
    region: "Estado / provincia / emirato / región",
  },
  country: {
    search: "Buscar países",
    empty: "Ningún país coincide.",
    exclusiveUnavailable: "Exclusivo — No disponible",
    to: "a",
  },
  commercial: {
    title: "Condiciones comerciales avanzadas / manuales",
    help: "El acuerdo estándar sigue siendo el valor por defecto. Elija Personalizado solo para una condición negociada. El contrato usa el valor de este acuerdo y omite el valor por defecto cuando lo sustituye.",
    resetAll: "Restablecer la sección comercial",
    customTerm: "Condición personalizada",
    useDefault: "Usar valor por defecto",
    custom: "Personalizado",
    reset: "Restablecer",
    licenseFee: "Cuota de licencia",
    licenseFeeDefault: "No hay un importe estándar. La cuota se completa para este acuerdo.",
    currency: "Moneda",
    duration: "Duración del acuerdo",
    months12: "12 meses",
    paymentDue: "Fecha de vencimiento del pago",
    paymentDueDefault: "Se define al preparar el acuerdo.",
    start: "Fecha de inicio",
    startDefault: "Se define para este acuerdo.",
    end: "Fecha de fin",
    endDefault: "Se define para este acuerdo. Debe ser posterior a la fecha de inicio.",
    schedule: "Calendario de pago",
    scheduleDefault: "Pago único de la cuota de licencia",
    single: "Pago único",
    depositBalance: "Depósito y saldo restante",
    installmentsOption: "Cuotas",
    customSchedule: "Calendario personalizado",
    deposit: "Depósito / pago inicial",
    remaining: "Saldo restante",
    remainingDefault: "Cuota de licencia menos el depósito",
    installmentCount: "Número de cuotas",
    installmentAmounts: "Importes de las cuotas",
    installmentDefault: "Una cuota por la cuota de licencia",
    label: "Etiqueta",
    amount: "Importe",
    addInstallment: "Añadir cuota",
    installmentName: "Cuota {n}",
    commission: "Comisión",
    commissionDefault: "1–19 clientes = 30% · 20–39 = 35% · 40+ = 40%",
    tiers: "Tramos por número de clientes",
    flat: "Comisión recurrente fija",
    product: "Tasa distinta por producto o servicio",
    flatPercent: "Comisión fija %",
    productName: "Producto o servicio",
    percent: "Porcentaje",
    addProduct: "Añadir tasa de producto",
    fallback: "Porcentaje fijo de reserva si un producto no tiene tasa",
    openEnded: "Sin límite",
    addTier: "Añadir tramo",
    minimum: "Objetivo mínimo de clientes",
    minimumDefault: "Sin objetivo mínimo de clientes",
    performance: "Objetivo de rendimiento",
    performanceDefault: "Sin objetivo numérico de rendimiento",
    period: "Periodo de medición del rendimiento",
    periodDefault: "El plazo de la licencia",
    cure: "Plazo de subsanación",
    cureDefault: "30 días",
    renewalPrice: "Precio de renovación",
    renewalPriceDefault: "La cuota de licencia vigente en ese momento",
    renewalTerm: "Plazo de renovación",
    exclusivity: "Exclusivo / No exclusivo",
    nonExclusiveDefault: "No exclusivo",
    additional: "Importes comerciales adicionales",
    none: "Ninguno",
    addAmount: "Añadir importe",
    special: "Condiciones especiales",
    specialDefault: "No hay condiciones comerciales especiales. Las secciones legales fijas no cambian.",
    exclusive: "Exclusivo",
    nonExclusive: "No exclusivo",
  },
  preview: {
    backCreate: "Volver a crear el acuerdo",
    back: "Volver al acuerdo",
    unsaved: "Solo vista previa. No se guardó ningún acuerdo.",
    empty: "Esta vista previa está vacía. Ábrala desde Crear acuerdo. No se ha guardado nada.",
    unreadable: "No se pudo leer esta vista previa. No se ha guardado nada.",
    error: "No se pudo previsualizar el acuerdo.",
    program: "Programa de Partners",
    signedPreserved: "versión firmada conservada",
    currentTemplate: "plantilla actual",
    version: "versión {version}",
    partner: "Partner",
    territory: "Territorio",
    type: "Tipo",
    fee: "Cuota de licencia",
    bizuply: "Bizuply",
    name: "Nombre",
    title: "Cargo",
    signature: "Firma",
    date: "Fecha",
    authorized: "Representante autorizado",
    loading: "Cargando vista previa...",
    issuesTitle: "Estos campos necesitan atención. La vista previa sigue mostrando los valores introducidos. No se guardó nada.",
    issueLegalProfile: "El perfil legal de Bizuply falta o está incompleto.",
    issueLegalCompanyName: "Falta la razón social.",
    issueBrandName: "Falta el nombre del partner o de la marca.",
    issueCountry: "Falta el país o no es un país ISO válido.",
    issueTerritoryType: "Falta el tipo de territorio o no es válido.",
    issueDates: "Faltan las fechas de inicio y fin, o la fecha de fin no es posterior a la de inicio.",
    issueLicenseFee: "Falta la cuota de licencia o el importe no es válido.",
    issueCurrency: "Falta la moneda o el código ISO no es válido.",
    issueContactEmail: "El correo de contacto falta o no es válido.",
    issueSignatoryEmail: "El correo de un firmante falta o no es válido.",
    issueSignatories: "A un firmante requerido le falta el nombre, el cargo o el correo.",
    issueSubdivision: "Elija un estado, provincia, emirato o región antes de una ciudad.",
    issueIncorporation: "Falta el país de constitución o no es un país ISO válido.",
    issueLocale: "Un acuerdo bilingüe necesita dos idiomas distintos.",
    issueCommission: "Las condiciones de comisión no son válidas.",
    issuePayment: "Las condiciones de pago no son válidas.",
    issueGeneric: "Este campo necesita atención.",
  },
  sign: {
    section: "Firmantes",
    partner: "Firmantes del Partner",
    bizuply: "Firmantes de Bizuply",
    requiredPartner: "Firmas requeridas del Partner",
    requiredBizuply: "Firmas requeridas de Bizuply",
    custom: "Personalizado",
    add: "Añadir firmante",
    remove: "Quitar firmante",
    required: "Requerido",
    optional: "Opcional",
    order: "Orden de firma",
    email: "Correo",
    phone: "Teléfono / WhatsApp",
    name: "Nombre legal completo",
    title: "Cargo",
    mode: "Modo de firma",
    parallel: "Paralelo",
    sequential: "Secuencial",
    parallelHelp: "Todos los firmantes requeridos pueden firmar en cualquier orden.",
    sequentialHelp: "El siguiente firmante puede firmar solo después de la firma requerida anterior.",
    status: "Estado",
    signed: "Firmado",
    pending: "Pendiente",
    signedDate: "Fecha de firma",
    resend: "Reenviar enlace de firma",
    revoke: "Revocar enlace de firma",
    signNow: "Firmar como este firmante de Bizuply",
    partnerProgress: "Firmas del Partner",
    bizuplyProgress: "Firmas de Bizuply",
    of: "de",
    completed: "completadas",
    locked: "Alguien ya firmó esta versión. Cree una nueva versión del acuerdo antes de cambiar los firmantes.",
    linkReady: "Enlace de firma listo. No se envió ningún correo.",
    saveFirst: "Guarde el acuerdo antes de enviar un enlace de firma.",
    signPageTitle: "Firmar el acuerdo de Partner",
    signingAs: "Está firmando como",
    typeName: "Escriba su nombre legal completo",
    signButton: "Firmar el acuerdo",
    invalidLink: "Este enlace de firma no es válido.",
    couldNotSign: "No se pudo firmar.",
    signedAgreement: "Firmado",
    company: "Empresa",
    territory: "Territorio",
    exclusivity: "Exclusividad",
    fee: "Cuota",
    dates: "Fechas",
    linkOpen: "Enlace abierto",
    linkConsumed: "Enlace usado",
    linkRevoked: "Enlace revocado",
    linkExpired: "Enlace vencido",
  },
};

const ptBR = {
  list: {
    eyebrow: "Administração Bizuply",
    title: "Contratos de parceiro",
    intro: "O contrato jurídico é um modelo fixo. Crie um registro somente quando estiver pronto para definir o parceiro e as condições comerciais. Nada é gerado ou enviado sozinho.",
    create: "Criar contrato",
    loadError: "Não foi possível carregar os contratos de parceiro.",
    territoryTitle: "Disponibilidade de territórios",
    territoryHelp: "Um país permanece disponível até que um contrato exclusivo seja assinado, pago e ativado.",
    all: "Todos os países",
    available: "Disponível",
    agreement_pending: "Contrato pendente",
    exclusive_active: "Exclusividade ativa",
    renewal_window: "Janela de renovação",
    expiring_soon: "Vence em breve",
    search: "Buscar país, parceiro ou contrato",
    country: "País",
    status: "Status",
    partner: "Parceiro",
    agreement: "Contrato",
    start: "Início",
    expiry: "Vencimento",
    loading: "Carregando territórios...",
    showing: "Mostrando {shown} de {total}. Busque para reduzir a lista.",
    agreements: "Contratos",
    number: "Número",
    type: "Tipo",
    payment: "Pagamento",
    term: "Prazo",
    empty: "Ainda não há contratos.",
    exclusive: "Exclusivo",
    nonExclusive: "Não exclusivo",
    rangeTo: "até",
  },
  status: {
    draft: "Rascunho",
    ready_for_review: "Pronto para revisão",
    sent: "Enviado",
    awaiting_signatures: "Aguardando assinaturas do Parceiro",
    awaiting_partner_signatures: "Aguardando assinaturas do Parceiro",
    awaiting_bizuply_signatures: "Aguardando assinaturas da Bizuply",
    partially_signed: "Parcialmente assinado",
    partner_signed: "Aguardando assinaturas da Bizuply",
    bizuply_signed: "Aguardando assinaturas do Parceiro",
    payment_pending: "Pagamento pendente",
    signed: "Assinado",
    fully_signed: "Totalmente assinado",
    active: "Ativo",
    expired: "Vencido",
    terminated: "Encerrado",
    cancelled: "Cancelado",
    unpaid: "Não pago",
    paid: "Pago",
    pending: "Pendente",
  },
  actions: {
    create: "Criado",
    save_draft: "Rascunho salvo",
    amend: "Nova versão",
    ready_for_review: "Pronto para revisão",
    send: "Enviado para revisão",
    payment_pending: "Pagamento pendente",
    record_payment: "Pagamento registrado",
    activate: "Ativado",
    renew_create: "Renovação criada",
    approve_renewal: "Renovação aprovada",
    expire: "Vencido",
    terminate: "Encerrado",
    cancel: "Cancelado",
    auto_expire: "Vencido automaticamente",
    sign: "Assinado",
    new: "Novo",
  },
  editor: {
    back: "Contratos de parceiro",
    agreement: "Contrato",
    create: "Criar contrato",
    fill: "Preencha os dados comerciais. O texto jurídico permanece no modelo.",
    meta: "{number} · {status} · versão {version}",
    sample: "Apenas uma amostra de teste. Harbor & Co. não é um parceiro real e nada foi salvo.",
    openError: "Não foi possível abrir o contrato.",
    partner: "Parceiro",
    existingPartner: "Parceiro existente",
    searchPartner: "Buscar por nome ou empresa",
    brand: "Nome do parceiro / marca",
    legal: "Razão social",
    registration: "Número de registro",
    incorporation: "País de constituição",
    address: "Endereço registrado",
    contact: "Contato principal",
    contactEmail: "E-mail de contato",
    phone: "Telefone",
    whatsapp: "WhatsApp",
    entity: "Tipo de entidade",
    tax: "Número fiscal / IVA",
    territory: "Território e exclusividade",
    territoryType: "Tipo de território",
    country: "País / território",
    wholeCountry: "País inteiro",
    countryLevel: "Este país é vendido em nível nacional. Um estado ou província não é necessário.",
    locality: "Cidade / região metro / território personalizado",
    city: "Cidade",
    metro: "Região metro",
    customTerritory: "Território personalizado",
    localityPlaceholder: "Opcional. Exemplo: Miami ou sul da Flórida",
    exclusivity: "A exclusividade só entra em vigor depois que todos os signatários exigidos assinarem, o pagamento exigido for concluído e o contrato estiver ativo.",
    exclusiveTaken: "Exclusivo — Indisponível. {name} · {start} até {end}",
    draftNoReserve: "Um rascunho, um contrato enviado ou o interesse de um prospecto não reserva este país.",
    commercial: "Condições comerciais",
    language: "Idioma do contrato",
    bilingual: "Bilíngue com",
    oneLanguage: "Um idioma",
    agreementDate: "Data do contrato",
    paymentStatus: "Status do pagamento",
    renewalNotes: "Notas de renovação",
    quoteTitle: "Simulação de comissão",
    quoteHelp: "Esta calculadora não salva um contrato.",
    customers: "Clientes pagantes ativos",
    gross: "Valor bruto recebido",
    taxes: "Impostos",
    refunds: "Reembolsos",
    chargebacks: "Estornos",
    passThrough: "Uso de repasse",
    calculate: "Calcular comissão",
    quoteError: "Não foi possível calcular a comissão.",
    customCommission: "O perfil deste parceiro tem uma comissão personalizada de {percent}%. Este contrato ainda usa o modelo 30/35/40, a menos que você altere os percentuais.",
    agreementSection: "Contrato",
    agreementNumber: "Número do contrato",
    numberPlaceholder: "Atribuído ao salvar se ficar em branco",
    specialNote: "As condições comerciais especiais ficam na seção comercial. As seções jurídicas fixas não são editadas aqui.",
    save: "Salvar rascunho",
    saved: "Rascunho salvo. O território não foi reservado.",
    saveError: "Não foi possível salvar o rascunho.",
    preview: "Pré-visualizar contrato",
    previewRefused: "A pré-visualização foi recusada porque salvaria um contrato.",
    previewError: "Não foi possível abrir a pré-visualização.",
    newVersion: "Nova versão do contrato / aditivo",
    amendError: "Não foi possível criar uma nova versão do contrato.",
    pdf: "Gerar PDF",
    pdfError: "Não foi possível gerar o PDF.",
    ready: "Pronto para revisão",
    send: "Enviar para revisão",
    markSigned: "Marcar como assinado",
    paymentPending: "Pagamento pendente",
    recordPayment: "Registrar pagamento",
    activate: "Ativar contrato",
    expire: "Vencer",
    terminate: "Encerrar",
    cancel: "Cancelar",
    sendNote: "Enviar para revisão marca o contrato como enviado. Nenhum e-mail é enviado.",
    statusNow: "O status agora é {status}.",
    updateError: "Não foi possível atualizar o contrato.",
    renewTitle: "Renovar",
    renewHelp: "A renovação ativa o próximo prazo no mesmo passo, para que um país exclusivo não fique disponível no intervalo.",
    newNumber: "Novo número do contrato",
    renew: "Renovar",
    renewError: "Não foi possível renovar o contrato.",
    audit: "Auditoria comercial",
    auditHelp: "Alterações manuais registram o campo, o valor anterior, o valor novo, o administrador e o horário. Uma versão assinada não é editada no lugar.",
    admin: "Administrador",
    noAudit: "Nenhuma alteração comercial manual foi salva neste contrato.",
    history: "Histórico",
    version: "Versão {version}",
    versionSigned: "Versão {version} · assinada",
    linkReady: "Link de assinatura pronto. Nenhum e-mail foi enviado.",
    resendError: "Não foi possível reenviar o link de assinatura.",
    revokeError: "Não foi possível revogar o link de assinatura.",
    signError: "Não foi possível assinar pela Bizuply.",
  },
  subdivision: {
    state: "Estado",
    province: "Província / território",
    stateTerritory: "Estado / território",
    emirate: "Emirado",
    union: "Estado / território da união",
    region: "Estado / província / emirado / região",
  },
  country: {
    search: "Buscar países",
    empty: "Nenhum país encontrado.",
    exclusiveUnavailable: "Exclusivo — Indisponível",
    to: "até",
  },
  commercial: {
    title: "Condições comerciais avançadas / manuais",
    help: "O contrato padrão continua sendo o valor inicial. Escolha Personalizado apenas para uma condição negociada. O contrato usa o valor deste acordo e deixa de lado o padrão quando você o substitui.",
    resetAll: "Redefinir a seção comercial",
    customTerm: "Condição personalizada",
    useDefault: "Usar padrão",
    custom: "Personalizado",
    reset: "Voltar ao padrão",
    licenseFee: "Taxa de licença",
    licenseFeeDefault: "Não há um valor padrão. A taxa é preenchida neste contrato.",
    currency: "Moeda",
    duration: "Duração do contrato",
    months12: "12 meses",
    paymentDue: "Data de vencimento do pagamento",
    paymentDueDefault: "Definida quando o contrato é preparado.",
    start: "Data de início",
    startDefault: "Definida para este contrato.",
    end: "Data de término",
    endDefault: "Definida para este contrato. Deve ser posterior à data de início.",
    schedule: "Cronograma de pagamento",
    scheduleDefault: "Pagamento único da taxa de licença",
    single: "Pagamento único",
    depositBalance: "Entrada e saldo restante",
    installmentsOption: "Parcelas",
    customSchedule: "Cronograma personalizado",
    deposit: "Entrada / pagamento antecipado",
    remaining: "Saldo restante",
    remainingDefault: "Taxa de licença menos a entrada",
    installmentCount: "Número de parcelas",
    installmentAmounts: "Valores das parcelas",
    installmentDefault: "Uma parcela da taxa de licença",
    label: "Rótulo",
    amount: "Valor",
    addInstallment: "Adicionar parcela",
    installmentName: "Parcela {n}",
    commission: "Comissão",
    commissionDefault: "1–19 clientes = 30% · 20–39 = 35% · 40+ = 40%",
    tiers: "Faixas por número de clientes",
    flat: "Comissão recorrente fixa",
    product: "Taxa diferente por produto ou serviço",
    flatPercent: "Comissão fixa %",
    productName: "Produto ou serviço",
    percent: "Percentual",
    addProduct: "Adicionar taxa de produto",
    fallback: "Percentual fixo de reserva se o produto não tiver taxa",
    openEnded: "Sem limite",
    addTier: "Adicionar faixa",
    minimum: "Meta mínima de clientes",
    minimumDefault: "Sem meta mínima de clientes",
    performance: "Meta de desempenho",
    performanceDefault: "Sem meta numérica de desempenho",
    period: "Período de medição do desempenho",
    periodDefault: "O prazo da licença",
    cure: "Prazo de regularização",
    cureDefault: "30 dias",
    renewalPrice: "Preço de renovação",
    renewalPriceDefault: "A taxa de licença então vigente",
    renewalTerm: "Prazo de renovação",
    exclusivity: "Exclusivo / Não exclusivo",
    nonExclusiveDefault: "Não exclusivo",
    additional: "Valores comerciais adicionais",
    none: "Nenhum",
    addAmount: "Adicionar valor",
    special: "Condições especiais",
    specialDefault: "Não há condições comerciais especiais. As seções jurídicas fixas permanecem inalteradas.",
    exclusive: "Exclusivo",
    nonExclusive: "Não exclusivo",
  },
  preview: {
    backCreate: "Voltar para criar contrato",
    back: "Voltar ao contrato",
    unsaved: "Somente pré-visualização. Nenhum contrato foi salvo.",
    empty: "Esta pré-visualização está vazia. Abra-a em Criar contrato. Nada foi salvo.",
    unreadable: "Não foi possível ler esta pré-visualização. Nada foi salvo.",
    error: "Não foi possível pré-visualizar o contrato.",
    program: "Programa de parceiros",
    signedPreserved: "versão assinada preservada",
    currentTemplate: "modelo atual",
    version: "versão {version}",
    partner: "Parceiro",
    territory: "Território",
    type: "Tipo",
    fee: "Taxa de licença",
    bizuply: "Bizuply",
    name: "Nome",
    title: "Cargo",
    signature: "Assinatura",
    date: "Data",
    authorized: "Representante autorizado",
    loading: "Carregando pré-visualização...",
    issuesTitle: "Estes campos precisam de atenção. A pré-visualização continua mostrando os valores informados. Nada foi salvo.",
    issueLegalProfile: "O perfil jurídico da Bizuply está ausente ou incompleto.",
    issueLegalCompanyName: "Falta a razão social.",
    issueBrandName: "Falta o nome do parceiro ou da marca.",
    issueCountry: "Falta o país ou ele não é um país ISO válido.",
    issueTerritoryType: "Falta o tipo de território ou ele não é válido.",
    issueDates: "Faltam as datas de início e término, ou a data de término não é posterior à de início.",
    issueLicenseFee: "Falta a taxa de licença ou o valor não é válido.",
    issueCurrency: "Falta a moeda ou o código ISO não é válido.",
    issueContactEmail: "O e-mail de contato está ausente ou não é válido.",
    issueSignatoryEmail: "O e-mail de um signatário está ausente ou não é válido.",
    issueSignatories: "Falta nome, cargo ou e-mail de um signatário obrigatório.",
    issueSubdivision: "Escolha um estado, província, emirado ou região antes de uma cidade.",
    issueIncorporation: "Falta o país de constituição ou ele não é um país ISO válido.",
    issueLocale: "Um contrato bilíngue precisa de dois idiomas diferentes.",
    issueCommission: "As condições de comissão não são válidas.",
    issuePayment: "As condições de pagamento não são válidas.",
    issueGeneric: "Este campo precisa de atenção.",
  },
  sign: {
    section: "Signatários",
    partner: "Signatários do Parceiro",
    bizuply: "Signatários da Bizuply",
    requiredPartner: "Assinaturas exigidas do Parceiro",
    requiredBizuply: "Assinaturas exigidas da Bizuply",
    custom: "Personalizado",
    add: "Adicionar signatário",
    remove: "Remover signatário",
    required: "Obrigatório",
    optional: "Opcional",
    order: "Ordem de assinatura",
    email: "E-mail",
    phone: "Telefone / WhatsApp",
    name: "Nome legal completo",
    title: "Cargo",
    mode: "Modo de assinatura",
    parallel: "Paralelo",
    sequential: "Sequencial",
    parallelHelp: "Todos os signatários exigidos podem assinar em qualquer ordem.",
    sequentialHelp: "O próximo signatário só pode assinar depois que a assinatura exigida anterior estiver concluída.",
    status: "Status",
    signed: "Assinado",
    pending: "Pendente",
    signedDate: "Data da assinatura",
    resend: "Reenviar link de assinatura",
    revoke: "Revogar link de assinatura",
    signNow: "Assinar como este signatário da Bizuply",
    partnerProgress: "Assinaturas do Parceiro",
    bizuplyProgress: "Assinaturas da Bizuply",
    of: "de",
    completed: "concluídas",
    locked: "Alguém já assinou esta versão. Crie uma nova versão do contrato antes de alterar os signatários.",
    linkReady: "Link de assinatura pronto. Nenhum e-mail foi enviado.",
    saveFirst: "Salve o contrato antes de enviar um link de assinatura.",
    signPageTitle: "Assinar contrato de parceiro",
    signingAs: "Você está assinando como",
    typeName: "Digite seu nome legal completo",
    signButton: "Assinar contrato",
    invalidLink: "Este link de assinatura não é válido.",
    couldNotSign: "Não foi possível assinar.",
    signedAgreement: "Assinado",
    company: "Empresa",
    territory: "Território",
    exclusivity: "Exclusividade",
    fee: "Taxa",
    dates: "Datas",
    linkOpen: "Link aberto",
    linkConsumed: "Link usado",
    linkRevoked: "Link revogado",
    linkExpired: "Link expirado",
  },
};

const ar = {
  list: {
    eyebrow: "إدارة Bizuply",
    title: "اتفاقيات الشركاء",
    intro: "الاتفاقية القانونية قالب ثابت. أنشئوا سجلاً فقط عندما تكونون جاهزين لتحديد الشريك والشروط التجارية. لا يُنشأ شيء ولا يُرسل من تلقاء نفسه.",
    create: "إنشاء اتفاقية",
    loadError: "تعذر تحميل اتفاقيات الشركاء.",
    territoryTitle: "توفر الأقاليم",
    territoryHelp: "تبقى الدولة متاحة إلى أن تُوقَّع اتفاقية حصرية ويُستكمل الدفع وتصبح نشطة.",
    all: "كل الدول",
    available: "متاح",
    agreement_pending: "اتفاقية قيد الانتظار",
    exclusive_active: "حصرية نشطة",
    renewal_window: "نافذة التجديد",
    expiring_soon: "تنتهي قريباً",
    search: "ابحثوا عن دولة أو شريك أو اتفاقية",
    country: "الدولة",
    status: "الحالة",
    partner: "الشريك",
    agreement: "الاتفاقية",
    start: "البداية",
    expiry: "الانتهاء",
    loading: "جارٍ تحميل الأقاليم...",
    showing: "يُعرض {shown} من {total}. ابحثوا لتضييق القائمة.",
    agreements: "الاتفاقيات",
    number: "الرقم",
    type: "النوع",
    payment: "الدفع",
    term: "المدة",
    empty: "لا توجد اتفاقيات بعد.",
    exclusive: "حصري",
    nonExclusive: "غير حصري",
    rangeTo: "إلى",
  },
  status: {
    draft: "مسودة",
    ready_for_review: "جاهز للمراجعة",
    sent: "أُرسل",
    awaiting_signatures: "بانتظار تواقيع الشريك",
    awaiting_partner_signatures: "بانتظار تواقيع الشريك",
    awaiting_bizuply_signatures: "بانتظار تواقيع Bizuply",
    partially_signed: "موقّع جزئياً",
    partner_signed: "بانتظار تواقيع Bizuply",
    bizuply_signed: "بانتظار تواقيع الشريك",
    payment_pending: "بانتظار الدفع",
    signed: "موقّع",
    fully_signed: "موقّع بالكامل",
    active: "نشط",
    expired: "منتهٍ",
    terminated: "مُنهى",
    cancelled: "ملغى",
    unpaid: "غير مدفوع",
    paid: "مدفوع",
    pending: "قيد الانتظار",
  },
  actions: {
    create: "أُنشئ",
    save_draft: "حُفظت المسودة",
    amend: "نسخة جديدة",
    ready_for_review: "جاهز للمراجعة",
    send: "أُرسل للمراجعة",
    payment_pending: "بانتظار الدفع",
    record_payment: "سُجّل الدفع",
    activate: "تم التفعيل",
    renew_create: "أُنشئ التجديد",
    approve_renewal: "اعتُمد التجديد",
    expire: "انتهى",
    terminate: "أُنهي",
    cancel: "أُلغي",
    auto_expire: "انتهى تلقائياً",
    sign: "وُقّع",
    new: "جديد",
  },
  editor: {
    back: "اتفاقيات الشركاء",
    agreement: "اتفاقية",
    create: "إنشاء اتفاقية",
    fill: "أكملوا التفاصيل التجارية. النص القانوني يبقى في القالب.",
    meta: "{number} · {status} · النسخة {version}",
    sample: "عينة اختبار فقط. Harbor & Co. ليس شريكاً حقيقياً ولم يُحفظ شيء.",
    openError: "تعذر فتح الاتفاقية.",
    partner: "الشريك",
    existingPartner: "شريك موجود",
    searchPartner: "بحث بالاسم أو الشركة",
    brand: "اسم الشريك / العلامة",
    legal: "الاسم القانوني للشركة",
    registration: "رقم التسجيل",
    incorporation: "دولة التأسيس",
    address: "العنوان المسجّل",
    contact: "جهة الاتصال الرئيسية",
    contactEmail: "بريد الاتصال",
    phone: "الهاتف",
    whatsapp: "واتساب",
    entity: "نوع الكيان",
    tax: "الرقم الضريبي / ضريبة القيمة المضافة",
    territory: "الإقليم والحصرية",
    territoryType: "نوع الإقليم",
    country: "الدولة / الإقليم",
    wholeCountry: "الدولة كاملة",
    countryLevel: "تُباع هذه الدولة على مستوى الدولة. لا يُطلب ولاية أو مقاطعة.",
    locality: "مدينة / منطقة حضرية / إقليم مخصص",
    city: "مدينة",
    metro: "منطقة حضرية",
    customTerritory: "إقليم مخصص",
    localityPlaceholder: "اختياري. مثال: ميامي أو جنوب فلوريدا",
    exclusivity: "تصبح الحصرية سارية فقط بعد توقيع كل الموقّعين المطلوبين، واكتمال الدفع المطلوب، وتفعيل الاتفاقية.",
    exclusiveTaken: "حصري — غير متاح. {name} · {start} إلى {end}",
    draftNoReserve: "المسودة أو الاتفاقية المرسلة أو اهتمام عميل محتمل لا تحجز هذه الدولة.",
    commercial: "الشروط التجارية",
    language: "لغة الاتفاقية",
    bilingual: "ثنائية اللغة مع",
    oneLanguage: "لغة واحدة",
    agreementDate: "تاريخ الاتفاقية",
    paymentStatus: "حالة الدفع",
    renewalNotes: "ملاحظات التجديد",
    quoteTitle: "تقدير العمولة",
    quoteHelp: "هذه الحاسبة لا تحفظ اتفاقية.",
    customers: "عملاء دافعون نشطون",
    gross: "المحصّل الإجمالي",
    taxes: "الضرائب",
    refunds: "المبالغ المستردة",
    chargebacks: "عمليات الاسترداد القسري",
    passThrough: "استخدام التمرير",
    calculate: "حساب العمولة",
    quoteError: "تعذر حساب العمولة.",
    customCommission: "لدى ملف هذا الشريك عمولة مخصصة بنسبة {percent}%. ما زالت هذه الاتفاقية تستخدم قالب 30/35/40 ما لم تغيّروا النسب.",
    agreementSection: "الاتفاقية",
    agreementNumber: "رقم الاتفاقية",
    numberPlaceholder: "يُعيَّن عند الحفظ إذا تُرك فارغاً",
    specialNote: "تُحدَّد الشروط التجارية الخاصة في القسم التجاري. الأقسام القانونية الثابتة لا تُحرَّر هنا.",
    save: "حفظ المسودة",
    saved: "حُفظت المسودة. لم يُحجز الإقليم.",
    saveError: "تعذر حفظ المسودة.",
    preview: "معاينة الاتفاقية",
    previewRefused: "رُفضت المعاينة لأنها كانت ستحفظ اتفاقية.",
    previewError: "تعذر فتح المعاينة.",
    newVersion: "نسخة جديدة من الاتفاقية / تعديل",
    amendError: "تعذر إنشاء نسخة جديدة من الاتفاقية.",
    pdf: "إنشاء PDF",
    pdfError: "تعذر إنشاء ملف PDF.",
    ready: "جاهز للمراجعة",
    send: "إرسال للمراجعة",
    markSigned: "تعليم كموقّع",
    paymentPending: "بانتظار الدفع",
    recordPayment: "تسجيل الدفع",
    activate: "تفعيل الاتفاقية",
    expire: "إنهاء الصلاحية",
    terminate: "إنهاء",
    cancel: "إلغاء",
    sendNote: "الإرسال للمراجعة يعلّم الاتفاقية كمُرسلة. لا يُرسل بريد.",
    statusNow: "الحالة الآن هي {status}.",
    updateError: "تعذر تحديث الاتفاقية.",
    renewTitle: "تجديد",
    renewHelp: "يفعّل التجديد المدة التالية في الخطوة نفسها حتى لا تصبح دولة حصرية متاحة في الفترة الفاصلة.",
    newNumber: "رقم اتفاقية جديد",
    renew: "تجديد",
    renewError: "تعذر تجديد الاتفاقية.",
    audit: "تدقيق تجاري",
    auditHelp: "تسجّل التعديلات اليدوية الحقل والقيمة السابقة والقيمة الجديدة والمسؤول والوقت. لا تُحرَّر النسخة الموقّعة في مكانها.",
    admin: "مسؤول",
    noAudit: "لم تُحفظ تعديلات تجارية يدوية في هذه الاتفاقية.",
    history: "السجل",
    version: "النسخة {version}",
    versionSigned: "النسخة {version} · موقّعة",
    linkReady: "رابط التوقيع جاهز. لم يُرسل بريد.",
    resendError: "تعذر إعادة إرسال رابط التوقيع.",
    revokeError: "تعذر إلغاء رابط التوقيع.",
    signError: "تعذر التوقيع نيابة عن Bizuply.",
  },
  subdivision: {
    state: "ولاية",
    province: "مقاطعة / إقليم",
    stateTerritory: "ولاية / إقليم",
    emirate: "إمارة",
    union: "ولاية / إقليم اتحادي",
    region: "ولاية / مقاطعة / إمارة / منطقة",
  },
  country: {
    search: "البحث عن دول",
    empty: "لا توجد دول مطابقة.",
    exclusiveUnavailable: "حصري — غير متاح",
    to: "إلى",
  },
  commercial: {
    title: "شروط تجارية متقدمة / يدوية",
    help: "تبقى الاتفاقية القياسية هي الافتراضي. اختاروا مخصصاً فقط لشرط تم التفاوض عليه. يستخدم العقد القيمة الموجودة في هذه الاتفاقية ويستبعد الافتراضي عند تجاوزه.",
    resetAll: "إعادة القسم التجاري إلى الافتراضي",
    customTerm: "شرط مخصص",
    useDefault: "استخدام الافتراضي",
    custom: "مخصص",
    reset: "إعادة إلى الافتراضي",
    licenseFee: "رسم الترخيص",
    licenseFeeDefault: "لا يوجد مبلغ قياسي. يُستكمل الرسم لهذه الاتفاقية.",
    currency: "العملة",
    duration: "مدة الاتفاقية",
    months12: "12 شهراً",
    paymentDue: "تاريخ استحقاق الدفع",
    paymentDueDefault: "يُحدَّد عند إعداد الاتفاقية.",
    start: "تاريخ البداية",
    startDefault: "يُحدَّد لهذه الاتفاقية.",
    end: "تاريخ النهاية",
    endDefault: "يُحدَّد لهذه الاتفاقية. يجب أن يكون بعد تاريخ البداية.",
    schedule: "جدول الدفع",
    scheduleDefault: "دفعة واحدة لرسم الترخيص",
    single: "دفعة واحدة",
    depositBalance: "عربون والرصيد المتبقي",
    installmentsOption: "أقساط",
    customSchedule: "جدول مخصص",
    deposit: "عربون / دفعة مقدمة",
    remaining: "الرصيد المتبقي",
    remainingDefault: "رسم الترخيص ناقص العربون",
    installmentCount: "عدد الأقساط",
    installmentAmounts: "مبالغ الأقساط",
    installmentDefault: "قسط واحد لرسم الترخيص",
    label: "التسمية",
    amount: "المبلغ",
    addInstallment: "إضافة قسط",
    installmentName: "القسط {n}",
    commission: "العمولة",
    commissionDefault: "1–19 عميلاً = 30% · 20–39 = 35% · 40+ = 40%",
    tiers: "شرائح حسب عدد العملاء",
    flat: "عمولة متكررة ثابتة",
    product: "نسبة مختلفة حسب المنتج أو الخدمة",
    flatPercent: "نسبة العمولة الثابتة",
    productName: "منتج أو خدمة",
    percent: "النسبة",
    addProduct: "إضافة نسبة منتج",
    fallback: "نسبة ثابتة بديلة إذا لم يكن للمنتج نسبة",
    openEnded: "بلا حد",
    addTier: "إضافة شريحة",
    minimum: "الحد الأدنى لهدف العملاء",
    minimumDefault: "لا يوجد حد أدنى لهدف العملاء",
    performance: "هدف الأداء",
    performanceDefault: "لا يوجد هدف أداء رقمي",
    period: "فترة قياس الأداء",
    periodDefault: "مدة الترخيص",
    cure: "مهلة التصحيح",
    cureDefault: "30 يوماً",
    renewalPrice: "سعر التجديد",
    renewalPriceDefault: "رسم الترخيص الساري حينها",
    renewalTerm: "مدة التجديد",
    exclusivity: "حصري / غير حصري",
    nonExclusiveDefault: "غير حصري",
    additional: "مبالغ تجارية إضافية",
    none: "لا يوجد",
    addAmount: "إضافة مبلغ",
    special: "شروط خاصة",
    specialDefault: "لا توجد شروط تجارية خاصة. تبقى الأقسام القانونية الثابتة دون تغيير.",
    exclusive: "حصري",
    nonExclusive: "غير حصري",
  },
  preview: {
    backCreate: "العودة إلى إنشاء الاتفاقية",
    back: "العودة إلى الاتفاقية",
    unsaved: "معاينة فقط. لم يُحفظ سجل اتفاقية.",
    empty: "هذه المعاينة فارغة. افتحوها من إنشاء الاتفاقية. لم يُحفظ شيء.",
    unreadable: "تعذرت قراءة هذه المعاينة. لم يُحفظ شيء.",
    error: "تعذرت معاينة الاتفاقية.",
    program: "برنامج الشركاء",
    signedPreserved: "نسخة موقّعة محفوظة",
    currentTemplate: "القالب الحالي",
    version: "النسخة {version}",
    partner: "الشريك",
    territory: "الإقليم",
    type: "النوع",
    fee: "رسم الترخيص",
    bizuply: "Bizuply",
    name: "الاسم",
    title: "المنصب",
    signature: "التوقيع",
    date: "التاريخ",
    authorized: "ممثل مفوّض",
    loading: "جارٍ تحميل المعاينة...",
    issuesTitle: "هذه الحقول تحتاج إلى إكمال أو تصحيح. المعاينة ما زالت تعرض القيم التي أُدخلت. لم يُحفظ شيء.",
    issueLegalProfile: "الملف القانوني لـ Bizuply ناقص أو غير مكتمل.",
    issueLegalCompanyName: "اسم الشركة القانوني مفقود.",
    issueBrandName: "اسم الشريك أو العلامة مفقود.",
    issueCountry: "الدولة مفقودة أو ليست رمز دولة ISO صالحاً.",
    issueTerritoryType: "نوع الإقليم مفقود أو غير صالح.",
    issueDates: "تاريخا البداية والنهاية مفقودان، أو تاريخ النهاية ليس بعد تاريخ البداية.",
    issueLicenseFee: "رسم الترخيص مفقود أو المبلغ غير صالح.",
    issueCurrency: "العملة مفقودة أو رمز ISO غير صالح.",
    issueContactEmail: "بريد جهة الاتصال مفقود أو غير صالح.",
    issueSignatoryEmail: "بريد أحد الموقّعين مفقود أو غير صالح.",
    issueSignatories: "ينقص موقّعاً مطلوباً الاسم أو المنصب أو البريد.",
    issueSubdivision: "اختر ولاية أو مقاطعة أو إمارة أو منطقة قبل المدينة.",
    issueIncorporation: "دولة التأسيس مفقودة أو ليست رمز دولة ISO صالحاً.",
    issueLocale: "الاتفاقية ثنائية اللغة تحتاج إلى لغتين مختلفتين.",
    issueCommission: "شروط العمولة غير صالحة.",
    issuePayment: "شروط الدفع غير صالحة.",
    issueGeneric: "هذا الحقل يحتاج إلى انتباه.",
  },
  sign: {
    section: "الموقّعون",
    partner: "موقّعو الشريك",
    bizuply: "موقّعو Bizuply",
    requiredPartner: "تواقيع الشريك المطلوبة",
    requiredBizuply: "تواقيع Bizuply المطلوبة",
    custom: "مخصص",
    add: "إضافة موقّع",
    remove: "إزالة الموقّع",
    required: "مطلوب",
    optional: "اختياري",
    order: "ترتيب التوقيع",
    email: "البريد",
    phone: "الهاتف / واتساب",
    name: "الاسم القانوني الكامل",
    title: "المنصب",
    mode: "وضع التوقيع",
    parallel: "متوازٍ",
    sequential: "متسلسل",
    parallelHelp: "يمكن لجميع الموقّعين المطلوبين التوقيع بأي ترتيب.",
    sequentialHelp: "لا يستطيع الموقّع التالي التوقيع إلا بعد اكتمال التوقيع المطلوب السابق.",
    status: "الحالة",
    signed: "موقّع",
    pending: "قيد الانتظار",
    signedDate: "تاريخ التوقيع",
    resend: "إعادة إرسال رابط التوقيع",
    revoke: "إلغاء رابط التوقيع",
    signNow: "التوقيع بصفة موقّع Bizuply هذا",
    partnerProgress: "تواقيع الشريك",
    bizuplyProgress: "تواقيع Bizuply",
    of: "من",
    completed: "مكتملة",
    locked: "وقّع أحدهم هذه النسخة. أنشئوا نسخة جديدة من الاتفاقية قبل تغيير الموقّعين.",
    linkReady: "رابط التوقيع جاهز. لم يُرسل بريد.",
    saveFirst: "احفظوا الاتفاقية قبل إرسال رابط التوقيع.",
    signPageTitle: "توقيع اتفاقية الشريك",
    signingAs: "أنتم توقّعون بصفة",
    typeName: "اكتبوا الاسم القانوني الكامل",
    signButton: "توقيع الاتفاقية",
    invalidLink: "رابط التوقيع هذا غير صالح.",
    couldNotSign: "تعذر التوقيع.",
    signedAgreement: "تم التوقيع",
    company: "الشركة",
    territory: "الإقليم",
    exclusivity: "الحصرية",
    fee: "الرسم",
    dates: "التواريخ",
    linkOpen: "الرابط مفتوح",
    linkConsumed: "استُخدم الرابط",
    linkRevoked: "أُلغي الرابط",
    linkExpired: "انتهت صلاحية الرابط",
  },
};

const COPY = { en, he, es, "pt-BR": ptBR, ar };

function leafPaths(value, prefix = "") {
  if (value == null || typeof value !== "object" || Array.isArray(value)) return [prefix];
  return Object.keys(value).flatMap((key) => leafPaths(value[key], prefix ? `${prefix}.${key}` : key));
}

const englishPaths = leafPaths(en).sort().join("\n");
for (const locale of LOCALES) {
  const paths = leafPaths(COPY[locale]).sort().join("\n");
  if (paths !== englishPaths) {
    throw new Error(`Partner agreement copy for ${locale} does not match English keys.`);
  }
}

export function fill(template, vars = {}) {
  return String(template || "").replace(/\{(\w+)\}/g, (_, key) => (vars[key] == null ? "" : String(vars[key])));
}

export function partnerAgreementPageCopy(locale) {
  const raw = String(locale || "en").trim().replace(/_/g, "-");
  const lower = raw.toLowerCase();
  let key = "en";
  if (lower === "pt-br" || lower.startsWith("pt-br")) key = "pt-BR";
  else if (lower === "iw" || lower.startsWith("he") || lower.startsWith("iw-")) key = "he";
  else if (lower.startsWith("es")) key = "es";
  else if (lower.startsWith("ar")) key = "ar";
  return {
    locale: key,
    dir: key === "he" || key === "ar" ? "rtl" : "ltr",
    text: COPY[key],
  };
}

export function agreementStatusLabel(code, text) {
  if (!code) return "";
  return text.status[code] || text.actions[code] || String(code).replace(/_/g, " ");
}

export function agreementActionLabel(code, text) {
  if (!code) return "";
  return text.actions[code] || text.status[code] || String(code).replace(/_/g, " ");
}

export function subdivisionLabel(kind, countryCode, text) {
  const labels = text.subdivision;
  if (countryCode === "US" || countryCode === "BR" || countryCode === "MX") return labels.state;
  if (countryCode === "CA") return labels.province;
  if (countryCode === "AU") return labels.stateTerritory;
  if (countryCode === "AE") return labels.emirate;
  if (countryCode === "IN") return labels.union;
  if (kind === "province") return labels.province;
  if (kind === "emirate") return labels.emirate;
  if (kind === "state") return labels.stateTerritory;
  return labels.region;
}

export function linkStateLabel(state, text) {
  if (state === "open" || state === "active") return text.sign.linkOpen;
  if (state === "consumed" || state === "used") return text.sign.linkConsumed;
  if (state === "revoked") return text.sign.linkRevoked;
  if (state === "expired") return text.sign.linkExpired;
  return "";
}
