export type SignatoryLocale = "en" | "he" | "es" | "pt-BR" | "ar";

const COPY = {
  en: {
    section: "Signatories",
    partner: "Partner Signatories",
    bizuply: "Bizuply Signatories",
    requiredPartner: "Required Partner Signatures",
    requiredBizuply: "Required Bizuply Signatures",
    custom: "Custom",
    add: "Add signatory",
    remove: "Remove signatory",
    required: "Required",
    optional: "Optional",
    order: "Signing order",
    email: "Email",
    phone: "Phone / WhatsApp",
    name: "Full legal name",
    title: "Title / position",
    mode: "Signing mode",
    parallel: "Parallel",
    sequential: "Sequential",
    parallelHelp: "All required signatories may sign in any order.",
    sequentialHelp: "The next signatory can sign only after the previous required signature.",
    status: "Status",
    signed: "Signed",
    pending: "Pending",
    signedDate: "Signed date",
    resend: "Resend signing link",
    revoke: "Revoke signing link",
    signNow: "Sign as this Bizuply signatory",
    partnerProgress: "Partner signatures",
    bizuplyProgress: "Bizuply signatures",
    completed: "completed",
    awaitingPartner: "Awaiting Partner Signatures",
    awaitingBizuply: "Awaiting Bizuply Signatures",
    partial: "Partially Signed",
    full: "Fully Signed",
    locked: "Someone has signed this version. Create a new agreement version before changing signatories.",
    linkReady: "Signing link ready. No email was sent.",
    saveFirst: "Save the agreement before sending a signing link.",
    signPageTitle: "Sign Partner Agreement",
    signingAs: "You are signing as",
    typeName: "Type your full legal name",
    signButton: "Sign agreement",
    invalidLink: "This signing link is not valid.",
    couldNotSign: "Could not sign.",
    signedAgreement: "Signed",
    company: "Company",
    territory: "Territory",
    exclusivity: "Exclusivity",
    fee: "Fee",
    dates: "Dates",
  },
  he: {
    section: "חותמים",
    partner: "חותמי השותף",
    bizuply: "חותמי Bizuply",
    requiredPartner: "חתימות שותף נדרשות",
    requiredBizuply: "חתימות Bizuply נדרשות",
    custom: "מותאם",
    add: "הוספת חותם",
    remove: "הסרת חותם",
    required: "נדרש",
    optional: "רשות",
    order: "סדר חתימה",
    email: "דוא״ל",
    phone: "טלפון / וואטסאפ",
    name: "שם משפטי מלא",
    title: "תפקיד",
    mode: "מצב חתימה",
    parallel: "מקביל",
    sequential: "רציף",
    parallelHelp: "כל החותמים הנדרשים יכולים לחתום בכל סדר.",
    sequentialHelp: "החותם הבא יכול לחתום רק אחרי שהחתימה הנדרשת הקודמת הושלמה.",
    status: "סטטוס",
    signed: "נחתם",
    pending: "ממתין",
    signedDate: "תאריך חתימה",
    resend: "שליחה מחדש של קישור החתימה",
    revoke: "ביטול קישור החתימה",
    signNow: "חתימה כחותם זה של Bizuply",
    partnerProgress: "חתימות השותף",
    bizuplyProgress: "חתימות Bizuply",
    completed: "הושלמו",
    awaitingPartner: "ממתין לחתימות השותף",
    awaitingBizuply: "ממתין לחתימות Bizuply",
    partial: "חתום חלקית",
    full: "חתום במלואו",
    locked: "מישהו כבר חתם על גרסה זו. צרו גרסת הסכם חדשה לפני שינוי החותמים.",
    linkReady: "קישור החתימה מוכן. לא נשלח דוא״ל.",
    saveFirst: "שמרו את ההסכם לפני שליחת קישור חתימה.",
    signPageTitle: "חתימה על הסכם פרטנר",
    signingAs: "אתם חותמים בתור",
    typeName: "הקלידו את השם המשפטי המלא",
    signButton: "חתימה על ההסכם",
    invalidLink: "קישור החתימה הזה אינו תקף.",
    couldNotSign: "לא ניתן לחתום.",
    signedAgreement: "נחתם",
    company: "חברה",
    territory: "טריטוריה",
    exclusivity: "בלעדיות",
    fee: "עמלה",
    dates: "תאריכים",
  },
  es: {
    section: "Firmantes",
    partner: "Firmantes del Partner",
    bizuply: "Firmantes de Bizuply",
    requiredPartner: "Firmas requeridas del Partner",
    requiredBizuply: "Firmas requeridas de Bizuply",
    custom: "Personalizado",
    add: "Añadir firmante",
    remove: "Quitar firmante",
    required: "Requerido",
    optional: "Opcional",
    order: "Orden de firma",
    email: "Correo",
    phone: "Teléfono / WhatsApp",
    name: "Nombre legal completo",
    title: "Cargo",
    mode: "Modo de firma",
    parallel: "Paralelo",
    sequential: "Secuencial",
    parallelHelp: "Todos los firmantes requeridos pueden firmar en cualquier orden.",
    sequentialHelp: "El siguiente firmante puede firmar solo después de la firma requerida anterior.",
    status: "Estado",
    signed: "Firmado",
    pending: "Pendiente",
    signedDate: "Fecha de firma",
    resend: "Reenviar enlace de firma",
    revoke: "Revocar enlace de firma",
    signNow: "Firmar como este firmante de Bizuply",
    partnerProgress: "Firmas del Partner",
    bizuplyProgress: "Firmas de Bizuply",
    completed: "completadas",
    awaitingPartner: "En espera de firmas del Partner",
    awaitingBizuply: "En espera de firmas de Bizuply",
    partial: "Firmado parcialmente",
    full: "Totalmente firmado",
    locked: "Alguien ya firmó esta versión. Cree una nueva versión del acuerdo antes de cambiar los firmantes.",
    linkReady: "Enlace de firma listo. No se envió ningún correo.",
    saveFirst: "Guarde el acuerdo antes de enviar un enlace de firma.",
    signPageTitle: "Firmar el acuerdo de Partner",
    signingAs: "Está firmando como",
    typeName: "Escriba su nombre legal completo",
    signButton: "Firmar el acuerdo",
    invalidLink: "Este enlace de firma no es válido.",
    couldNotSign: "No se pudo firmar.",
    signedAgreement: "Firmado",
    company: "Empresa",
    territory: "Territorio",
    exclusivity: "Exclusividad",
    fee: "Cuota",
    dates: "Fechas",
  },
  "pt-BR": {
    section: "Signatários",
    partner: "Signatários do Parceiro",
    bizuply: "Signatários da Bizuply",
    requiredPartner: "Assinaturas exigidas do Parceiro",
    requiredBizuply: "Assinaturas exigidas da Bizuply",
    custom: "Personalizado",
    add: "Adicionar signatário",
    remove: "Remover signatário",
    required: "Obrigatório",
    optional: "Opcional",
    order: "Ordem de assinatura",
    email: "E-mail",
    phone: "Telefone / WhatsApp",
    name: "Nome legal completo",
    title: "Cargo",
    mode: "Modo de assinatura",
    parallel: "Paralelo",
    sequential: "Sequencial",
    parallelHelp: "Todos os signatários exigidos podem assinar em qualquer ordem.",
    sequentialHelp: "O próximo signatário só pode assinar depois que a assinatura exigida anterior estiver concluída.",
    status: "Status",
    signed: "Assinado",
    pending: "Pendente",
    signedDate: "Data da assinatura",
    resend: "Reenviar link de assinatura",
    revoke: "Revogar link de assinatura",
    signNow: "Assinar como este signatário da Bizuply",
    partnerProgress: "Assinaturas do Parceiro",
    bizuplyProgress: "Assinaturas da Bizuply",
    completed: "concluídas",
    awaitingPartner: "Aguardando assinaturas do Parceiro",
    awaitingBizuply: "Aguardando assinaturas da Bizuply",
    partial: "Parcialmente assinado",
    full: "Totalmente assinado",
    locked: "Alguém já assinou esta versão. Crie uma nova versão do contrato antes de alterar os signatários.",
    linkReady: "Link de assinatura pronto. Nenhum e-mail foi enviado.",
    saveFirst: "Salve o contrato antes de enviar um link de assinatura.",
    signPageTitle: "Assinar contrato de parceiro",
    signingAs: "Você está assinando como",
    typeName: "Digite seu nome legal completo",
    signButton: "Assinar contrato",
    invalidLink: "Este link de assinatura não é válido.",
    couldNotSign: "Não foi possível assinar.",
    signedAgreement: "Assinado",
    company: "Empresa",
    territory: "Território",
    exclusivity: "Exclusividade",
    fee: "Taxa",
    dates: "Datas",
  },
  ar: {
    section: "الموقّعون",
    partner: "موقّعو الشريك",
    bizuply: "موقّعو Bizuply",
    requiredPartner: "تواقيع الشريك المطلوبة",
    requiredBizuply: "تواقيع Bizuply المطلوبة",
    custom: "مخصص",
    add: "إضافة موقّع",
    remove: "إزالة الموقّع",
    required: "مطلوب",
    optional: "اختياري",
    order: "ترتيب التوقيع",
    email: "البريد",
    phone: "الهاتف / واتساب",
    name: "الاسم القانوني الكامل",
    title: "المنصب",
    mode: "وضع التوقيع",
    parallel: "متوازٍ",
    sequential: "متسلسل",
    parallelHelp: "يمكن لجميع الموقّعين المطلوبين التوقيع بأي ترتيب.",
    sequentialHelp: "لا يستطيع الموقّع التالي التوقيع إلا بعد اكتمال التوقيع المطلوب السابق.",
    status: "الحالة",
    signed: "موقّع",
    pending: "قيد الانتظار",
    signedDate: "تاريخ التوقيع",
    resend: "إعادة إرسال رابط التوقيع",
    revoke: "إلغاء رابط التوقيع",
    signNow: "التوقيع بصفة موقّع Bizuply هذا",
    partnerProgress: "تواقيع الشريك",
    bizuplyProgress: "تواقيع Bizuply",
    completed: "مكتملة",
    awaitingPartner: "بانتظار تواقيع الشريك",
    awaitingBizuply: "بانتظار تواقيع Bizuply",
    partial: "موقّع جزئياً",
    full: "موقّع بالكامل",
    locked: "وقّع أحدهم هذه النسخة. أنشئوا نسخة جديدة من الاتفاقية قبل تغيير الموقّعين.",
    linkReady: "رابط التوقيع جاهز. لم يُرسل بريد.",
    saveFirst: "احفظوا الاتفاقية قبل إرسال رابط التوقيع.",
    signPageTitle: "توقيع اتفاقية الشريك",
    signingAs: "أنتم توقّعون بصفة",
    typeName: "اكتبوا الاسم القانوني الكامل",
    signButton: "توقيع الاتفاقية",
    invalidLink: "رابط التوقيع هذا غير صالح.",
    couldNotSign: "تعذر التوقيع.",
    signedAgreement: "تم التوقيع",
    company: "الشركة",
    territory: "الإقليم",
    exclusivity: "الحصرية",
    fee: "الرسم",
    dates: "التواريخ",
  },
} as const;

export function signatoryCopy(locale?: string) {
  const key: SignatoryLocale = locale === "he" || locale === "es" || locale === "pt-BR" || locale === "ar" ? locale : "en";
  return {
    locale: key,
    dir: key === "he" || key === "ar" ? ("rtl" as const) : ("ltr" as const),
    text: COPY[key],
  };
}

export function signatureStatusText(
  code: string | undefined,
  text: (typeof COPY)["en"]
) {
  if (code === "fully_signed") return text.full;
  if (code === "partially_signed") return text.partial;
  if (code === "awaiting_bizuply_signatures") return text.awaitingBizuply;
  if (code === "awaiting_partner_signatures" || code === "awaiting_signatures") return text.awaitingPartner;
  return "";
}
